//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:53 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float
// TEXCOORD                 1   xyzw        1     NONE   float   xyz
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float   xyz
// TEXCOORD                 4   xyzw        4     NONE   float   x zw
// TEXCOORD                 5   xyzw        5     NONE   float   xy
// TEXCOORD                 6   xyzw        6     NONE   float
// TEXCOORD                 7   xyzw        7     NONE   float
// POSITION                 0   xyz         8     NONE   float   xyz
// POSITION                 1   xy          9     NONE   float   xy
// POSITION                 2   xyz        10     NONE   float   xyz
// SV_VERTEXID              0   x          11   VERTID    uint
// SV_InstanceID            0   x          12   INSTID    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float   xyz
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// SV_POSITION              0   xyzw        4      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[116], immediateIndexed
dcl_constantbuffer cb12[8], immediateIndexed
dcl_constantbuffer cb1[7], immediateIndexed
dcl_input v1.xyz
dcl_input v2.xyzw
dcl_input v3.xyz
dcl_input v4.xzw
dcl_input v5.xy
dcl_input v8.xyz
dcl_input v9.xy
dcl_input v10.xyz
dcl_output o0.xyzw
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xyzw
dcl_output_siv o4.xyzw, position
dcl_temps 7
mul r0.xyz, v1.yyyy, cb1[1].xyzx
mad r0.xyz, cb1[0].xyzx, v1.xxxx, r0.xyzx
mad r0.xyz, cb1[2].xyzx, v1.zzzz, r0.xyzx
add r0.xyz, r0.xyzx, cb1[3].xyzx
add r1.xyz, -r0.xyzx, cb12[7].xyzx
add r0.xyz, r0.xyzx, -cb12[7].xyzx
dp3 r0.x, -cb12[6].xyzx, r0.xyzx
dp3 r0.y, r1.xyzx, r1.xyzx
sqrt r0.y, r0.y
add r0.z, r0.y, l(-1.000000)
add r0.y, -r0.y, l(10000.000000)
min_sat r0.y, r0.y, r0.z
mul r0.y, r0.y, cb0[5].z
mul r0.z, v4.w, l(1760.000000)
div r0.x, r0.x, r0.z
max r0.x, r0.x, l(1.000000)
mul r0.z, r0.x, r0.x
mul r0.x, r0.x, v4.w
div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
mul r0.y, r0.z, r0.y
mul r0.y, r0.y, cb0[115].x
lt r0.z, l(0.999000), v2.w
movc r0.y, r0.z, l(0), r0.y
mov o0.z, r0.y
lt r0.y, r0.y, l(0.000001)
mov r1.w, l(0)
mul r0.z, l(3.141000), cb0[108].x
sincos r2.x, r3.x, r0.z
mad r2.yzw, v8.xxyz, cb1[4].xxyz, cb1[5].xxyz
mul r1.xyz, r2.yzwy, r3.xxxx
dp3 r0.z, cb0[109].xyzx, cb0[109].xyzx
rsq r0.z, r0.z
mul r3.yzw, r0.zzzz, cb0[109].xxyz
mul r3.yzw, r2.xxxx, r3.yyzw
mul r4.xyz, r2.wyzw, -r3.zwyz
mad r4.xyz, r2.zwyz, -r3.wyzw, -r4.xyzx
dp3 r0.z, r2.yzwy, -r3.yzwy
mov r4.w, -r0.z
add r1.xyzw, r1.xyzw, r4.xyzw
mul r2.xyz, r1.yzxy, r3.wyzw
mad r2.xyz, r3.zwyz, r1.zxyz, -r2.xyzx
mad r1.xyz, r3.xxxx, r1.xyzx, r2.xyzx
mad r1.xyz, r1.wwww, r3.yzwy, r1.xyzx
mul r0.xzw, r0.xxxx, r1.xxyz
mul r0.xzw, r0.xxzw, v3.xxyz
add r1.x, v4.x, l(3.141000)
mul r1.x, r1.x, l(0.500000)
sincos r1.x, r2.x, r1.x
mul r4.xyz, r0.xzwx, r2.xxxx
mov r4.w, l(0)
dp3 r1.y, v2.xyzx, v2.xyzx
rsq r1.y, r1.y
mul r1.yzw, r1.yyyy, v2.xxyz
mul r1.xyz, r1.yzwy, r1.xxxx
mul r2.yzw, r0.wwxz, -r1.yyzx
mad r5.xyz, r0.zwxz, -r1.zxyz, -r2.yzwy
dp3 r0.x, r0.xzwx, -r1.xyzx
mov r5.w, -r0.x
add r4.xyzw, r4.xyzw, r5.xyzw
mul r0.xzw, r1.zzxy, r4.yyzx
mad r0.xzw, r1.yyzx, r4.zzxy, -r0.xxzw
mad r0.xzw, r2.xxxx, r4.xxyz, r0.xxzw
mad r0.xzw, r4.wwww, r1.xxyz, r0.xxzw
add r0.xzw, r0.xxzw, v1.xxyz
mul r2.yzw, r0.zzzz, cb1[1].xxyz
mad r2.yzw, cb1[0].xxyz, r0.xxxx, r2.yyzw
mad r0.xzw, cb1[2].xxyz, r0.wwww, r2.yyzw
add r0.xzw, r0.xxzw, cb1[3].xxyz
mul r4.xyzw, r0.zzzz, cb12[1].xyzw
mad r4.xyzw, cb12[0].xyzw, r0.xxxx, r4.xyzw
mad r4.xyzw, cb12[2].xyzw, r0.wwww, r4.xyzw
add o2.xyz, -r0.xzwx, cb12[7].xyzx
add r4.xyzw, r4.xyzw, cb12[3].xyzw
mov o0.w, r4.w
mad o0.xy, v9.xyxx, cb1[6].xyxx, cb1[6].zwzz
mov r5.xyz, v10.xyzx
mov r5.w, l(0)
mul r0.xzw, -r3.zzwy, v10.zzxy
mad r6.xyz, v10.yzxy, -r3.wyzw, -r0.xzwx
dp3 r0.x, v10.xyzx, -r3.yzwy
mov r6.w, -r0.x
mad r5.xyzw, r3.xxxx, r5.xyzw, r6.xyzw
mul r0.xzw, r3.wwyz, r5.yyzx
mad r0.xzw, r3.zzwy, r5.zzxy, -r0.xxzw
mad r0.xzw, r3.xxxx, r5.xxyz, r0.xxzw
mad r0.xzw, r5.wwww, r3.yyzw, r0.xxzw
mul r3.xyz, r0.xzwx, r2.xxxx
mul r2.yzw, -r1.yyzx, r0.wwxz
mad r5.xyz, r0.zwxz, -r1.zxyz, -r2.yzwy
dp3 r0.x, r0.xzwx, -r1.xyzx
mov r5.w, -r0.x
mov r3.w, l(0)
add r3.xyzw, r3.xyzw, r5.xyzw
mul r0.xzw, r1.zzxy, r3.yyzx
mad r0.xzw, r1.yyzx, r3.zzxy, -r0.xxzw
mad r0.xzw, r2.xxxx, r3.xxyz, r0.xxzw
mad r0.xzw, r3.wwww, r1.xxyz, r0.xxzw
mul r1.xyz, r0.zzzz, cb1[1].xyzx
mad r1.xyz, cb1[0].xyzx, r0.xxxx, r1.xyzx
mad o1.xyz, cb1[2].xyzx, r0.wwww, r1.xyzx
mov o3.xy, v4.zwzz
mov o3.zw, v5.xxxy
lt r0.x, v5.x, l(0.000001)
or r0.x, r0.x, r0.y
movc o4.xyzw, r0.xxxx, l(10000.000000,10000.000000,-10000.000000,1.000000), r4.xyzw
ret
// Approximately 0 instruction slots used
