//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:11 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float      w
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   x
// SV_VERTEXID              0   x           3   VERTID    uint   x
// SV_InstanceID            0   x           4   INSTID    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float   xyz
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// SV_POSITION              0   xyzw        3      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[113], immediateIndexed
dcl_constantbuffer cb12[8], immediateIndexed
dcl_constantbuffer cb1[4], immediateIndexed
dcl_input v0.w
dcl_input v1.xyzw
dcl_input v2.x
dcl_input_sgv v3.x, vertex_id
dcl_output o0.xyzw
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output_siv o3.xyzw, position
dcl_temps 3
dcl_indexableTemp x0[4], 4
dcl_indexableTemp x1[4], 4
mov x0[0].xy, l(-1.000000,1.000000,0,0)
mov x0[1].xy, l(-1.000000,-1.000000,0,0)
mov x0[2].xy, l(1.000000,1.000000,0,0)
mov x0[3].xy, l(1.000000,-1.000000,0,0)
mov x1[0].xy, l(0,0,0,0)
mov x1[1].xy, l(0,1.000000,0,0)
mov x1[2].xy, l(1.000000,0,0,0)
mov x1[3].xy, l(1.000000,1.000000,0,0)
itof r0.x, v3.x
add r0.x, r0.x, l(0.500000)
mad r0.x, r0.x, l(0.250000), l(-0.500000)
round_ne r0.x, r0.x
ftoi r0.x, r0.x
ishl r0.x, r0.x, l(2)
iadd r0.x, -r0.x, v3.x
mov o0.xy, x1[r0.x + 0].xyxx
mov r0.xy, x0[r0.x + 0].xyxx
sincos r1.x, r2.x, v1.w
mul r0.zw, r0.yyyx, r1.xxxx
mad r0.y, r0.y, r2.x, r0.w
mad r0.x, r0.x, r2.x, -r0.z
mul r0.xzw, r0.xxxx, cb12[4].xxyz
mul r1.xyz, r0.yyyy, cb12[5].xyzx
mul r2.xyz, v1.yyyy, cb1[1].xyzx
mad r2.xyz, cb1[0].xyzx, v1.xxxx, r2.xyzx
mad r2.xyz, cb1[2].xyzx, v1.zzzz, r2.xyzx
add r2.xyz, r2.xyzx, cb1[3].xyzx
mad r0.xyz, r0.xzwx, l(0.001000, 0.001000, 0.001000, 0.000000), r2.xyzx
add r2.xyz, -r2.xyzx, cb12[7].xyzx
dp3 r0.w, r2.xyzx, r2.xyzx
sqrt r0.w, r0.w
mad r0.xyz, r1.xyzx, l(0.001000, 0.001000, 0.001000, 0.000000), r0.xyzx
mul r1.xyzw, r0.yyyy, cb12[1].xyzw
mad r1.xyzw, cb12[0].xyzw, r0.xxxx, r1.xyzw
mad r1.xyzw, cb12[2].xyzw, r0.zzzz, r1.xyzw
add o2.xyz, -r0.xyzx, cb12[7].xyzx
add r1.xyzw, r1.xyzw, cb12[3].xyzw
mov o0.w, r1.w
mul r0.x, v2.x, l(0.280000)
frc r0.x, r0.x
mul r0.y, r0.x, cb0[96].x
add r0.x, -r0.x, cb0[102].x
add r0.x, r0.x, l(1.000000)
mul_sat r0.x, r0.x, l(3.333333)
mad r0.y, -r0.y, cb0[106].x, cb0[106].y
mad_sat r0.y, r0.w, cb0[106].x, r0.y
mul r0.x, r0.x, r0.y
mul r0.x, r0.x, cb0[8].y
mul r0.x, r0.x, cb0[112].x
lt r0.y, l(0.999000), v0.w
movc r0.x, r0.y, l(0), r0.x
mov o0.z, r0.x
lt r0.x, r0.x, l(0.000001)
movc o3.xyzw, r0.xxxx, l(10000.000000,10000.000000,-10000.000000,1.000000), r1.xyzw
mov o1.xyz, cb12[6].xyzx
ret
// Approximately 0 instruction slots used
