//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:52 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float      w
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float   xy w
// TEXCOORD                 4   xyzw        4     NONE   float   xy w
// TEXCOORD                 5   xyzw        5     NONE   float   xyzw
// TEXCOORD                 6   xyzw        6     NONE   float   xyzw
// TEXCOORD                 7   xyzw        7     NONE   float   xy
// TEXCOORD                 8   xyzw        8     NONE   float
// TEXCOORD                 9   xyzw        9     NONE   float
// SV_VERTEXID              0   x          10   VERTID    uint   x
// SV_InstanceID            0   x          11   INSTID    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float   xyz
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyzw        4     NONE   float   xyzw
// TEXCOORD                 5   xyzw        5     NONE   float   xyzw
// TEXCOORD                 6   xyzw        6     NONE   float   xyzw
// TEXCOORD                 7   xy          7     NONE   float   xy
// SV_POSITION              0   xyzw        8      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[128], immediateIndexed
dcl_constantbuffer cb12[8], immediateIndexed
dcl_constantbuffer cb1[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.w
dcl_input v2.xyzw
dcl_input v3.xyw
dcl_input v4.xyw
dcl_input v5.xyzw
dcl_input v6.xyzw
dcl_input v7.xy
dcl_input_sgv v10.x, vertex_id
dcl_output o0.xyzw
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_output o5.xyzw
dcl_output o6.xyzw
dcl_output o7.xy
dcl_output_siv o8.xyzw, position
dcl_temps 3
dcl_indexableTemp x0[4], 4
dcl_indexableTemp x1[4], 4
mov x0[0].xy, l(-1.000000,1.000000,0,0)
mov x0[1].xy, l(-1.000000,-1.000000,0,0)
mov x0[2].xy, l(1.000000,1.000000,0,0)
mov x0[3].xy, l(1.000000,-1.000000,0,0)
mov x1[0].xy, l(0,0,0,0)
mov x1[1].xy, l(0,1.000000,0,0)
mov x1[2].xy, l(1.000000,0,0,0)
mov x1[3].xy, l(1.000000,1.000000,0,0)
itof r0.x, v10.x
add r0.x, r0.x, l(0.500000)
mad r0.x, r0.x, l(0.250000), l(-0.500000)
round_ne r0.x, r0.x
ftoi r0.x, r0.x
ishl r0.x, r0.x, l(2)
iadd r0.x, -r0.x, v10.x
mov o0.xy, x1[r0.x + 0].xyxx
mov r0.xy, x0[r0.x + 0].xyxx
mul r0.xy, r0.yxyy, v3.yxyy
mad r0.z, v7.y, l(6.282000), v3.w
sincos r1.x, r2.x, r0.z
mul r0.zw, r0.xxxy, r1.xxxx
mad r0.x, r0.x, r2.x, r0.w
mad r0.y, r0.y, r2.x, -r0.z
mul r1.xyz, v2.yyyy, cb1[1].xyzx
mad r1.xyz, cb1[0].xyzx, v2.xxxx, r1.xyzx
mad r1.xyz, cb1[2].xyzx, v2.zzzz, r1.xyzx
add r1.xyz, r1.xyzx, cb1[3].xyzx
mul r2.xyz, v6.yyyy, cb12[4].xyzx
mad r0.yzw, r2.xxyz, r0.yyyy, r1.xxyz
mul r2.xyz, v6.yyyy, cb12[5].xyzx
mad r0.xyz, r2.xyzx, r0.xxxx, r0.yzwy
mul r2.xyzw, r0.yyyy, cb12[1].xyzw
mad r2.xyzw, cb12[0].xyzw, r0.xxxx, r2.xyzw
mad r2.xyzw, cb12[2].xyzw, r0.zzzz, r2.xyzw
add r2.xyzw, r2.xyzw, cb12[3].xyzw
mov o0.w, r2.w
mul r0.w, cb0[9].y, cb0[127].x
lt r1.w, l(0.999000), v2.w
movc r0.w, r1.w, l(0), r0.w
mov o0.z, r0.w
add r1.xyz, -r1.xyzx, r0.xyzx
add o2.xyz, -r0.xyzx, cb12[7].xyzx
dp3 r0.x, r1.xyzx, r1.xyzx
rsq r0.x, r0.x
mad r0.xyz, r1.xyzx, r0.xxxx, -cb12[6].xyzx
mad o1.xyz, r0.xyzx, l(0.850000, 0.850000, 0.850000, 0.000000), cb12[6].xyzx
mov o3.xyzw, v0.xyzw
mov o4.xyw, v4.xyxw
mov o4.z, v1.w
mov o5.xyzw, v5.xyzw
mov o6.x, l(0)
mov o6.yzw, v6.xxyz
mov o7.x, v6.w
mov o7.y, v7.x
add r0.x, v6.z, v6.w
lt r0.xw, r0.xxxw, l(0.000001, 0.000000, 0.000000, 0.000001)
or r0.x, r0.x, r0.w
movc o8.xyzw, r0.xxxx, l(10000.000000,10000.000000,-10000.000000,1.000000), r2.xyzw
ret
// Approximately 0 instruction slots used
