//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:08 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyzw        1     NONE   float   xyzw
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy
// SV_VERTEXID              0   x           4   VERTID    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// TEXCOORD                 8   xyzw        5     NONE   float   xyzw
// SV_POSITION              0   xyzw        6      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[34], immediateIndexed
dcl_constantbuffer cb12[16], immediateIndexed
dcl_constantbuffer cb1[24], dynamicIndexed
dcl_resource_buffer (float,float,float,float) t0
dcl_resource_buffer (uint,uint,uint,uint) t1
dcl_input v0.xyzw
dcl_input v1.xyzw
dcl_input v2.xyzw
dcl_input v3.xy
dcl_input_sgv v4.x, vertex_id
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xyzw
dcl_output_siv o6.xyzw, position
dcl_temps 17
umin r0.x, v4.x, cb1[4].w
ld_indexable(buffer)(float,float,float,float) r0.xyzw, r0.xxxx, t0.xyzw
mad r1.xyz, v0.xyzx, cb1[5].wwww, cb1[5].xyzx
add r1.w, cb0[2].x, cb0[3].x
add r1.w, r1.w, cb0[4].x
mad r1.w, r1.w, r0.z, cb0[1].x
mad_sat r2.x, r0.z, cb0[5].x, cb0[5].y
mul r1.w, r1.w, r2.x
mul r1.w, r1.w, l(3.141000)
sincos r2.x, r3.x, r1.w
dp3 r1.w, cb0[0].xyzx, cb0[0].xyzx
rsq r1.w, r1.w
mul r2.yzw, r1.wwww, cb0[0].xxyz
mul r2.xyz, r2.yzwy, r2.xxxx
add r3.yzw, r1.xxyz, -cb0[6].xxyz
mul r4.xyz, -r2.yzxy, r3.wyzw
mad r4.xyz, r3.zwyz, -r2.zxyz, -r4.xyzx
dp3 r1.w, r3.yzwy, -r2.xyzx
mov r4.w, -r1.w
mul r5.xyz, r3.yzwy, r3.xxxx
mov r5.w, l(0)
add r4.xyzw, r4.xyzw, r5.xyzw
mul r3.yzw, r2.zzxy, r4.yyzx
mad r3.yzw, r2.yyzx, r4.zzxy, -r3.yyzw
mad r3.yzw, r3.xxxx, r4.xxyz, r3.yyzw
mad r3.yzw, r4.wwww, r2.xxyz, r3.yyzw
add r3.yzw, r3.yyzw, cb0[6].xxyz
mul r4.xyz, -r2.yzxy, v1.zxyz
mad r4.xyz, v1.yzxy, -r2.zxyz, -r4.xyzx
dp3 r1.w, v1.xyzx, -r2.xyzx
mov r4.w, -r1.w
mov r5.xyz, v1.xyzx
mov r5.w, l(0)
mad r4.xyzw, r3.xxxx, r5.xyzw, r4.xyzw
mul r5.xyz, r2.zxyz, r4.yzxy
mad r5.xyz, r2.yzxy, r4.zxyz, -r5.xyzx
mad r4.xyz, r3.xxxx, r4.xyzx, r5.xyzx
mad r4.xyz, r4.wwww, r2.xyzx, r4.xyzx
add r5.xyz, r4.xyzx, -v1.xyzx
mul r6.xyz, -r2.yzxy, v2.zxyz
mad r6.xyz, v2.yzxy, -r2.zxyz, -r6.xyzx
dp3 r1.w, v2.xyzx, -r2.xyzx
mov r6.w, -r1.w
mov r7.xyz, v2.xyzx
mov r7.w, l(0)
mad r6.xyzw, r3.xxxx, r7.xyzw, r6.xyzw
mul r8.xyz, r2.zxyz, r6.yzxy
mad r8.xyz, r2.yzxy, r6.zxyz, -r8.xyzx
mad r6.xyz, r3.xxxx, r6.xyzx, r8.xyzx
mad r2.xyz, r6.wwww, r2.xyzx, r6.xyzx
add r2.xyz, r2.xyzx, -v2.xyzx
add r6.xyz, -r1.xyzx, r3.yzwy
add r1.w, cb0[9].x, cb0[10].x
mad r1.w, r1.w, r0.x, cb0[8].x
mad_sat r2.w, r0.x, cb0[11].x, cb0[11].y
mul r1.w, r1.w, r2.w
mul r1.w, r1.w, l(3.141000)
sincos r3.x, r8.x, r1.w
dp3 r1.w, cb0[7].xyzx, cb0[7].xyzx
rsq r1.w, r1.w
mul r8.yzw, r1.wwww, cb0[7].xxyz
mul r8.yzw, r3.xxxx, r8.yyzw
add r9.xyz, r3.yzwy, -cb0[12].xyzx
mul r10.xyz, -r8.zwyz, r9.zxyz
mad r10.xyz, r9.yzxy, -r8.wyzw, -r10.xyzx
dp3 r1.w, r9.xyzx, -r8.yzwy
mov r10.w, -r1.w
mul r9.xyz, r8.xxxx, r9.xyzx
mov r9.w, l(0)
add r9.xyzw, r9.xyzw, r10.xyzw
mul r10.xyz, r8.wyzw, r9.yzxy
mad r10.xyz, r8.zwyz, r9.zxyz, -r10.xyzx
mad r9.xyz, r8.xxxx, r9.xyzx, r10.xyzx
mad r9.xyz, r9.wwww, r8.yzwy, r9.xyzx
add r9.xyz, r9.xyzx, cb0[12].xyzx
mul r10.xyz, r4.zxyz, -r8.zwyz
mad r10.xyz, r4.yzxy, -r8.wyzw, -r10.xyzx
dp3 r1.w, r4.xyzx, -r8.yzwy
mov r10.w, -r1.w
mul r11.xyz, r4.xyzx, r8.xxxx
mov r11.w, l(0)
add r10.xyzw, r10.xyzw, r11.xyzw
mul r11.xyz, r8.wyzw, r10.yzxy
mad r11.xyz, r8.zwyz, r10.zxyz, -r11.xyzx
mad r10.xyz, r8.xxxx, r10.xyzx, r11.xyzx
mad r10.xyz, r10.wwww, r8.yzwy, r10.xyzx
add r4.xyz, -r4.xyzx, r10.xyzx
mul r11.xyz, -r8.zwyz, v2.zxyz
mad r11.xyz, v2.yzxy, -r8.wyzw, -r11.xyzx
dp3 r1.w, v2.xyzx, -r8.yzwy
mov r11.w, -r1.w
mad r11.xyzw, r8.xxxx, r7.xyzw, r11.xyzw
mul r12.xyz, r8.wyzw, r11.yzxy
mad r12.xyz, r8.zwyz, r11.zxyz, -r12.xyzx
mad r11.xyz, r8.xxxx, r11.xyzx, r12.xyzx
mad r8.xyz, r11.wwww, r8.yzwy, r11.xyzx
add r8.xyz, r8.xyzx, -v2.xyzx
add r3.xyz, -r3.yzwy, r9.xyzx
mul r1.w, r2.w, cb0[14].x
mul r1.w, r1.w, l(3.141000)
sincos r11.x, r12.x, r1.w
dp3 r1.w, cb0[13].xyzx, cb0[13].xyzx
rsq r1.w, r1.w
mul r11.yzw, r1.wwww, cb0[13].xxyz
mul r11.xyz, r11.yzwy, r11.xxxx
add r12.yzw, r9.xxyz, -cb0[15].xxyz
mul r13.xyz, -r11.yzxy, r12.wyzw
mad r13.xyz, r12.zwyz, -r11.zxyz, -r13.xyzx
dp3 r1.w, r12.yzwy, -r11.xyzx
mov r13.w, -r1.w
mul r14.xyz, r12.yzwy, r12.xxxx
mov r14.w, l(0)
add r13.xyzw, r13.xyzw, r14.xyzw
mul r12.yzw, r11.zzxy, r13.yyzx
mad r12.yzw, r11.yyzx, r13.zzxy, -r12.yyzw
mad r12.yzw, r12.xxxx, r13.xxyz, r12.yyzw
mad r12.yzw, r13.wwww, r11.xxyz, r12.yyzw
add r12.yzw, r12.yyzw, cb0[15].xxyz
mul r13.xyz, r10.zxyz, -r11.yzxy
mad r13.xyz, r10.yzxy, -r11.zxyz, -r13.xyzx
dp3 r1.w, r10.xyzx, -r11.xyzx
mov r13.w, -r1.w
mul r14.xyz, r10.xyzx, r12.xxxx
mov r14.w, l(0)
add r13.xyzw, r13.xyzw, r14.xyzw
mul r14.xyz, r11.zxyz, r13.yzxy
mad r14.xyz, r11.yzxy, r13.zxyz, -r14.xyzx
mad r13.xyz, r12.xxxx, r13.xyzx, r14.xyzx
mad r13.xyz, r13.wwww, r11.xyzx, r13.xyzx
add r10.xyz, -r10.xyzx, r13.xyzx
mul r13.xyz, -r11.yzxy, v2.zxyz
mad r13.xyz, v2.yzxy, -r11.zxyz, -r13.xyzx
dp3 r1.w, v2.xyzx, -r11.xyzx
mov r13.w, -r1.w
mad r7.xyzw, r12.xxxx, r7.xyzw, r13.xyzw
mul r13.xyz, r7.yzxy, r11.zxyz
mad r13.xyz, r11.yzxy, r7.zxyz, -r13.xyzx
mad r7.xyz, r12.xxxx, r7.xyzx, r13.xyzx
mad r7.xyz, r7.wwww, r11.xyzx, r7.xyzx
add r7.xyz, r7.xyzx, -v2.xyzx
add r9.xyz, -r9.xyzx, r12.yzwy
add r4.xyz, r4.xyzx, r10.xyzx
add r7.xyz, r7.xyzx, r8.xyzx
add r3.xyz, r3.xyzx, r9.xyzx
add r4.xyz, r4.xyzx, r5.xyzx
add r2.xyz, r2.xyzx, r7.xyzx
add r3.xyz, r3.xyzx, r6.xyzx
add r5.xy, r1.yxyy, r3.yxyy
mad r5.xy, r5.xyxx, cb0[16].yxyy, cb0[16].wzww
add r1.w, r5.x, cb0[17].z
mad_sat r1.w, cb0[17].y, |r1.w|, cb0[17].x
log r1.w, r1.w
mul r1.w, r1.w, cb0[18].x
exp r1.w, r1.w
mad r2.w, cb0[19].y, r1.w, cb0[19].x
add r3.w, r5.y, cb0[20].z
mad_sat r3.w, cb0[20].y, |r3.w|, cb0[20].x
log r3.w, r3.w
mul r3.w, r3.w, cb0[21].x
exp r3.w, r3.w
mad r4.w, cb0[22].y, r3.w, cb0[22].x
mul r4.w, r0.x, r4.w
mad r6.x, r2.w, r0.z, r4.w
add r2.w, r5.y, cb0[23].z
mad_sat r2.w, cb0[23].y, |r2.w|, cb0[23].x
add r4.w, r5.y, cb0[24].z
mad_sat r4.w, cb0[24].y, |r4.w|, cb0[24].x
mul r4.w, r0.x, r4.w
mad r2.w, r2.w, r0.z, r4.w
max r2.w, r2.w, l(0.000000)
log r2.w, r2.w
mul r2.w, r2.w, cb0[25].x
exp r2.w, r2.w
mad r2.w, cb0[26].y, r2.w, cb0[26].x
add r4.w, r0.z, r0.x
mul r5.x, r4.w, cb0[27].x
add r5.yz, r0.zzxz, cb0[28].xxxx
mad r5.y, cb0[29].w, r5.y, cb0[29].z
round_ne r5.w, r5.y
add r5.y, -r5.w, r5.y
mad r5.w, |r5.y|, l(-16.000000), l(8.000000)
mul r5.y, r5.w, r5.y
mad r5.w, |r5.y|, l(0.225000), l(0.775000)
mul r5.y, r5.w, r5.y
mad r5.y, cb0[29].x, r5.y, cb0[29].y
mad r5.z, cb0[30].w, r5.z, cb0[30].z
round_ne r5.w, r5.z
add r5.z, -r5.w, r5.z
mad r5.w, |r5.z|, l(-16.000000), l(8.000000)
mul r5.z, r5.w, r5.z
mad r5.w, |r5.z|, l(0.225000), l(0.775000)
mul r5.z, r5.w, r5.z
mad r5.z, cb0[30].x, r5.z, cb0[30].y
mul r5.z, r0.x, r5.z
mad r5.y, r5.y, r0.z, r5.z
mul r5.y, r5.y, cb0[31].x
mad r6.y, r5.x, r5.y, r2.w
mad r1.w, cb0[32].y, r1.w, cb0[32].x
mad r2.w, cb0[33].y, r3.w, cb0[33].x
mul r2.w, r0.x, r2.w
mad r6.z, r1.w, r0.z, r2.w
mad r3.xyz, r6.xyzx, r4.wwww, r3.xyzx
mul r1.w, v0.w, l(32767.099609)
ftoi r1.w, r1.w
imax r2.w, -r1.w, r1.w
ige r3.w, r2.w, l(2048)
ilt r4.w, r1.w, l(0)
ishl r5.x, v4.x, l(1)
movc r5.x, r4.w, r5.x, v4.x
ishl r2.w, r2.w, l(3)
iadd r2.w, r2.w, l(0xffffc000)
bfi r2.w, l(3), l(0), r5.x, r2.w
ld_indexable(buffer)(uint,uint,uint,uint) r5.xyzw, r2.wwww, t1.xyzw
movc r1.w, r3.w, r5.x, r1.w
imul null, r5.x, r1.w, l(3)
imad r6.xy, l(3, 3, 0, 0), r1.wwww, l(1, 2, 0, 0)
if_nz r3.w
  utof r5.zw, r5.zzzw
  mul r5.zw, r5.zzzw, l(0.000000, 0.000000, 0.00392156886, 0.00392156886)
  mov r7.x, cb1[r5.x + 8].w
  mov r7.y, cb1[r6.x + 8].w
  mov r7.z, cb1[r6.y + 8].w
  imul null, r1.w, r5.y, l(3)
  imad r6.zw, l(0, 0, 3, 3), r5.yyyy, l(0, 0, 1, 2)
  mul r8.xyz, r5.wwww, cb1[r1.w + 8].xyzx
  mul r9.x, r5.w, cb1[r1.w + 8].w
  mul r9.y, r5.w, cb1[r6.z + 8].w
  mul r9.z, r5.w, cb1[r6.w + 8].w
  mul r10.xyz, r5.wwww, cb1[r6.z + 8].xyzx
  mul r11.xyz, r5.wwww, cb1[r6.w + 8].xyzx
  mad r8.xyz, cb1[r5.x + 8].xyzx, r5.zzzz, r8.xyzx
  mad r7.xyz, r7.xyzx, r5.zzzz, r9.xyzx
  mad r9.xyz, cb1[r6.x + 8].xyzx, r5.zzzz, r10.xyzx
  mad r10.xyz, cb1[r6.y + 8].xyzx, r5.zzzz, r11.xyzx
  if_nz r4.w
    iadd r1.w, r2.w, l(1)
    ld_indexable(buffer)(uint,uint,uint,uint) r11.xyzw, r1.wwww, t1.xyzw
    utof r5.yz, r11.zzwz
    mul r5.yz, r5.yyzy, l(0.000000, 0.00392156886, 0.00392156886, 0.000000)
    imul null, r6.zw, r11.xxxy, l(0, 0, 3, 3)
    imad r11.xyzw, l(3, 3, 3, 3), r11.xxyy, l(1, 2, 1, 2)
    mul r12.x, r5.y, cb1[r6.z + 8].w
    mul r12.y, r5.y, cb1[r11.x + 8].w
    mul r12.z, r5.y, cb1[r11.y + 8].w
    mad r13.xyz, r5.yyyy, cb1[r6.z + 8].xyzx, r8.xyzx
    add r12.xyz, r7.xyzx, r12.xyzx
    mad r14.xyz, r5.yyyy, cb1[r11.x + 8].xyzx, r9.xyzx
    mad r15.xyz, r5.yyyy, cb1[r11.y + 8].xyzx, r10.xyzx
    mul r16.x, r5.z, cb1[r6.w + 8].w
    mul r16.y, r5.z, cb1[r11.z + 8].w
    mul r16.z, r5.z, cb1[r11.w + 8].w
    mad r8.xyz, r5.zzzz, cb1[r6.w + 8].xyzx, r13.xyzx
    add r7.xyz, r12.xyzx, r16.xyzx
    mad r9.xyz, r5.zzzz, cb1[r11.z + 8].xyzx, r14.xyzx
    mad r10.xyz, r5.zzzz, cb1[r11.w + 8].xyzx, r15.xyzx
  endif
else
  mov r8.xyz, cb1[r5.x + 8].xyzx
  mov r7.x, cb1[r5.x + 8].w
  mov r7.y, cb1[r6.x + 8].w
  mov r7.z, cb1[r6.y + 8].w
  mov r9.xyz, cb1[r6.x + 8].xyzx
  mov r10.xyz, cb1[r6.y + 8].xyzx
endif
add r1.xyz, r1.xyzx, r3.xyzx
add r3.xyz, r7.xyzx, cb12[15].xyzx
mov r8.w, r3.x
mov r1.w, l(1.000000)
dp4 r5.x, r8.xyzw, r1.xyzw
mov r9.w, r3.y
dp4 r5.y, r9.xyzw, r1.xyzw
mov r10.w, r3.z
dp4 r5.z, r10.xyzw, r1.xyzw
mul r3.xyzw, r5.yyyy, cb12[1].xyzw
mad r3.xyzw, cb12[0].xyzw, r5.xxxx, r3.xyzw
mad r3.xyzw, cb12[2].xyzw, r5.zzzz, r3.xyzw
add o6.xyzw, r3.xyzw, cb12[14].xyzw
add o4.xyz, r5.xyzx, cb12[7].xyzx
add r1.xyw, r4.xyxz, v1.xyxz
dp3 r2.w, r1.xywx, r1.xywx
rsq r2.w, r2.w
mul r1.xyw, r1.xyxw, r2.wwww
dp3 r3.x, r8.xyzx, r1.xywx
dp3 r3.y, r9.xyzx, r1.xywx
dp3 r3.z, r10.xyzx, r1.xywx
add r1.xyw, r2.xyxz, v2.xyxz
dp3 r2.x, r1.xywx, r1.xywx
rsq r2.x, r2.x
mul r1.xyw, r1.xyxw, r2.xxxx
dp3 r2.x, r8.xyzx, r1.xywx
dp3 r2.y, r9.xyzx, r1.xywx
dp3 r2.z, r10.xyzx, r1.xywx
mul r1.xyw, r2.yzyx, r3.zxzy
mad r1.xyw, r3.yzyx, r2.zxzy, -r1.xyxw
mul o2.xyz, r1.xywx, v2.wwww
mad r1.xy, v3.xyxx, cb1[6].xyxx, cb1[6].zwzz
mul_sat r1.w, r3.z, cb1[7].z
add_sat o0.w, r1.w, cb1[7].w
mul r1.w, v1.w, l(32767.099609)
ftoi r1.w, r1.w
ishr r2.w, r1.w, l(3)
and r2.w, r2.w, l(4095)
and r1.w, r1.w, l(7)
itof r1.w, r1.w
add o2.w, r1.w, l(0.100000)
ld_indexable(buffer)(uint,uint,uint,uint) r4.xyzw, r2.wwww, t1.xyzw
ishl r4.yw, r4.yyyw, l(0, 8, 0, 8)
or r4.xy, r4.ywyy, r4.xzxx
f16tof32 r4.xy, r4.xyxx
mul o3.zw, r1.xxxy, r4.xxxy
mov o0.xyz, r3.xyzx
mov o1.w, r1.z
mov o1.xyz, r2.xyzx
mov o3.xy, r1.xyxx
mov o5.xyzw, r0.xyzw
ret
// Approximately 0 instruction slots used
