//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:13 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyzw        1     NONE   float   xyzw
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy
// SV_VERTEXID              0   x           4   VERTID    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// TEXCOORD                 8   xyzw        5     NONE   float   xyzw
// SV_POSITION              0   xyzw        6      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[2], immediateIndexed
dcl_constantbuffer cb12[16], immediateIndexed
dcl_constantbuffer cb1[24], dynamicIndexed
dcl_resource_buffer (float,float,float,float) t0
dcl_resource_buffer (uint,uint,uint,uint) t1
dcl_input v0.xyzw
dcl_input v1.xyzw
dcl_input v2.xyzw
dcl_input v3.xy
dcl_input_sgv v4.x, vertex_id
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xyzw
dcl_output_siv o6.xyzw, position
dcl_temps 15
umin r0.x, v4.x, cb1[4].w
ld_indexable(buffer)(float,float,float,float) r0.xyzw, r0.xxxx, t0.xyzw
mad r1.xyzw, v0.xxyz, cb1[5].wwww, cb1[5].xxyz
add r1.x, r1.x, cb0[0].x
mad r1.x, cb0[1].w, r1.x, cb0[1].z
round_ne r2.x, r1.x
add r1.x, r1.x, -r2.x
mad r2.x, |r1.x|, l(-16.000000), l(8.000000)
mul r1.x, r1.x, r2.x
mad r2.x, |r1.x|, l(0.225000), l(0.775000)
mul r1.x, r1.x, r2.x
mad r1.x, cb0[1].x, r1.x, cb0[1].y
mul r2.y, r0.x, r1.x
mul r1.x, v0.w, l(32767.099609)
ftoi r1.x, r1.x
imax r2.w, -r1.x, r1.x
ige r3.x, r2.w, l(2048)
ilt r3.y, r1.x, l(0)
ishl r3.z, v4.x, l(1)
movc r3.z, r3.y, r3.z, v4.x
ishl r2.w, r2.w, l(3)
iadd r2.w, r2.w, l(0xffffc000)
bfi r2.w, l(3), l(0), r3.z, r2.w
ld_indexable(buffer)(uint,uint,uint,uint) r4.xyzw, r2.wwww, t1.xyzw
movc r1.x, r3.x, r4.x, r1.x
imul null, r3.z, r1.x, l(3)
imad r5.xy, l(3, 3, 0, 0), r1.xxxx, l(1, 2, 0, 0)
if_nz r3.x
  utof r3.xw, r4.zzzw
  mul r3.xw, r3.xxxw, l(0.00392156886, 0.000000, 0.000000, 0.00392156886)
  mov r6.x, cb1[r3.z + 8].w
  mov r6.y, cb1[r5.x + 8].w
  mov r6.z, cb1[r5.y + 8].w
  imul null, r1.x, r4.y, l(3)
  imad r4.xy, l(3, 3, 0, 0), r4.yyyy, l(1, 2, 0, 0)
  mul r7.xyz, r3.wwww, cb1[r1.x + 8].xyzx
  mul r8.x, r3.w, cb1[r1.x + 8].w
  mul r8.y, r3.w, cb1[r4.x + 8].w
  mul r8.z, r3.w, cb1[r4.y + 8].w
  mul r4.xzw, r3.wwww, cb1[r4.x + 8].xxyz
  mul r9.xyz, r3.wwww, cb1[r4.y + 8].xyzx
  mad r7.xyz, cb1[r3.z + 8].xyzx, r3.xxxx, r7.xyzx
  mad r6.xyz, r6.xyzx, r3.xxxx, r8.xyzx
  mad r4.xyz, cb1[r5.x + 8].xyzx, r3.xxxx, r4.xzwx
  mad r8.xyz, cb1[r5.y + 8].xyzx, r3.xxxx, r9.xyzx
  if_nz r3.y
    iadd r1.x, r2.w, l(1)
    ld_indexable(buffer)(uint,uint,uint,uint) r9.xyzw, r1.xxxx, t1.xyzw
    utof r3.xy, r9.zwzz
    mul r3.xy, r3.xyxx, l(0.00392156886, 0.00392156886, 0.000000, 0.000000)
    imul null, r5.zw, r9.xxxy, l(0, 0, 3, 3)
    imad r9.xyzw, l(3, 3, 3, 3), r9.xxyy, l(1, 2, 1, 2)
    mul r10.x, r3.x, cb1[r5.z + 8].w
    mul r10.y, r3.x, cb1[r9.x + 8].w
    mul r10.z, r3.x, cb1[r9.y + 8].w
    mad r11.xyz, r3.xxxx, cb1[r5.z + 8].xyzx, r7.xyzx
    add r10.xyz, r6.xyzx, r10.xyzx
    mad r12.xyz, r3.xxxx, cb1[r9.x + 8].xyzx, r4.xyzx
    mad r13.xyz, r3.xxxx, cb1[r9.y + 8].xyzx, r8.xyzx
    mul r14.x, r3.y, cb1[r5.w + 8].w
    mul r14.y, r3.y, cb1[r9.z + 8].w
    mul r14.z, r3.y, cb1[r9.w + 8].w
    mad r7.xyz, r3.yyyy, cb1[r5.w + 8].xyzx, r11.xyzx
    add r6.xyz, r10.xyzx, r14.xyzx
    mad r4.xyz, r3.yyyy, cb1[r9.z + 8].xyzx, r12.xyzx
    mad r8.xyz, r3.yyyy, cb1[r9.w + 8].xyzx, r13.xyzx
  endif
else
  mov r7.xyz, cb1[r3.z + 8].xyzx
  mov r6.x, cb1[r3.z + 8].w
  mov r6.y, cb1[r5.x + 8].w
  mov r6.z, cb1[r5.y + 8].w
  mov r4.xyz, cb1[r5.x + 8].xyzx
  mov r8.xyz, cb1[r5.y + 8].xyzx
endif
mov r2.xz, l(0,0,0,0)
add r1.xyz, r1.yzwy, r2.xyzx
add r2.xyz, r6.xyzx, cb12[15].xyzx
mov r7.w, r2.x
mov r1.w, l(1.000000)
dp4 r3.x, r7.xyzw, r1.xyzw
mov r4.w, r2.y
dp4 r3.y, r4.xyzw, r1.xyzw
mov r8.w, r2.z
dp4 r3.z, r8.xyzw, r1.xyzw
mul r2.xyzw, r3.yyyy, cb12[1].xyzw
mad r2.xyzw, cb12[0].xyzw, r3.xxxx, r2.xyzw
mad r2.xyzw, cb12[2].xyzw, r3.zzzz, r2.xyzw
add o6.xyzw, r2.xyzw, cb12[14].xyzw
add o4.xyz, r3.xyzx, cb12[7].xyzx
dp3 r1.x, v1.xyzx, v1.xyzx
rsq r1.x, r1.x
mul r1.xyw, r1.xxxx, v1.xyxz
dp3 r2.x, r7.xyzx, r1.xywx
dp3 r2.y, r4.xyzx, r1.xywx
dp3 r2.z, r8.xyzx, r1.xywx
dp3 r1.x, v2.xyzx, v2.xyzx
rsq r1.x, r1.x
mul r1.xyw, r1.xxxx, v2.xyxz
dp3 r3.x, r7.xyzx, r1.xywx
dp3 r3.y, r4.xyzx, r1.xywx
dp3 r3.z, r8.xyzx, r1.xywx
mul r1.xyw, r2.zxzy, r3.yzyx
mad r1.xyw, r2.yzyx, r3.zxzy, -r1.xyxw
mul o2.xyz, r1.xywx, v2.wwww
mad r1.xy, v3.xyxx, cb1[6].xyxx, cb1[6].zwzz
mul_sat r1.w, r2.z, cb1[7].z
add_sat o0.w, r1.w, cb1[7].w
mul r1.w, v1.w, l(32767.099609)
ftoi r1.w, r1.w
ishr r2.w, r1.w, l(3)
and r2.w, r2.w, l(4095)
and r1.w, r1.w, l(7)
itof r1.w, r1.w
add o2.w, r1.w, l(0.100000)
ld_indexable(buffer)(uint,uint,uint,uint) r4.xyzw, r2.wwww, t1.xyzw
ishl r4.yw, r4.yyyw, l(0, 8, 0, 8)
or r4.xy, r4.ywyy, r4.xzxx
f16tof32 r4.xy, r4.xyxx
mul o3.zw, r1.xxxy, r4.xxxy
mov o0.xyz, r2.xyzx
mov o1.w, r1.z
mov o1.xyz, r3.xyzx
mov o3.xy, r1.xyxx
mov o5.xyzw, r0.xyzw
ret
// Approximately 0 instruction slots used
