//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:01 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyzw        1     NONE   float   xyzw
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy
// SV_VERTEXID              0   x           4   VERTID    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// SV_POSITION              0   xyzw        5      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[15], immediateIndexed
dcl_constantbuffer cb12[16], immediateIndexed
dcl_constantbuffer cb1[24], dynamicIndexed
dcl_resource_buffer (uint,uint,uint,uint) t1
dcl_input v0.xyzw
dcl_input v1.xyzw
dcl_input v2.xyzw
dcl_input v3.xy
dcl_input_sgv v4.x, vertex_id
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output_siv o5.xyzw, position
dcl_temps 20
mad r0.xyz, v0.xyzx, cb1[5].wwww, cb1[5].xyzx
mul r0.w, l(3.141000), cb0[3].x
sincos r1.x, r2.x, r0.w
dp3 r0.w, cb0[2].xyzx, cb0[2].xyzx
rsq r0.w, r0.w
mul r1.yzw, r0.wwww, cb0[2].xxyz
mul r2.yzw, r1.yyzw, r1.xxxx
add r3.xyz, r0.xyzx, -cb0[4].xyzx
mul r4.xyz, -r2.zwyz, r3.zxyz
mad r4.xyz, r3.yzxy, -r2.wyzw, -r4.xyzx
dp3 r0.w, r3.xyzx, -r2.yzwy
mov r4.w, -r0.w
mul r3.xyz, r2.xxxx, r3.xyzx
mov r3.w, l(0)
add r3.xyzw, r3.xyzw, r4.xyzw
mul r4.xyz, r2.wyzw, r3.yzxy
mad r4.xyz, r2.zwyz, r3.zxyz, -r4.xyzx
mad r3.xyz, r2.xxxx, r3.xyzx, r4.xyzx
mad r3.xyz, r3.wwww, r2.yzwy, r3.xyzx
add r3.xyz, r3.xyzx, cb0[4].xyzx
mul r4.xyz, -r2.zwyz, v1.zxyz
mad r4.xyz, v1.yzxy, -r2.wyzw, -r4.xyzx
dp3 r0.w, v1.xyzx, -r2.yzwy
mov r4.w, -r0.w
mov r5.xyz, v1.xyzx
mov r5.w, l(0)
mad r4.xyzw, r2.xxxx, r5.xyzw, r4.xyzw
mul r5.xyz, r2.wyzw, r4.yzxy
mad r5.xyz, r2.zwyz, r4.zxyz, -r5.xyzx
mad r4.xyz, r2.xxxx, r4.xyzx, r5.xyzx
mad r4.xyz, r4.wwww, r2.yzwy, r4.xyzx
add r5.xyz, r4.xyzx, -v1.xyzx
mul r6.xyz, -r2.zwyz, v2.zxyz
mad r6.xyz, v2.yzxy, -r2.wyzw, -r6.xyzx
dp3 r0.w, v2.xyzx, -r2.yzwy
mov r6.w, -r0.w
mov r7.xyz, v2.xyzx
mov r7.w, l(0)
mad r6.xyzw, r2.xxxx, r7.xyzw, r6.xyzw
mul r8.xyz, r2.wyzw, r6.yzxy
mad r8.xyz, r2.zwyz, r6.zxyz, -r8.xyzx
mad r6.xyz, r2.xxxx, r6.xyzx, r8.xyzx
mad r2.xyz, r6.wwww, r2.yzwy, r6.xyzx
add r2.xyz, r2.xyzx, -v2.xyzx
add r6.xyz, -r0.xyzx, r3.xyzx
mul r0.w, l(3.141000), cb0[5].x
sincos r1.x, r8.x, r0.w
mul r8.yzw, r1.yyzw, r1.xxxx
add r9.xyz, r3.xyzx, -cb0[6].xyzx
mul r10.xyz, -r8.zwyz, r9.zxyz
mad r10.xyz, r9.yzxy, -r8.wyzw, -r10.xyzx
dp3 r0.w, r9.xyzx, -r8.yzwy
mov r10.w, -r0.w
mul r9.xyz, r8.xxxx, r9.xyzx
mov r9.w, l(0)
add r9.xyzw, r9.xyzw, r10.xyzw
mul r10.xyz, r8.wyzw, r9.yzxy
mad r10.xyz, r8.zwyz, r9.zxyz, -r10.xyzx
mad r9.xyz, r8.xxxx, r9.xyzx, r10.xyzx
mad r9.xyz, r9.wwww, r8.yzwy, r9.xyzx
add r9.xyz, r9.xyzx, cb0[6].xyzx
mul r10.xyz, r4.zxyz, -r8.zwyz
mad r10.xyz, r4.yzxy, -r8.wyzw, -r10.xyzx
dp3 r0.w, r4.xyzx, -r8.yzwy
mov r10.w, -r0.w
mul r11.xyz, r4.xyzx, r8.xxxx
mov r11.w, l(0)
add r10.xyzw, r10.xyzw, r11.xyzw
mul r11.xyz, r8.wyzw, r10.yzxy
mad r11.xyz, r8.zwyz, r10.zxyz, -r11.xyzx
mad r10.xyz, r8.xxxx, r10.xyzx, r11.xyzx
mad r10.xyz, r10.wwww, r8.yzwy, r10.xyzx
add r4.xyz, -r4.xyzx, r10.xyzx
mul r11.xyz, -r8.zwyz, v2.zxyz
mad r11.xyz, v2.yzxy, -r8.wyzw, -r11.xyzx
dp3 r0.w, v2.xyzx, -r8.yzwy
mov r11.w, -r0.w
mad r11.xyzw, r8.xxxx, r7.xyzw, r11.xyzw
mul r12.xyz, r8.wyzw, r11.yzxy
mad r12.xyz, r8.zwyz, r11.zxyz, -r12.xyzx
mad r11.xyz, r8.xxxx, r11.xyzx, r12.xyzx
mad r8.xyz, r11.wwww, r8.yzwy, r11.xyzx
add r8.xyz, r8.xyzx, -v2.xyzx
add r3.xyz, -r3.xyzx, r9.xyzx
mul r0.w, l(3.141000), cb0[7].x
sincos r1.x, r11.x, r0.w
mul r11.yzw, r1.yyzw, r1.xxxx
add r12.xyz, r9.xyzx, -cb0[8].xyzx
mul r13.xyz, -r11.zwyz, r12.zxyz
mad r13.xyz, r12.yzxy, -r11.wyzw, -r13.xyzx
dp3 r0.w, r12.xyzx, -r11.yzwy
mov r13.w, -r0.w
mul r12.xyz, r11.xxxx, r12.xyzx
mov r12.w, l(0)
add r12.xyzw, r12.xyzw, r13.xyzw
mul r13.xyz, r11.wyzw, r12.yzxy
mad r13.xyz, r11.zwyz, r12.zxyz, -r13.xyzx
mad r12.xyz, r11.xxxx, r12.xyzx, r13.xyzx
mad r12.xyz, r12.wwww, r11.yzwy, r12.xyzx
add r12.xyz, r12.xyzx, cb0[8].xyzx
mul r13.xyz, r10.zxyz, -r11.zwyz
mad r13.xyz, r10.yzxy, -r11.wyzw, -r13.xyzx
dp3 r0.w, r10.xyzx, -r11.yzwy
mov r13.w, -r0.w
mul r14.xyz, r10.xyzx, r11.xxxx
mov r14.w, l(0)
add r13.xyzw, r13.xyzw, r14.xyzw
mul r14.xyz, r11.wyzw, r13.yzxy
mad r14.xyz, r11.zwyz, r13.zxyz, -r14.xyzx
mad r13.xyz, r11.xxxx, r13.xyzx, r14.xyzx
mad r13.xyz, r13.wwww, r11.yzwy, r13.xyzx
add r10.xyz, -r10.xyzx, r13.xyzx
mul r14.xyz, -r11.zwyz, v2.zxyz
mad r14.xyz, v2.yzxy, -r11.wyzw, -r14.xyzx
dp3 r0.w, v2.xyzx, -r11.yzwy
mov r14.w, -r0.w
mad r14.xyzw, r11.xxxx, r7.xyzw, r14.xyzw
mul r15.xyz, r11.wyzw, r14.yzxy
mad r15.xyz, r11.zwyz, r14.zxyz, -r15.xyzx
mad r14.xyz, r11.xxxx, r14.xyzx, r15.xyzx
mad r11.xyz, r14.wwww, r11.yzwy, r14.xyzx
add r11.xyz, r11.xyzx, -v2.xyzx
add r9.xyz, -r9.xyzx, r12.xyzx
mul r0.w, l(3.141000), cb0[9].x
sincos r1.x, r14.x, r0.w
mul r1.xyz, r1.yzwy, r1.xxxx
add r14.yzw, r12.xxyz, -cb0[10].xxyz
mul r15.xyz, -r1.yzxy, r14.wyzw
mad r15.xyz, r14.zwyz, -r1.zxyz, -r15.xyzx
dp3 r0.w, r14.yzwy, -r1.xyzx
mov r15.w, -r0.w
mul r16.xyz, r14.yzwy, r14.xxxx
mov r16.w, l(0)
add r15.xyzw, r15.xyzw, r16.xyzw
mul r14.yzw, r1.zzxy, r15.yyzx
mad r14.yzw, r1.yyzx, r15.zzxy, -r14.yyzw
mad r14.yzw, r14.xxxx, r15.xxyz, r14.yyzw
mad r14.yzw, r15.wwww, r1.xxyz, r14.yyzw
add r14.yzw, r14.yyzw, cb0[10].xxyz
mul r15.xyz, -r1.yzxy, r13.zxyz
mad r15.xyz, r13.yzxy, -r1.zxyz, -r15.xyzx
dp3 r0.w, r13.xyzx, -r1.xyzx
mov r15.w, -r0.w
mul r16.xyz, r13.xyzx, r14.xxxx
mov r16.w, l(0)
add r15.xyzw, r15.xyzw, r16.xyzw
mul r16.xyz, r1.zxyz, r15.yzxy
mad r16.xyz, r1.yzxy, r15.zxyz, -r16.xyzx
mad r15.xyz, r14.xxxx, r15.xyzx, r16.xyzx
mad r15.xyz, r15.wwww, r1.xyzx, r15.xyzx
add r13.xyz, -r13.xyzx, r15.xyzx
mul r16.xyz, -r1.yzxy, v2.zxyz
mad r16.xyz, v2.yzxy, -r1.zxyz, -r16.xyzx
dp3 r0.w, v2.xyzx, -r1.xyzx
mov r16.w, -r0.w
mad r16.xyzw, r14.xxxx, r7.xyzw, r16.xyzw
mul r17.xyz, r1.zxyz, r16.yzxy
mad r17.xyz, r1.yzxy, r16.zxyz, -r17.xyzx
mad r16.xyz, r14.xxxx, r16.xyzx, r17.xyzx
mad r1.xyz, r16.wwww, r1.xyzx, r16.xyzx
add r1.xyz, r1.xyzx, -v2.xyzx
add r12.xyz, -r12.xyzx, r14.yzwy
mul r0.w, l(3.141000), cb0[12].x
sincos r14.x, r16.x, r0.w
dp3 r0.w, cb0[11].xyzx, cb0[11].xyzx
rsq r0.w, r0.w
mul r16.yzw, r0.wwww, cb0[11].xxyz
mul r16.yzw, r14.xxxx, r16.yyzw
add r17.xyz, r14.yzwy, -cb0[13].xyzx
mul r18.xyz, -r16.zwyz, r17.zxyz
mad r18.xyz, r17.yzxy, -r16.wyzw, -r18.xyzx
dp3 r0.w, r17.xyzx, -r16.yzwy
mov r18.w, -r0.w
mul r17.xyz, r16.xxxx, r17.xyzx
mov r17.w, l(0)
add r17.xyzw, r17.xyzw, r18.xyzw
mul r18.xyz, r16.wyzw, r17.yzxy
mad r18.xyz, r16.zwyz, r17.zxyz, -r18.xyzx
mad r17.xyz, r16.xxxx, r17.xyzx, r18.xyzx
mad r17.xyz, r17.wwww, r16.yzwy, r17.xyzx
add r17.xyz, r17.xyzx, cb0[13].xyzx
mul r18.xyz, r15.zxyz, -r16.zwyz
mad r18.xyz, r15.yzxy, -r16.wyzw, -r18.xyzx
dp3 r0.w, r15.xyzx, -r16.yzwy
mov r18.w, -r0.w
mul r19.xyz, r15.xyzx, r16.xxxx
mov r19.w, l(0)
add r18.xyzw, r18.xyzw, r19.xyzw
mul r19.xyz, r16.wyzw, r18.yzxy
mad r19.xyz, r16.zwyz, r18.zxyz, -r19.xyzx
mad r18.xyz, r16.xxxx, r18.xyzx, r19.xyzx
mad r18.xyz, r18.wwww, r16.yzwy, r18.xyzx
add r15.xyz, -r15.xyzx, r18.xyzx
mul r18.xyz, -r16.zwyz, v2.zxyz
mad r18.xyz, v2.yzxy, -r16.wyzw, -r18.xyzx
dp3 r0.w, v2.xyzx, -r16.yzwy
mov r18.w, -r0.w
mad r7.xyzw, r16.xxxx, r7.xyzw, r18.xyzw
mul r18.xyz, r7.yzxy, r16.wyzw
mad r18.xyz, r16.zwyz, r7.zxyz, -r18.xyzx
mad r7.xyz, r16.xxxx, r7.xyzx, r18.xyzx
mad r7.xyz, r7.wwww, r16.yzwy, r7.xyzx
add r7.xyz, r7.xyzx, -v2.xyzx
add r14.xyz, -r14.yzwy, r17.xyzx
add r13.xyz, r13.xyzx, r15.xyzx
add r1.xyz, r1.xyzx, r7.xyzx
add r7.xyz, r12.xyzx, r14.xyzx
add r10.xyz, r10.xyzx, r13.xyzx
add r1.xyz, r1.xyzx, r11.xyzx
add r7.xyz, r7.xyzx, r9.xyzx
add r4.xyz, r4.xyzx, r10.xyzx
add r1.xyz, r1.xyzx, r8.xyzx
add r3.xyz, r3.xyzx, r7.xyzx
add r4.xyz, r4.xyzx, r5.xyzx
add r1.xyz, r1.xyzx, r2.xyzx
add r2.xyz, r3.xyzx, r6.xyzx
add r2.xyz, r2.xyzx, -cb0[0].xyzx
mad r2.xyz, cb0[14].xxxx, r2.xyzx, cb0[0].xyzx
mul r0.w, v0.w, l(32767.099609)
ftoi r0.w, r0.w
imax r1.w, -r0.w, r0.w
ige r2.w, r1.w, l(2048)
ilt r3.x, r0.w, l(0)
ishl r3.y, v4.x, l(1)
movc r3.y, r3.x, r3.y, v4.x
ishl r1.w, r1.w, l(3)
iadd r1.w, r1.w, l(0xffffc000)
bfi r1.w, l(3), l(0), r3.y, r1.w
ld_indexable(buffer)(uint,uint,uint,uint) r5.xyzw, r1.wwww, t1.xyzw
movc r0.w, r2.w, r5.x, r0.w
imul null, r3.y, r0.w, l(3)
imad r3.zw, l(0, 0, 3, 3), r0.wwww, l(0, 0, 1, 2)
if_nz r2.w
  utof r5.xz, r5.zzwz
  mul r5.xz, r5.xxzx, l(0.00392156886, 0.000000, 0.00392156886, 0.000000)
  mov r6.x, cb1[r3.y + 8].w
  mov r6.y, cb1[r3.z + 8].w
  mov r6.z, cb1[r3.w + 8].w
  imul null, r0.w, r5.y, l(3)
  imad r5.yw, l(0, 3, 0, 3), r5.yyyy, l(0, 1, 0, 2)
  mul r7.xyz, r5.zzzz, cb1[r0.w + 8].xyzx
  mul r8.x, r5.z, cb1[r0.w + 8].w
  mul r8.y, r5.z, cb1[r5.y + 8].w
  mul r8.z, r5.z, cb1[r5.w + 8].w
  mul r9.xyz, r5.zzzz, cb1[r5.y + 8].xyzx
  mul r5.yzw, r5.zzzz, cb1[r5.w + 8].xxyz
  mad r7.xyz, cb1[r3.y + 8].xyzx, r5.xxxx, r7.xyzx
  mad r6.xyz, r6.xyzx, r5.xxxx, r8.xyzx
  mad r8.xyz, cb1[r3.z + 8].xyzx, r5.xxxx, r9.xyzx
  mad r5.xyz, cb1[r3.w + 8].xyzx, r5.xxxx, r5.yzwy
  if_nz r3.x
    iadd r0.w, r1.w, l(1)
    ld_indexable(buffer)(uint,uint,uint,uint) r9.xyzw, r0.wwww, t1.xyzw
    utof r9.zw, r9.zzzw
    mul r9.zw, r9.zzzw, l(0.000000, 0.000000, 0.00392156886, 0.00392156886)
    imul null, r10.xy, r9.xyxx, l(3, 3, 0, 0)
    imad r11.xyzw, l(3, 3, 3, 3), r9.xxyy, l(1, 2, 1, 2)
    mul r12.x, r9.z, cb1[r10.x + 8].w
    mul r12.y, r9.z, cb1[r11.x + 8].w
    mul r12.z, r9.z, cb1[r11.y + 8].w
    mad r10.xzw, r9.zzzz, cb1[r10.x + 8].xxyz, r7.xxyz
    add r12.xyz, r6.xyzx, r12.xyzx
    mad r13.xyz, r9.zzzz, cb1[r11.x + 8].xyzx, r8.xyzx
    mad r9.xyz, r9.zzzz, cb1[r11.y + 8].xyzx, r5.xyzx
    mul r14.x, r9.w, cb1[r10.y + 8].w
    mul r14.y, r9.w, cb1[r11.z + 8].w
    mul r14.z, r9.w, cb1[r11.w + 8].w
    mad r7.xyz, r9.wwww, cb1[r10.y + 8].xyzx, r10.xzwx
    add r6.xyz, r12.xyzx, r14.xyzx
    mad r8.xyz, r9.wwww, cb1[r11.z + 8].xyzx, r13.xyzx
    mad r5.xyz, r9.wwww, cb1[r11.w + 8].xyzx, r9.xyzx
  endif
else
  mov r7.xyz, cb1[r3.y + 8].xyzx
  mov r6.x, cb1[r3.y + 8].w
  mov r6.y, cb1[r3.z + 8].w
  mov r6.z, cb1[r3.w + 8].w
  mov r8.xyz, cb1[r3.z + 8].xyzx
  mov r5.xyz, cb1[r3.w + 8].xyzx
endif
add r0.xyz, r0.xyzx, r2.xyzx
add r2.xyz, r6.xyzx, cb12[15].xyzx
mov r7.w, r2.x
mov r0.w, l(1.000000)
dp4 r3.x, r7.xyzw, r0.xyzw
mov r8.w, r2.y
dp4 r3.y, r8.xyzw, r0.xyzw
mov r5.w, r2.z
dp4 r3.z, r5.xyzw, r0.xyzw
mul r2.xyzw, r3.yyyy, cb12[1].xyzw
mad r2.xyzw, cb12[0].xyzw, r3.xxxx, r2.xyzw
mad r2.xyzw, cb12[2].xyzw, r3.zzzz, r2.xyzw
add o5.xyzw, r2.xyzw, cb12[14].xyzw
add o4.xyz, r3.xyzx, cb12[7].xyzx
mad r0.xyw, cb0[14].xxxx, r4.xyxz, v1.xyxz
dp3 r1.w, r0.xywx, r0.xywx
rsq r1.w, r1.w
mul r0.xyw, r0.xyxw, r1.wwww
dp3 r2.x, r7.xyzx, r0.xywx
dp3 r2.y, r8.xyzx, r0.xywx
dp3 r2.z, r5.xyzx, r0.xywx
mad r0.xyw, cb0[14].xxxx, r1.xyxz, v2.xyxz
dp3 r1.x, r0.xywx, r0.xywx
rsq r1.x, r1.x
mul r0.xyw, r0.xyxw, r1.xxxx
dp3 r1.x, r7.xyzx, r0.xywx
dp3 r1.y, r8.xyzx, r0.xywx
dp3 r1.z, r5.xyzx, r0.xywx
mul r0.xyw, r1.yzyx, r2.zxzy
mad r0.xyw, r2.yzyx, r1.zxzy, -r0.xyxw
mul o2.xyz, r0.xywx, v2.wwww
mad r0.xy, v3.xyxx, cb1[6].xyxx, cb1[6].zwzz
mul_sat r0.w, r2.z, cb1[7].z
add_sat o0.w, r0.w, cb1[7].w
mul r0.w, v1.w, l(32767.099609)
ftoi r0.w, r0.w
ishr r1.w, r0.w, l(3)
and r1.w, r1.w, l(4095)
and r0.w, r0.w, l(7)
itof r0.w, r0.w
add o2.w, r0.w, l(0.100000)
ld_indexable(buffer)(uint,uint,uint,uint) r3.xyzw, r1.wwww, t1.xyzw
ishl r3.yw, r3.yyyw, l(0, 8, 0, 8)
or r3.xy, r3.ywyy, r3.xzxx
f16tof32 r3.xy, r3.xyxx
mul o3.zw, r0.xxxy, r3.xxxy
mov o0.xyz, r2.xyzx
mov o1.w, r0.z
mov o1.xyz, r1.xyzx
mov o3.xy, r0.xyxx
ret
// Approximately 0 instruction slots used
