//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:05 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xy          0     NONE   float   xy
// TEXCOORD                 0   xy          1     NONE   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[21], immediateIndexed
dcl_constantbuffer cb12[8], immediateIndexed
dcl_input v0.xy
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_temps 2
mul r0.x, v0.x, cb0[10].x
mul r0.y, v0.y, cb0[11].x
dp2 r1.x, cb0[19].xyxx, r0.xyxx
dp2 r1.y, cb0[20].xyxx, r0.xyxx
add r0.xy, r1.xyxx, cb0[4].xyxx
add r0.xy, r0.xyxx, cb0[5].xyxx
add r0.xy, r0.xyxx, -cb0[4].xyxx
dp2 r1.x, cb0[17].xyxx, r0.xyxx
dp2 r1.y, cb0[18].xyxx, r0.xyxx
add r0.xy, r1.xyxx, cb0[4].xyxx
mul r1.xyzw, r0.yyyy, cb12[5].xyzw
mad r0.xyzw, cb12[4].xyzw, r0.xxxx, r1.xyzw
add r0.xyzw, r0.xyzw, cb12[6].xyzw
add r0.xyzw, r0.xyzw, cb12[7].xyzw
mul r1.xyz, r0.yyyy, cb12[1].xywx
mad r1.xyz, cb12[0].xywx, r0.xxxx, r1.xyzx
mad r0.xyz, cb12[2].xywx, r0.zzzz, r1.xyzx
mad r0.xyz, cb12[3].xywx, r0.wwww, r0.xyzx
div o0.xyw, r0.xyxz, r0.zzzz
mov o0.z, l(0.990000)
mov o1.xy, v1.xyxx
ret
// Approximately 0 instruction slots used
