//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:51 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyz
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float    y
// SV_VERTEXID              0   x           4   VERTID    uint   x
// SV_InstanceID            0   x           5   INSTID    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float   xyz
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// SV_POSITION              0   xyzw        4      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[106], immediateIndexed
dcl_constantbuffer cb12[8], immediateIndexed
dcl_constantbuffer cb1[4], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyzw
dcl_input v2.xyzw
dcl_input v3.y
dcl_input_sgv v4.x, vertex_id
dcl_output o0.xyzw
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xyzw
dcl_output_siv o4.xyzw, position
dcl_temps 6
dcl_indexableTemp x0[4], 4
dcl_indexableTemp x1[4], 4
mov x0[0].xy, l(-1.000000,1.000000,0,0)
mov x0[1].xy, l(-1.000000,-1.000000,0,0)
mov x0[2].xy, l(1.000000,1.000000,0,0)
mov x0[3].xy, l(1.000000,-1.000000,0,0)
mov x1[0].xy, l(0,0,0,0)
mov x1[1].xy, l(0,1.000000,0,0)
mov x1[2].xy, l(1.000000,0,0,0)
mov x1[3].xy, l(1.000000,1.000000,0,0)
itof r0.x, v4.x
add r0.x, r0.x, l(0.500000)
mad r0.x, r0.x, l(0.250000), l(-0.500000)
round_ne r0.x, r0.x
ftoi r0.x, r0.x
ishl r0.x, r0.x, l(2)
iadd r0.x, -r0.x, v4.x
mov o0.xy, x1[r0.x + 0].xyxx
mov r0.xy, x0[r0.x + 0].xyxx
mul r1.xyz, v0.yyyy, cb1[1].yzxy
mad r1.xyz, cb1[0].yzxy, v0.xxxx, r1.xyzx
mad r1.xyz, cb1[2].yzxy, v0.zzzz, r1.xyzx
dp3 r0.z, r1.xyzx, r1.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, r1.xyzx
mul r2.xyz, v1.yyyy, cb1[1].xyzx
mad r2.xyz, cb1[0].xyzx, v1.xxxx, r2.xyzx
mad r2.xyz, cb1[2].xyzx, v1.zzzz, r2.xyzx
add r2.xyz, r2.xyzx, cb1[3].xyzx
add r3.xyz, -r2.xyzx, cb12[7].xyzx
dp3 r0.z, r3.xyzx, r3.xyzx
rsq r0.z, r0.z
mul r3.xyz, r0.zzzz, r3.xyzx
mul r4.xyz, r1.xyzx, r3.zxyz
mad r4.xyz, r3.yzxy, r1.yzxy, -r4.xyzx
dp3 r0.z, r1.zxyz, r3.xyzx
log r0.z, |r0.z|
mul r0.z, r0.z, l(2.500000)
exp r0.z, r0.z
mad r1.y, r0.z, l(-1.650000), l(2.500000)
dp3 r0.z, r4.xyzx, r4.xyzx
rsq r0.z, r0.z
mul r4.xyz, r0.zzzz, r4.xyzx
mul r5.xyz, r3.yzxy, r4.zxyz
mad r5.xyz, r4.yzxy, r3.zxyz, -r5.xyzx
mov o1.xyz, r3.xyzx
mov r1.x, l(0.850000)
mul r0.xy, r0.yxyy, r1.xyxx
sincos r1.x, r3.x, v2.w
mul r0.zw, r0.xxxy, r1.xxxx
mad r0.y, r0.y, r3.x, -r0.z
mad r0.x, r0.x, r3.x, r0.w
mul r0.xzw, r0.xxxx, r4.xxyz
mul r1.xyz, r0.yyyy, r5.xyzx
mad r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r2.xyzx
mad r0.xyz, r0.xzwx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx
mul r1.xyzw, r0.yyyy, cb12[1].xyzw
mad r1.xyzw, cb12[0].xyzw, r0.xxxx, r1.xyzw
mad r1.xyzw, cb12[2].xyzw, r0.zzzz, r1.xyzw
add o2.xyz, -r0.xyzx, cb12[7].xyzx
add r0.xyzw, r1.xyzw, cb12[3].xyzw
mov o0.w, r0.w
mul r1.x, cb0[10].y, cb0[105].x
lt r1.y, l(0.999000), v1.w
movc r1.x, r1.y, l(0), r1.x
mov o0.z, r1.x
lt r1.x, r1.x, l(0.000001)
mov o3.xyz, v2.xyzx
mov o3.w, v3.y
lt r1.y, v3.y, l(0.000001)
or r1.x, r1.y, r1.x
movc o4.xyzw, r1.xxxx, l(10000.000000,10000.000000,-10000.000000,1.000000), r0.xyzw
ret
// Approximately 0 instruction slots used
