//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:13 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyzw        1     NONE   float   xyzw
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy
// SV_VERTEXID              0   x           4   VERTID    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// TEXCOORD                 8   xyzw        5     NONE   float   xyzw
// SV_POSITION              0   xyzw        6      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_constantbuffer cb12[16], immediateIndexed
dcl_constantbuffer cb1[24], dynamicIndexed
dcl_resource_buffer (float,float,float,float) t0
dcl_resource_buffer (uint,uint,uint,uint) t1
dcl_input v0.xyzw
dcl_input v1.xyzw
dcl_input v2.xyzw
dcl_input v3.xy
dcl_input_sgv v4.x, vertex_id
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xyzw
dcl_output_siv o6.xyzw, position
dcl_temps 13
umin r0.x, v4.x, cb1[4].w
ld_indexable(buffer)(float,float,float,float) r0.xyzw, r0.xxxx, t0.xyzw
mul r1.x, v0.w, l(32767.099609)
ftoi r1.x, r1.x
imax r1.y, -r1.x, r1.x
ige r1.z, r1.y, l(2048)
ilt r1.w, r1.x, l(0)
ishl r2.x, v4.x, l(1)
movc r2.x, r1.w, r2.x, v4.x
ishl r1.y, r1.y, l(3)
iadd r1.y, r1.y, l(0xffffc000)
bfi r1.y, l(3), l(0), r2.x, r1.y
ld_indexable(buffer)(uint,uint,uint,uint) r2.xyzw, r1.yyyy, t1.xyzw
movc r1.x, r1.z, r2.x, r1.x
imul null, r2.x, r1.x, l(3)
imad r3.xy, l(3, 3, 0, 0), r1.xxxx, l(1, 2, 0, 0)
if_nz r1.z
  utof r1.xz, r2.zzwz
  mul r1.xz, r1.xxzx, l(0.00392156886, 0.000000, 0.00392156886, 0.000000)
  mov r4.x, cb1[r2.x + 8].w
  mov r4.y, cb1[r3.x + 8].w
  mov r4.z, cb1[r3.y + 8].w
  imul null, r2.z, r2.y, l(3)
  imad r2.yw, l(0, 3, 0, 3), r2.yyyy, l(0, 1, 0, 2)
  mul r5.xyz, r1.zzzz, cb1[r2.z + 8].xyzx
  mul r6.x, r1.z, cb1[r2.z + 8].w
  mul r6.y, r1.z, cb1[r2.y + 8].w
  mul r6.z, r1.z, cb1[r2.w + 8].w
  mul r7.xyz, r1.zzzz, cb1[r2.y + 8].xyzx
  mul r2.yzw, r1.zzzz, cb1[r2.w + 8].xxyz
  mad r5.xyz, cb1[r2.x + 8].xyzx, r1.xxxx, r5.xyzx
  mad r4.xyz, r4.xyzx, r1.xxxx, r6.xyzx
  mad r6.xyz, cb1[r3.x + 8].xyzx, r1.xxxx, r7.xyzx
  mad r7.xyz, cb1[r3.y + 8].xyzx, r1.xxxx, r2.yzwy
  if_nz r1.w
    iadd r1.x, r1.y, l(1)
    ld_indexable(buffer)(uint,uint,uint,uint) r1.xyzw, r1.xxxx, t1.xyzw
    utof r1.zw, r1.zzzw
    mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 0.00392156886, 0.00392156886)
    imul null, r2.yz, r1.xxyx, l(0, 3, 3, 0)
    imad r8.xyzw, l(3, 3, 3, 3), r1.xxyy, l(1, 2, 1, 2)
    mul r9.x, r1.z, cb1[r2.y + 8].w
    mul r9.y, r1.z, cb1[r8.x + 8].w
    mul r9.z, r1.z, cb1[r8.y + 8].w
    mad r10.xyz, r1.zzzz, cb1[r2.y + 8].xyzx, r5.xyzx
    add r9.xyz, r4.xyzx, r9.xyzx
    mad r11.xyz, r1.zzzz, cb1[r8.x + 8].xyzx, r6.xyzx
    mad r1.xyz, r1.zzzz, cb1[r8.y + 8].xyzx, r7.xyzx
    mul r12.x, r1.w, cb1[r2.z + 8].w
    mul r12.y, r1.w, cb1[r8.z + 8].w
    mul r12.z, r1.w, cb1[r8.w + 8].w
    mad r5.xyz, r1.wwww, cb1[r2.z + 8].xyzx, r10.xyzx
    add r4.xyz, r9.xyzx, r12.xyzx
    mad r6.xyz, r1.wwww, cb1[r8.z + 8].xyzx, r11.xyzx
    mad r7.xyz, r1.wwww, cb1[r8.w + 8].xyzx, r1.xyzx
  endif
else
  mov r5.xyz, cb1[r2.x + 8].xyzx
  mov r4.x, cb1[r2.x + 8].w
  mov r4.y, cb1[r3.x + 8].w
  mov r4.z, cb1[r3.y + 8].w
  mov r6.xyz, cb1[r3.x + 8].xyzx
  mov r7.xyz, cb1[r3.y + 8].xyzx
endif
mad r1.xyz, v0.xyzx, cb1[5].wwww, cb1[5].xyzx
mad r1.xyz, cb0[0].xyzx, r0.yyyy, r1.xyzx
add r2.xyz, r4.xyzx, cb12[15].xyzx
mov r5.w, r2.x
mov r1.w, l(1.000000)
dp4 r3.x, r5.xyzw, r1.xyzw
mov r6.w, r2.y
dp4 r3.y, r6.xyzw, r1.xyzw
mov r7.w, r2.z
dp4 r3.z, r7.xyzw, r1.xyzw
mul r2.xyzw, r3.yyyy, cb12[1].xyzw
mad r2.xyzw, cb12[0].xyzw, r3.xxxx, r2.xyzw
mad r2.xyzw, cb12[2].xyzw, r3.zzzz, r2.xyzw
add o6.xyzw, r2.xyzw, cb12[14].xyzw
add r1.xyw, r3.xyxz, cb12[7].xyxz
dp3 r2.x, v1.xyzx, v1.xyzx
rsq r2.x, r2.x
mul r2.xyz, r2.xxxx, v1.xyzx
dp3 r3.x, r5.xyzx, r2.xyzx
dp3 r3.y, r6.xyzx, r2.xyzx
dp3 r3.z, r7.xyzx, r2.xyzx
dp3 r2.x, v2.xyzx, v2.xyzx
rsq r2.x, r2.x
mul r2.xyz, r2.xxxx, v2.xyzx
dp3 r4.x, r5.xyzx, r2.xyzx
dp3 r4.y, r6.xyzx, r2.xyzx
dp3 r4.z, r7.xyzx, r2.xyzx
mul r2.xyz, r3.zxyz, r4.yzxy
mad r2.xyz, r3.yzxy, r4.zxyz, -r2.xyzx
mul o2.xyz, r2.xyzx, v2.wwww
mad r2.xy, v3.xyxx, cb1[6].xyxx, cb1[6].zwzz
mul_sat r2.z, r3.z, cb1[7].z
add_sat o0.w, r2.z, cb1[7].w
mul r2.z, v1.w, l(32767.099609)
ftoi r2.z, r2.z
ishr r2.w, r2.z, l(3)
and r2.zw, r2.zzzw, l(0, 0, 7, 4095)
itof r2.z, r2.z
add o2.w, r2.z, l(0.100000)
ld_indexable(buffer)(uint,uint,uint,uint) r5.xyzw, r2.wwww, t1.xyzw
ishl r2.zw, r5.yyyw, l(0, 0, 8, 8)
or r2.zw, r2.zzzw, r5.xxxz
f16tof32 r2.zw, r2.zzzw
mul o3.zw, r2.zzzw, r2.xxxy
add r5.xyz, -cb12[7].xyzx, cb12[10].xyzx
add o4.xyz, r1.xywx, r5.xyzx
mov o0.xyz, r3.xyzx
mov o1.w, r1.z
mov o1.xyz, r4.xyzx
mov o3.xy, r2.xyxx
mov o5.xyzw, r0.xyzw
ret
// Approximately 0 instruction slots used
