//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:54 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[99], immediateIndexed
dcl_resource_buffer (float,float,float,float) t0
dcl_uav_typed_buffer (float,float,float,float) u0
dcl_input vThreadID.x
dcl_temps 12
dcl_thread_group 64, 1, 1
add r0.x, l(0.500000), cb0[88].x
ftou r0.x, r0.x
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  ftou r0.x, cb0[98].x
  ftou r0.y, cb0[89].x
  imad r0.y, l(5), vThreadID.x, r0.y
  ld_indexable(buffer)(float,float,float,float) r1.xyzw, r0.yyyy, t0.xyzw
  iadd r2.xyzw, r0.yyyy, l(1, 2, 3, 4)
  ld_indexable(buffer)(float,float,float,float) r3.xyzw, r2.xxxx, t0.xyzw
  ld_indexable(buffer)(float,float,float,float) r4.xzw, r2.yyyy, t0.xwyz
  ld_indexable(buffer)(float,float,float,float) r5.xyzw, r2.zzzz, t0.yzwx
  ld_indexable(buffer)(float,float,float,float) r2.xyz, r2.wwww, t0.yzxw
  mov_sat r6.xy, r5.xyxx
  mad r0.yzw, r6.yyyy, l(0.000000, -1.500000, -0.675824, 0.500000), l(0.000000, 1.000000, 0.675824, 0.500000)
  ge r7.xyz, r6.yyyy, l(0.000000, 0.393333, 1.000000, 0.000000)
  and r7.xyz, r7.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
  add r7.xy, r7.yzyy, r7.xyxx
  add r7.xy, r7.xyxx, l(0.000001, 0.000001, 0.000000, 0.000000)
  mul r7.xy, r7.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  frc r7.xy, r7.xyxx
  mul r0.yz, r0.yyzy, r7.xxyx
  add r0.yz, r0.yyzy, r0.yyzy
  add_sat r0.y, r0.z, r0.y
  mad r0.y, r0.y, l(0.720000), l(0.080000)
  mov_sat r0.z, r3.w
  mad r7.xyzw, r0.zzzz, l(-1.516129, 0.000000, 46.647221, -0.014967), l(0.516129, 0.000000, -115.451866, 0.014967)
  mul r6.y, r0.z, r0.z
  mad r7.x, r7.x, r6.y, l(1.000000)
  min r7.x, r7.x, l(1.000000)
  mad r7.x, r7.x, l(0.750000), l(0.250000)
  mul r8.y, r0.y, r7.x
  mad_sat r0.y, r1.w, l(0.333333), l(-0.666667)
  mad r0.y, r0.y, l(0.850000), l(0.150000)
  mul r8.z, r0.y, r0.w
  mad r0.y, r6.x, l(2.000000), l(-3.000000)
  mul r0.w, r6.x, r6.x
  mad r0.y, r0.y, r0.w, l(1.000000)
  max r0.y, r0.y, l(0.000000)
  mad r8.w, r0.y, l(0.030000), l(0.030000)
  mad r9.xyzw, r0.zzzz, l(6.666667, 90.962074, 17.848076, 0.018089), l(0.000000, -22.157429, 0.992794, 0.131811)
  mad r0.yw, r7.yyyz, r6.yyyy, r9.xxxy
  ge r10.xyzw, r0.zzzz, l(0.000000, 0.150000, 0.650000, 1.000000)
  and r10.xyzw, r10.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
  add r7.xyz, r10.yzwy, r10.xyzx
  add r7.xyz, r7.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
  mul r7.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xz, r0.yywy, r7.xxzx
  add r0.yw, r7.xxxy, r7.xxxy
  add r0.y, r0.w, r0.y
  mad_sat r0.y, r7.z, l(2.000000), r0.y
  mul r10.x, r0.y, l(3.000000)
  mad r0.yw, r0.zzzz, l(0.000000, -4.824325, 0.000000, -0.357361), l(0.000000, 1.000000, 0.000000, 0.207461)
  mad r0.yw, r9.zzzw, r6.yyyy, r0.yyyw
  ge r7.xyz, r0.zzzz, l(0.000000, 0.273333, 1.000000, 0.000000)
  and r7.xyz, r7.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
  add r7.xy, r7.yzyy, r7.xyxx
  add r7.xy, r7.xyxx, l(0.000001, 0.000001, 0.000000, 0.000000)
  mul r7.xy, r7.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  frc r7.xy, r7.xyxx
  mul r0.yw, r0.yyyw, r7.xxxy
  add r0.yw, r0.yyyw, r0.yyyw
  add_sat r0.y, r0.w, r0.y
  add r0.yw, r0.yyyy, l(0.000000, -0.000000, 0.000000, -0.500000)
  add_sat r0.yw, r0.yyyw, r0.yyyw
  mul r0.yw, r0.yyyw, l(0.000000, 150.000000, 0.000000, 350.000000)
  dp2 r10.y, l(1.000000, 1.000000, 0.000000, 0.000000), r0.ywyy
  mad r9.xyzw, r0.zzzz, l(-1.492936, 4.526447, 2.104889, -1.566532), l(-1.327157, -7.226845, -1.776802, 5.966465)
  mad r11.xyzw, r0.zzzz, l(0.000000, 1.863552, -1.857117, -7.242321), l(1.000000, 0.808694, 1.610276, 2.842295)
  mad r9.xyzw, r9.xyzw, r6.yyyy, r11.xyzw
  ge r11.xyzw, r0.zzzz, l(0.000000, 0.283333, 0.527778, 0.755556)
  and r11.xyzw, r11.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
  ge r0.yz, r0.zzzz, l(0.000000, 0.988889, 1.000000, 0.000000)
  and r0.zw, r0.yyyz, l(0, 0, 0x3f800000, 0x3f800000)
  add r7.xyz, r11.yzwy, r11.xyzx
  add r7.xyz, r7.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
  mul r7.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xyz, r9.xyzx, r7.xyzx
  add r0.z, r0.w, r0.z
  add r0.z, r0.z, l(0.000001)
  mul r0.z, r0.z, l(0.500000)
  frc r0.z, r0.z
  mov r0.w, l(2.000000)
  mul r7.xy, r7.xyxx, r0.wwww
  dp2 r0.z, r0.zzzz, r7.wwww
  add r6.y, r7.y, r7.x
  mad r0.w, r0.w, r7.z, r6.y
  mad r0.w, r9.w, r11.w, r0.w
  movc_sat r0.y, r0.y, r0.z, r0.w
  mul r7.xyz, r0.yyyy, l(1.000000, 0.404822, 0.000000, 0.000000)
  mov_sat r10.w, r2.x
  imad r0.x, l(9), vThreadID.x, r0.x
  mov r6.z, l(0.350000)
  mov r6.w, cb0[3].w
  store_uav_typed u0.xyzw, r0.xxxx, r6.zzxw
  iadd r9.xyzw, r0.xxxx, l(1, 2, 3, 4)
  store_uav_typed u0.xyzw, r9.xxxx, r1.xyzw
  store_uav_typed u0.xyzw, r9.yyyy, r3.xyzw
  mov r7.w, r4.x
  store_uav_typed u0.xyzw, r9.zzzz, r7.xyzw
  mov r4.xy, r6.xwxx
  store_uav_typed u0.xyzw, r9.wwww, r4.xyzw
  iadd r1.xyzw, r0.xxxx, l(5, 6, 7, 8)
  mov r8.x, r4.x
  store_uav_typed u0.xyzw, r1.xxxx, r8.xyzw
  mov r10.z, r5.w
  store_uav_typed u0.xyzw, r1.yyyy, r10.xyzw
  mov r5.w, r2.z
  store_uav_typed u0.xyzw, r1.zzzz, r5.xyzw
  mov r2.zw, l(0,0,0,0)
  store_uav_typed u0.xyzw, r1.wwww, r2.xyzw
endif
ret
// Approximately 0 instruction slots used
