//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:53 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[150], immediateIndexed
dcl_resource_buffer (float,float,float,float) t0
dcl_uav_typed_buffer (float,float,float,float) u0
dcl_input vThreadID.x
dcl_temps 6
dcl_thread_group 64, 1, 1
add r0.x, l(0.500000), cb0[89].x
ftou r0.x, r0.x
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  ftou r0.x, cb0[99].x
  ftou r0.y, cb0[90].x
  ishl r0.z, vThreadID.x, l(2)
  iadd r0.xy, r0.zzzz, r0.xyxx
  ld_indexable(buffer)(float,float,float,float) r1.xyzw, r0.yyyy, t0.xyzw
  iadd r2.xyz, r0.yyyy, l(1, 2, 3, 0)
  ld_indexable(buffer)(float,float,float,float) r3.xyzw, r2.xxxx, t0.xyzw
  ld_indexable(buffer)(float,float,float,float) r4.xyzw, r2.yyyy, t0.xyzw
  ld_indexable(buffer)(float,float,float,float) r2.xy, r2.zzzz, t0.xyzw
  div r0.y, cb0[22].x, r4.z
  add r5.w, r0.y, r1.w
  add_sat r0.y, cb0[149].x, cb0[149].x
  add r0.y, -r0.y, l(1.000000)
  mul r5.xyz, r0.yyyy, r1.xyzx
  mad r3.xyz, r5.xyzx, cb0[145].xxxx, r3.xyzx
  mul r0.y, r3.w, cb0[149].x
  mad r4.x, r0.y, l(6.28318548), r4.x
  store_uav_typed u0.xyzw, r0.xxxx, r5.xyzw
  iadd r0.yzw, r0.xxxx, l(0, 1, 2, 3)
  store_uav_typed u0.xyzw, r0.yyyy, r3.xyzw
  store_uav_typed u0.xyzw, r0.zzzz, r4.xyzw
  mov r2.zw, l(0,0,0,0)
  store_uav_typed u0.xyzw, r0.wwww, r2.xyzw
endif
ret
// Approximately 0 instruction slots used
