//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:53 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[100], immediateIndexed
dcl_constantbuffer cb9[64], dynamicIndexed
dcl_constantbuffer cb10[3], immediateIndexed
dcl_uav_typed_buffer (float,float,float,float) u0
dcl_input vThreadID.x
dcl_temps 10
dcl_thread_group 64, 1, 1
add r0.x, l(0.500000), cb0[89].x
ftou r0.x, r0.x
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  ftou r0.x, cb0[99].x
  add r0.y, l(0.250000), cb10[2].x
  ftoi r0.y, r0.y
  ftoi r0.z, cb0[23].x
  iadd r0.y, r0.z, r0.y
  add r0.z, l(0.250000), cb10[1].x
  lt r0.w, cb0[23].x, cb0[24].x
  and r0.w, r0.w, cb0[23].x
  ftoi r0.zw, r0.zzzw
  iadd r0.z, r0.w, r0.z
  utof r0.w, vThreadID.x
  add r1.z, r0.w, cb0[19].x
  add r0.w, r1.z, cb0[21].x
  ftou r0.w, r0.w
  xor r2.x, r0.w, l(61)
  ushr r0.w, r0.w, l(16)
  xor r0.w, r0.w, r2.x
  imul null, r0.w, r0.w, l(9)
  ushr r2.x, r0.w, l(4)
  xor r0.w, r0.w, r2.x
  imul null, r0.w, r0.w, l(0x27d4eb2d)
  ushr r2.x, r0.w, l(15)
  xor r0.w, r0.w, r2.x
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r2.x, r0.w
  mul r2.x, r2.x, l(2.328306437E-010)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.x, r0.w
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.y, r0.w
  mul r2.yz, r3.xxyx, l(0.000000, 2.328306437E-010, 2.328306437E-010, 0.000000)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.y, r0.w
  mul r2.w, r3.y, l(2.328306437E-010)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.y, r0.w
  mul r4.x, r3.y, l(2.328306437E-010)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.y, r0.w
  mul r4.y, r3.y, l(2.328306437E-010)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.y, r0.w
  mul r4.z, r3.y, l(2.328306437E-010)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.y, r0.w
  mul r4.w, r3.y, l(2.328306437E-010)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.y, r0.w
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.z, r0.w
  mul r5.y, r3.z, l(2.328306437E-010)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.z, r0.w
  mul r5.xz, r3.yyzy, l(2.328306437E-010, 0.000000, 2.328306437E-010, 0.000000)
  mad r1.w, r3.y, l(-1.164153218E-010), l(1.250000)
  mad r3.yzw, r3.xxxx, l(0.000000, 7.504457472E-011, 7.285345105E-010, 1.333304717E-010), l(0.000000, 0.000000, -1.132043, 0.427350)
  ge r6.xyzw, r3.xxxx, l(0.000000, 1732302080.000000, 2619930112.000000, 4294967296.000000)
  and r6.xyzw, r6.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
  add r6.xyz, r6.yzwy, r6.xyzx
  add r6.xyz, r6.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
  mul r6.xyz, r6.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r3.xyz, r3.yzwy, r6.xyzx
  add r3.xy, r3.xyxx, r3.xyxx
  add r3.x, r3.y, r3.x
  mad_sat r3.x, r3.z, l(2.000000), r3.x
  mad r1.x, r3.x, l(6.000000), l(-3.000000)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.x, r0.w
  mad r3.x, r3.x, l(4.656612873E-010), l(-1.000000)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r3.w, r0.w
  mad r3.y, r3.w, l(4.656612873E-010), l(-1.000000)
  imad r0.w, r0.w, l(0x0019660d), l(0x3c6ef35f)
  utof r0.w, r0.w
  mad r3.z, r0.w, l(4.656612873E-010), l(-1.000000)
  dp3 r0.w, r3.xyzx, r3.xyzx
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, r3.xyzx
  max r0.w, l(0.001000), cb0[7].y
  mul r3.xyz, r0.wwww, r3.xyzx
  mul r6.xyz, cb9[r0.z + 0].zxyz, cb9[r0.z + 32].yzxy
  mad r6.xyz, cb9[r0.z + 0].yzxy, cb9[r0.z + 32].zxyz, -r6.xyzx
  dp3 r0.w, cb9[r0.z + 0].xyzx, cb9[r0.z + 32].xyzx
  mov r6.w, -r0.w
  mov r7.xyz, cb9[r0.z + 0].xyzx
  mov r7.w, l(0)
  mad r6.xyzw, cb9[r0.z + 32].wwww, r7.xyzw, r6.xyzw
  mul r7.xyz, r6.yzxy, -cb9[r0.z + 32].zxyz
  mad r7.xyz, -cb9[r0.z + 32].yzxy, r6.zxyz, -r7.xyzx
  mad r6.xyz, cb9[r0.z + 32].wwww, r6.xyzx, r7.xyzx
  mad r6.xyz, r6.wwww, -cb9[r0.z + 32].xyzx, r6.xyzx
  mul r7.xyz, cb9[r0.y + 32].yzxy, -cb9[r0.z + 32].zxyz
  mad r7.xyz, -cb9[r0.z + 32].yzxy, cb9[r0.y + 32].zxyz, -r7.xyzx
  dp3 r0.w, -cb9[r0.z + 32].xyzx, cb9[r0.y + 32].xyzx
  mov r8.w, -r0.w
  mad r8.xyz, cb9[r0.z + 32].wwww, cb9[r0.y + 32].xyzx, r7.xyzx
  mul r7.xyzw, l(-1.000000, -1.000000, -1.000000, 1.000000), cb9[r0.z + 32].xyzw
  mad r7.xyzw, cb9[r0.y + 32].wwww, r7.xyzw, r8.xyzw
  mul r8.xyz, cb9[r0.y + 0].zxyz, cb9[r0.z + 32].yzxy
  mad r8.xyz, cb9[r0.y + 0].yzxy, cb9[r0.z + 32].zxyz, -r8.xyzx
  dp3 r0.w, cb9[r0.y + 0].xyzx, cb9[r0.z + 32].xyzx
  mov r8.w, -r0.w
  mov r9.xyz, cb9[r0.y + 0].xyzx
  mov r9.w, l(0)
  mad r8.xyzw, cb9[r0.z + 32].wwww, r9.xyzw, r8.xyzw
  mul r9.xyz, r8.yzxy, -cb9[r0.z + 32].zxyz
  mad r9.xyz, -cb9[r0.z + 32].yzxy, r8.zxyz, -r9.xyzx
  mad r8.xyz, cb9[r0.z + 32].wwww, r8.xyzx, r9.xyzx
  mad r0.yzw, r8.wwww, -cb9[r0.z + 32].xxyz, r8.xxyz
  add r0.yzw, r0.yyzw, -r6.xxyz
  mul r6.xyz, r3.zxyz, -r7.yzxy
  mad r6.xyz, r3.yzxy, -r7.zxyz, -r6.xyzx
  dp3 r3.w, r3.xyzx, -r7.xyzx
  mov r6.w, -r3.w
  mul r3.xyz, r3.xyzx, r7.wwww
  mov r3.w, l(0)
  add r3.xyzw, r3.xyzw, r6.xyzw
  mul r6.xyz, r3.yzxy, r7.zxyz
  mad r6.xyz, r7.yzxy, r3.zxyz, -r6.xyzx
  mad r3.xyz, r7.wwww, r3.xyzx, r6.xyzx
  mad r3.xyz, r3.wwww, r7.xyzx, r3.xyzx
  add r3.xyz, r0.yzwy, r3.xyzx
  imad r0.x, l(6), vThreadID.x, r0.x
  store_uav_typed u0.xyzw, r0.xxxx, l(0,0,0,0)
  iadd r6.xyzw, r0.xxxx, l(1, 2, 3, 4)
  mov r3.w, l(0)
  store_uav_typed u0.xyzw, r6.xxxx, r3.xyzw
  mov r1.y, l(0)
  store_uav_typed u0.xyzw, r6.yyyy, r1.xyzw
  store_uav_typed u0.xyzw, r6.zzzz, r2.xyzw
  store_uav_typed u0.xyzw, r6.wwww, r4.xyzw
  iadd r0.y, r0.x, l(5)
  mov r5.w, l(0)
  store_uav_typed u0.xyzw, r0.yyyy, r5.xyzw
endif
ret
// Approximately 0 instruction slots used
