//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:52 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[148], immediateIndexed
dcl_resource_buffer (float,float,float,float) t0
dcl_uav_typed_buffer (float,float,float,float) u0
dcl_input vThreadID.x
dcl_temps 4
dcl_thread_group 64, 1, 1
add r0.x, l(0.500000), cb0[89].x
ftou r0.x, r0.x
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  ftou r0.x, cb0[99].x
  ftou r0.y, cb0[90].x
  imad r0.y, l(3), vThreadID.x, r0.y
  ld_indexable(buffer)(float,float,float,float) r1.xyzw, r0.yyyy, t0.xyzw
  iadd r0.yz, r0.yyyy, l(0, 1, 2, 0)
  ld_indexable(buffer)(float,float,float,float) r2.xyzw, r0.yyyy, t0.xyzw
  ld_indexable(buffer)(float,float,float,float) r3.xy, r0.zzzz, t0.xyzw
  add r1.w, r1.w, cb0[22].x
  mad r2.xyz, r1.xyzx, cb0[145].xxxx, r2.xyzx
  mul r0.y, r2.w, cb0[147].x
  mad r3.x, r0.y, l(6.28318548), r3.x
  imad r0.x, l(3), vThreadID.x, r0.x
  store_uav_typed u0.xyzw, r0.xxxx, r1.xyzw
  iadd r0.yz, r0.xxxx, l(0, 1, 2, 0)
  store_uav_typed u0.xyzw, r0.yyyy, r2.xyzw
  mov r3.zw, l(0,0,0,0)
  store_uav_typed u0.xyzw, r0.zzzz, r3.xyzw
endif
ret
// Approximately 0 instruction slots used
