//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:50 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[99], immediateIndexed
dcl_resource_buffer (float,float,float,float) t0
dcl_uav_typed_buffer (float,float,float,float) u0
dcl_input vThreadID.x
dcl_temps 6
dcl_thread_group 64, 1, 1
add r0.x, l(0.500000), cb0[88].x
ftou r0.x, r0.x
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  ftou r0.x, cb0[98].x
  ftou r0.y, cb0[89].x
  imad r0.y, l(3), vThreadID.x, r0.y
  ld_indexable(buffer)(float,float,float,float) r1.xyzw, r0.yyyy, t0.xyzw
  iadd r0.yz, r0.yyyy, l(0, 1, 2, 0)
  ld_indexable(buffer)(float,float,float,float) r2.xyzw, r0.yyyy, t0.xyzw
  ld_indexable(buffer)(float,float,float,float) r3.xyzw, r0.zzzz, t0.wxyz
  mov_sat r0.y, r1.w
  mad r4.xyzw, r0.yyyy, l(0.076790, 0.159721, 3.327408, 59.659363), l(-1.218485, -1.332584, -7.338043, -164.024353)
  mad r5.xyzw, r0.yyyy, l(-0.012658, 0.016020, 3.751949, 149.070679), l(1.000000, 0.998738, 0.233645, -44.705643)
  mul r0.z, r0.y, r0.y
  mad r4.xyzw, r4.xyzw, r0.zzzz, r5.xyzw
  ge r5.xyzw, r0.yyyy, l(0.000000, 0.255556, 0.561111, 0.927778)
  and r5.xyzw, r5.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
  add r0.yzw, r5.yyzw, r5.xxyz
  add r0.yzw, r0.yyzw, l(0.000000, 0.000001, 0.000001, 0.000001)
  mul r0.yzw, r0.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)
  frc r0.yzw, r0.yyzw
  mul r0.yzw, r4.xxyz, r0.yyzw
  mov r4.x, l(2.000000)
  mul r0.yz, r0.yyzy, r4.xxxx
  add r0.y, r0.z, r0.y
  mad r0.y, r4.x, r0.w, r0.y
  mad_sat r4.z, r4.w, r5.w, r0.y
  ishl r0.y, vThreadID.x, l(2)
  iadd r0.x, r0.y, r0.x
  store_uav_typed u0.xyzw, r0.xxxx, r1.xyzw
  iadd r0.yzw, r0.xxxx, l(0, 1, 2, 3)
  store_uav_typed u0.xyzw, r0.yyyy, r2.xyzw
  mov r4.xyw, r3.yzyw
  store_uav_typed u0.xyzw, r0.zzzz, r4.xyzw
  mov r3.yzw, l(0,0,0,0)
  store_uav_typed u0.xyzw, r0.wwww, r3.xyzw
endif
ret
// Approximately 0 instruction slots used
