//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:10 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float
// TEXCOORD                 2   xyz         2     NONE   float
// TEXCOORD                 3   xyzw        3     NONE   float   xy
// TEXCOORD                 4   xyz         4     NONE   float
// SV_POSITION              0   xyzw        5      POS   float
// SV_isFrontFace           0   x           6    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[57], immediateIndexed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v3.xy
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_temps 3
add r0.xy, v3.xyxx, -cb0[6].xyxx
dp2 r0.x, r0.xyxx, r0.xyxx
sqrt r0.x, r0.x
mad_sat r0.x, r0.x, cb0[8].x, cb0[8].y
add r0.yzw, -cb0[0].xxyz, cb0[1].xxyz
mad r0.xyz, r0.xxxx, r0.yzwy, cb0[0].xyzx
mad r1.xy, v3.xyxx, cb0[9].xyxx, cb0[9].zwzz
sample_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t4.xyzw, s1
mad r2.xy, v3.xyxx, cb0[10].xyxx, cb0[10].zwzz
sample_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t4.xyzw, s1
mul r1.xyz, r1.xyzx, r2.xyzx
mad_sat r1.xyz, r1.xyzx, cb0[11].xxxx, cb0[11].yyyy
add r0.xyz, r0.xyzx, r1.xyzx
add r1.xy, v3.xyxx, -cb0[18].xyxx
dp2 r0.w, r1.xyxx, r1.xyxx
sqrt r0.w, r0.w
mad_sat r0.w, r0.w, cb0[20].x, cb0[20].y
add r1.xyz, -cb0[12].xyzx, cb0[13].xyzx
mad r1.xyz, r0.wwww, r1.xyzx, cb0[12].xyzx
mul r0.xyz, r0.xyzx, r1.xyzx
mad r1.xyz, r0.xyzx, cb0[21].xyzx, cb0[53].xyzx
mul r0.xyz, r0.xyzx, cb0[21].xyzx
max r0.w, r1.z, r1.y
max r0.w, r0.w, r1.x
add_sat r0.w, r0.w, l(-1.000000)
add r0.w, -r0.w, l(1.000000)
mad r0.xyz, r0.xyzx, r0.wwww, cb0[53].xyzx
max r0.w, r0.z, r0.y
max r0.w, r0.w, r0.x
max r0.w, r0.w, l(1.000000)
div o0.xyz, r0.xyzx, r0.wwww
mov o0.w, l(0)
dp3 r0.x, v0.xyzx, v0.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, v0.xyzx
mov_sat r0.w, cb0[56].x
mad r0.w, r0.w, l(0.125000), l(0.375000)
mad_sat o1.xyz, r0.xyzx, r0.wwww, l(0.500000, 0.500000, 0.500000, 0.000000)
mov o1.w, l(0)
max r0.x, cb0[53].z, cb0[53].y
max r0.x, r0.x, cb0[53].x
mad r0.x, r0.x, cb0[55].x, l(0.00781250000)
log r0.x, r0.x
mad_sat r0.x, r0.x, l(0.0769230798), l(0.538461566)
add r0.x, r0.x, l(1.000000)
mul o2.y, r0.x, l(0.500000)
mov_sat r0.x, cb0[54].x
add o2.w, r0.x, v0.w
mov o2.x, cb0[56].x
mov o2.z, l(0)
ret
// Approximately 0 instruction slots used
