//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:05 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float
// TEXCOORD                 0   xy          1     NONE   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[16], immediateIndexed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 3
sample_indexable(texture2d)(float,float,float,float) r0.x, v1.xyxx, t4.xyzw, s1
mul r0.xyz, r0.xxxx, cb0[14].xyzx
mul r0.xyz, r0.xyzx, cb0[15].xxxx
dp3 r1.w, r0.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
mul r2.x, r1.w, r1.w
mul r2.y, r1.w, cb0[3].y
mad r2.x, r2.x, cb0[3].x, r2.y
add r2.x, r2.x, cb0[3].z
mul r1.xyz, r0.xyzx, r2.xxxx
lt r2.x, l(0.000000), cb0[3].w
mov r0.w, l(0)
movc o0.xyzw, r2.xxxx, r1.xyzw, r0.xyzw
ret
// Approximately 0 instruction slots used
