//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:55 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float
// TEXCOORD                 4      w        1     NONE   float      w
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   x zw
// SV_POSITION              0   xyzw        4      POS   float   xy
// SV_isFrontFace           0   x           5    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[117], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[13], immediateIndexed
dcl_constantbuffer cb2[1], immediateIndexed
dcl_constantbuffer cb8[8], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.w
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xzw
dcl_input_ps_siv linear noperspective v4.xy, position
dcl_output o0.xyzw
dcl_temps 3
mul r0.xyzw, v0.xyxy, l(0.200000, 0.200000, 0.200000, 1.000000)
sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t0.xyzw, s1
sample_indexable(texture2d)(float,float,float,float) r0.y, r0.zwzz, t1.yxzw, s1
mul r0.x, r0.y, r0.x
mad r0.x, r0.x, v3.w, v3.z
add r0.y, v3.x, l(-0.500000)
mul_sat r0.y, r0.y, l(0.500000)
mul_sat r0.x, r0.y, r0.x
mul_sat r0.x, r0.x, v0.z
mov r1.zw, l(0,0,0,0)
mul r2.xy, v4.xyxx, cb12[12].zwzz
mul r0.yz, r2.xxyx, cb12[12].xxyx
ftoi r1.xy, r0.yzyy
ld_indexable(texture2d)(float,float,float,float) r0.y, r1.xyzw, t10.yxzw
mad r0.y, r0.y, cb2[0].y, cb2[0].x
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
add r0.y, r0.y, -v0.w
mul_sat r0.y, r0.y, l(20.000000)
add r0.y, -r0.y, l(1.000000)
add r0.y, -r0.y, l(1.000000)
mad r0.x, r0.x, r0.y, -cb0[107].x
lt r0.x, r0.x, l(0.000000)
discard_nz r0.x
dp3 r0.x, -v2.xyzx, -v2.xyzx
sqrt r0.x, r0.x
mul r0.y, r0.x, l(0.015625)
mad_sat r0.x, r0.x, cb0[116].x, cb0[116].y
min r0.y, r0.y, l(1.000000)
sqrt r2.z, r0.y
sample_l_indexable(texture3d)(float,float,float,float) r0.y, r2.xyzx, t21.yxzw, s3, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, r2.xyxx, t20.xyzw, s3, l(0.000000)
add r1.xyzw, r1.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
mad r1.xyzw, r0.yyyy, r1.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
mul r0.yzw, v1.wwww, cb0[11].xxyz
mul r0.yzw, r0.yyzw, cb13[1].wwww
mul r0.yzw, r0.yyzw, cb13[1].xxxx
mul r0.yzw, r0.yyzw, cb8[7].xxyz
mad r0.yzw, r0.yyzw, r1.wwww, r1.xxyz
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, r2.xyxx, t11.xyzw, s2
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyxx, t13.xyzw, s2
add r1.xyzw, r1.xyzw, -r2.xyzw
mad r1.xyzw, r0.xxxx, r1.xyzw, r2.xyzw
mul r1.xyz, r1.xyzx, cb8[5].xyzx
mad r1.xyz, r1.wwww, cb8[6].xyzx, r1.xyzx
mad o0.xyz, r1.xyzx, cb13[1].xxxx, r0.yzwy
mov o0.w, l(1.000000)
ret
// Approximately 0 instruction slots used
