//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:58 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float   xyz
// TEXCOORD                 2   xyzw        2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// SV_POSITION              0   xyzw        5      POS   float
// SV_isFrontFace           0   x           6    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[25], immediateIndexed
dcl_constantbuffer cb12[8], immediateIndexed
dcl_constantbuffer cb7[63], dynamicIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyz
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_temps 14
add r0.xyz, -v4.xyzx, cb12[7].xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r1.x, r0.w
mul r0.xyz, r0.xyzx, r1.xxxx
sqrt r0.w, r0.w
dp3 r1.x, r0.xyzx, v0.xyzx
dp3 r2.x, r0.xyzx, v1.xyzx
dp3 r2.y, r0.xyzx, v2.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.xyz, v3.xyxx, t3.xyzw, s6
add r1.y, -r0.z, r0.y
lt r1.y, r1.y, l(0.00470588217)
movc r0.z, r1.y, r0.y, r0.z
deriv_rtx_coarse r3.xyz, r0.xyzx
deriv_rty_coarse r4.xyz, r0.xyzx
mul r1.yz, r3.yyzy, r3.xxxx
mul r2.zw, r4.yyyz, r4.xxxx
lt r3.xy, |r2.zwzz|, |r1.yzyy|
movc r1.yz, r3.xxyx, r1.yyzy, r2.zzwz
add r1.w, r0.x, l(-0.500000)
lt r1.w, |r1.w|, l(0.00470588217)
add r2.z, r0.y, r0.x
add r2.z, r2.z, l(-1.000000)
lt r2.z, |r2.z|, l(0.00588235306)
lt r1.yz, r1.yyzy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r1.y, r1.y, r2.z
add r2.z, -r0.y, l(1.000000)
movc r1.y, r1.y, r2.z, r0.x
add r2.z, r0.z, r1.y
add r2.z, r2.z, l(-1.000000)
lt r2.z, |r2.z|, l(0.00588235306)
and r1.z, r1.z, r2.z
add r2.z, -r0.z, l(1.000000)
movc r1.y, r1.z, r2.z, r1.y
movc r0.x, r1.w, r1.y, r0.x
ge r0.xz, r0.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
if_nz r0.z
  mad r1.yz, v3.zzwz, cb7[6].xxyx, cb7[6].zzwz
  mad r2.zw, v3.zzzw, cb7[7].xxxy, cb7[7].zzzw
  sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.yzyy, t8.wxyz, s1
  sample_indexable(texture2d)(float,float,float,float) r1.yzw, r2.zwzz, t9.wxyz, s1
  mad r1.yz, r1.yyzy, cb7[8].xxxx, cb7[8].yyyy
  add_sat r0.z, r1.w, cb7[8].z
  mov r1.w, l(4)
else
  ge r0.y, r0.y, l(0.500000)
  if_nz r0.y
    mad r2.zw, v3.zzzw, cb7[3].xxxy, cb7[3].zzzw
    mad r4.xy, v3.zwzz, cb7[4].xyxx, cb7[4].zwzz
    sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.zwzz, t6.wxyz, s1
    sample_indexable(texture2d)(float,float,float,float) r4.xyz, r4.xyxx, t7.xyzw, s1
    mad r1.yz, r4.xxyx, cb7[5].xxxx, cb7[5].yyyy
    add_sat r0.z, r4.z, cb7[5].z
    mov r1.w, l(2)
  else
    mad r2.zw, v3.zzzw, cb7[0].xxxy, cb7[0].zzzw
    mad r4.xy, v3.zwzz, cb7[1].xyxx, cb7[1].zwzz
    sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.zwzz, t4.wxyz, s1
    sample_indexable(texture2d)(float,float,float,float) r4.xyz, r4.xyxx, t5.xyzw, s1
    mad r1.yz, r4.xxyx, cb7[2].xxxx, cb7[2].yyyy
    add_sat r0.z, r4.z, cb7[2].z
    mov r1.w, l(0)
  endif
endif
iadd r0.y, r1.w, l(1)
movc r0.x, r0.x, r0.y, r1.w
imul null, r0.x, r0.x, l(9)
mov_sat r4.xyzw, cb7[r0.x + 11].xyzw
mov_sat r2.zw, cb7[r0.x + 12].yyyz
mov_sat r5.xyzw, cb7[r0.x + 17].xyzw
sample_indexable(texture2d)(float,float,float,float) r6.xyz, v3.xyxx, t0.xyzw, s3
sample_indexable(texture2d)(float,float,float,float) r7.xy, v3.xyxx, t1.xyzw, s4
mad r7.xy, r7.xyxx, cb0[24].xxxx, cb0[24].yyyy
sample_indexable(texture2d)(float,float,float,float) r8.xyzw, v3.xyxx, t2.xyzw, s5
ge r0.y, r8.w, l(0.156862751)
and r1.w, r0.y, l(0x3f800000)
add r9.xyz, r8.ywzy, l(-0.250000, -0.188235298, -0.156862751, 0.000000)
mul_sat r7.zw, r9.yyyz, l(0.000000, 0.000000, 1.231884, 1.18604648)
mad_sat r6.w, cb7[r0.x + 15].y, r7.z, cb7[r0.x + 15].x
mad_sat r6.w, cb7[r0.x + 15].w, r6.w, cb7[r0.x + 15].z
mul_sat r10.xy, r8.wyww, l(7.968750, 4.000000, 0.000000, 0.000000)
add r7.z, l(128.500000), cb0[2].x
mul r7.z, r7.z, l(0.00390625000)
ge r8.z, l(0.050000), r10.x
movc r7.z, r8.z, r7.z, l(-1.000000)
mul_sat r9.yzw, r3.yyzw, l(0.000000, 4.000000, 4.000000, 4.000000)
add_sat r3.yzw, r3.yyzw, l(0.000000, -0.250000, -0.250000, -0.250000)
mad_sat r11.xyz, cb7[r0.x + 9].xyzx, r9.yzwy, r3.yzwy
add r11.xyz, r11.xyzx, -cb7[r0.x + 9].xyzx
mad r11.xyz, r4.xxxx, r11.xyzx, cb7[r0.x + 9].xyzx
mad_sat r4.x, cb7[r0.x + 13].y, r8.y, cb7[r0.x + 13].x
mad_sat r4.x, cb7[r0.x + 13].w, r4.x, cb7[r0.x + 13].z
mov_sat r9.x, r9.x
mad_sat r3.x, r3.x, r10.y, r9.x
mad_sat r8.z, cb7[r0.x + 13].y, r3.x, cb7[r0.x + 13].x
mad_sat r8.z, cb7[r0.x + 13].w, r8.z, cb7[r0.x + 13].z
add r8.z, -r4.x, r8.z
mad r4.x, r4.z, r8.z, r4.x
mul_sat r12.xyz, r6.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r13.xyz, r6.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad_sat r11.xyz, r11.xyzx, r12.xyzx, r13.xyzx
mad r8.zw, r1.yyyz, r4.yyyy, r7.xxxy
add r0.z, r0.z, l(-1.000000)
mad r4.y, r4.y, r0.z, l(1.000000)
mad_sat r3.yzw, cb7[r0.x + 14].xxyz, r9.yyzw, r3.yyzw
add r3.yzw, r3.yyzw, -cb7[r0.x + 14].xxyz
mad r3.yzw, r5.xxxx, r3.yyzw, cb7[r0.x + 14].xxyz
mad_sat r3.yzw, r3.yyzw, r12.xxyz, r13.xxyz
mad_sat r4.z, cb7[r0.x + 16].y, r8.y, cb7[r0.x + 16].x
mad_sat r4.z, cb7[r0.x + 16].w, r4.z, cb7[r0.x + 16].z
mad_sat r3.x, cb7[r0.x + 16].y, r3.x, cb7[r0.x + 16].x
mad_sat r3.x, cb7[r0.x + 16].w, r3.x, cb7[r0.x + 16].z
add r3.x, -r4.z, r3.x
mad r3.x, r5.z, r3.x, r4.z
mad r1.yz, r1.yyzy, r5.yyyy, r7.xxyx
mad r0.z, r5.y, r0.z, l(1.000000)
add r5.xyz, -r3.yzwy, r11.xyzx
mad r3.yzw, r6.wwww, r5.xxyz, r3.yyzw
add r5.xy, -r1.yzyy, r8.zwzz
mad r1.yz, r6.wwww, r5.xxyx, r1.yyzy
add r4.x, -r3.x, r4.x
mad r3.x, r6.w, r4.x, r3.x
add r4.x, r4.w, -r5.w
mad r5.y, r6.w, r4.x, r5.w
add r4.x, -r0.z, r4.y
mad r0.z, r6.w, r4.x, r0.z
add r0.x, l(128.500000), cb7[r0.x + 12].x
mul r0.x, r0.x, l(0.00390625000)
ge r4.x, l(0.050000), r4.w
movc r0.x, r4.x, r0.x, l(-1.000000)
min r0.z, r0.z, r3.x
lt r3.x, l(0.000100), r2.z
mul r4.x, r2.z, l(-2.000000)
mad r2.z, r2.z, l(-2.000000), l(-0.200000)
mul r2.z, r0.z, r2.z
mad r2.z, r2.z, l(-5.002501), r4.x
min r2.z, r0.z, r2.z
movc r5.x, r3.x, r2.z, r0.z
add r3.xyz, -r6.xyzx, r3.yzwy
mad r3.xyz, r1.wwww, r3.xyzx, r6.xyzx
add r1.yz, -r7.xxyx, r1.yyzy
mad r4.xy, r1.wwww, r1.yzyy, r7.xyxx
mov r10.z, r8.y
add r1.yz, -r10.zzxz, r5.xxyx
mad r1.yz, r1.wwww, r1.yyzy, r10.zzxz
mul r0.z, r2.w, r1.w
movc o0.w, r0.y, r0.x, r7.z
mul r0.xy, r2.xyxx, cb0[14].xxxx
div r0.xy, r0.xyxx, r1.xxxx
add r0.xy, -r0.xyxx, v3.xyxx
mul r1.x, r1.x, r1.x
mad_sat r1.w, r1.x, cb0[15].x, cb0[15].y
mad r1.w, cb0[17].x, r1.w, cb0[16].x
mad r2.xy, r0.xyxx, cb0[18].xyxx, cb0[18].zwzz
mad r0.xy, r0.xyxx, cb0[19].xyxx, cb0[19].zwzz
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t10.xyzw, s2
add r0.xy, r0.xyxx, -cb0[21].xyxx
mad r0.xy, r0.xyxx, cb0[20].xxxx, r2.xyxx
sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t11.xyzw, s2
mad_sat r0.x, cb0[22].y, r0.x, cb0[22].x
mul r0.x, r0.x, r1.w
mad_sat r0.y, r1.x, cb0[23].x, cb0[23].y
mul r0.x, r0.y, r0.x
mul r0.x, r0.x, r7.w
mul r0.y, r0.x, cb0[4].x
mad r2.xyz, r0.xxxx, cb0[4].xxxx, r3.xyzx
max r0.x, r2.y, r2.x
max r0.x, r2.z, r0.x
add_sat r0.x, r0.x, l(-1.000000)
add r0.x, -r0.x, l(1.000000)
mad r2.xyz, r3.xyzx, r0.xxxx, r0.yyyy
max r0.x, r2.y, r2.x
max r0.x, r2.z, r0.x
max r0.x, r0.x, l(1.000000)
div r2.xyz, r2.xyzx, r0.xxxx
max r0.x, r0.y, r0.y
max r0.x, r0.y, r0.x
dp2 r0.y, r4.xyxx, r4.xyxx
add r0.y, -r0.y, l(1.000000)
max r0.y, r0.y, l(0.000000)
sqrt r4.z, r0.y
dp3 r0.y, r4.xyzx, r4.xyzx
rsq r0.y, r0.y
mul r3.xyz, r0.yyyy, r4.xyzx
mul r4.xyz, r3.yyyy, v2.xyzx
mad r3.xyw, v1.xyxz, r3.xxxx, r4.xyxz
mad r3.xyz, v0.xyzx, r3.zzzz, r3.xywx
dp3 r0.y, r3.xyzx, r3.xyzx
rsq r0.y, r0.y
mul r3.xyz, r0.yyyy, r3.xyzx
mov_sat r0.y, cb0[12].x
dp3 r1.x, v0.xyzx, v0.xyzx
rsq r1.x, r1.x
mul r4.xyz, r1.xxxx, v0.xyzx
dp3 r1.x, cb0[5].xyzx, r4.xyzx
add r1.w, -cb0[3].x, cb0[4].x
mad_sat r1.x, r1.x, r1.w, cb0[3].x
add r1.w, v4.z, -cb0[6].z
mul r1.w, r1.w, cb0[7].x
max r1.w, r1.w, l(0.000000)
log r1.w, r1.w
mul r1.w, r1.w, cb0[8].x
exp r1.w, r1.w
mul_sat r1.w, r1.w, cb0[9].x
mul r1.x, r1.w, r1.x
mad_sat r0.w, r0.w, cb0[10].x, cb0[10].y
mul r0.w, r0.w, r1.x
dp3 r1.x, r2.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
max r1.x, r1.x, l(0.000100)
log r1.x, r1.x
mul r1.x, r1.x, -cb0[11].x
exp r1.x, r1.x
mul r0.w, r0.w, r1.x
add o2.w, r0.y, v0.w
mad r0.x, r0.w, cb0[13].x, r0.x
mad r0.y, r1.y, l(0.125000), l(0.375000)
mad_sat o1.xyz, r3.xyzx, r0.yyyy, l(0.500000, 0.500000, 0.500000, 0.000000)
add r0.x, r0.x, l(0.00781250000)
log r0.x, r0.x
mad_sat r0.x, r0.x, l(0.0769230798), l(0.538461566)
mov_sat r8.x, r8.x
add r0.x, r0.x, r8.x
mul o2.yz, r0.xxzx, l(0.000000, 0.500000, 0.800000, 0.000000)
mov o0.xyz, r2.xyzx
mov o1.w, l(0)
mov o2.x, r1.z
ret
// Approximately 0 instruction slots used
