//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:50 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyz
// TEXCOORD                 1   xyz         1     NONE   float
// TEXCOORD                 4      w        1     NONE   float      w
// TEXCOORD                 2   xyz         2     NONE   float
// TEXCOORD                 3   xyzw        3     NONE   float   xyz
// SV_POSITION              0   xyzw        4      POS   float
// SV_isFrontFace           0   x           5    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[121], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb8[8], immediateIndexed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v0.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v3.xyz
dcl_output o0.xyzw
dcl_temps 1
sample_indexable(texture2d)(float,float,float,float) r0.xy, v0.xyxx, t0.xwyz, s1
log r0.xy, r0.xyxx
mul r0.xy, r0.xyxx, l(2.200000, 2.200000, 0.000000, 0.000000)
exp r0.xy, r0.xyxx
add r0.x, r0.x, l(-2.511886521E-007)
mul_sat r0.y, r0.y, cb0[120].x
mul_sat r0.y, r0.y, v0.z
mul r0.x, r0.x, l(1.00000024)
max r0.x, r0.x, l(0.000000)
mul r0.xzw, r0.xxxx, v3.xxyz
mul r0.xzw, r0.xxzw, v1.wwww
mul r0.xzw, r0.xxzw, cb13[1].wwww
mul r0.xzw, r0.xxzw, cb13[1].xxxx
mul r0.xzw, r0.xxzw, cb8[7].xxyz
mul o0.xyz, r0.yyyy, r0.xzwx
mov o0.w, l(0)
ret
// Approximately 0 instruction slots used
