//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:00 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float   xyz
// TEXCOORD                 2   xyzw        2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// SV_POSITION              0   xyzw        5      POS   float   xy
// SV_isFrontFace           0   x           6    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[36], immediateIndexed
dcl_constantbuffer cb13[5], immediateIndexed
dcl_constantbuffer cb12[15], immediateIndexed
dcl_constantbuffer cb3[16], immediateIndexed
dcl_constantbuffer cb8[36], immediateIndexed
dcl_constantbuffer cb7[63], dynamicIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texturecube (float,float,float,float) t24
dcl_resource_texturecube (float,float,float,float) t25
dcl_resource_texture2d (float,float,float,float) t26
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyz
dcl_input_ps_siv linear noperspective v5.xy, position
dcl_output o0.xyzw
dcl_temps 19
mul r0.xy, v5.xyxx, cb12[12].zwzz
add r1.xyz, -v4.xyzx, cb12[14].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r1.xyzx
add r3.xyz, v4.xyzx, -cb12[14].xyzx
dp3 r1.w, -cb12[6].xyzx, r3.xyzx
mul r2.w, v0.w, v0.w
sample_indexable(texture2d)(float,float,float,float) r3.xyz, v3.xyxx, t3.xyzw, s5
add r3.w, -r3.z, r3.y
lt r3.w, r3.w, l(0.00470588217)
movc r3.z, r3.w, r3.y, r3.z
deriv_rtx_coarse r4.xyz, r3.xyzx
deriv_rty_coarse r5.xyz, r3.xyzx
mul r4.xy, r4.yzyy, r4.xxxx
mul r4.zw, r5.yyyz, r5.xxxx
lt r5.xy, |r4.zwzz|, |r4.xyxx|
movc r4.xy, r5.xyxx, r4.xyxx, r4.zwzz
add r3.w, r3.x, l(-0.500000)
lt r3.w, |r3.w|, l(0.00470588217)
add r4.z, r3.y, r3.x
add r4.z, r4.z, l(-1.000000)
lt r4.z, |r4.z|, l(0.00588235306)
lt r4.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r4.x, r4.x, r4.z
add r4.z, -r3.y, l(1.000000)
movc r4.x, r4.x, r4.z, r3.x
add r4.z, r3.z, r4.x
add r4.z, r4.z, l(-1.000000)
lt r4.z, |r4.z|, l(0.00588235306)
and r4.y, r4.y, r4.z
add r4.z, -r3.z, l(1.000000)
movc r4.x, r4.y, r4.z, r4.x
movc r3.x, r3.w, r4.x, r3.x
ge r3.z, r3.z, l(0.500000)
if_nz r3.z
  mad r3.zw, v3.zzzw, cb7[7].xxxy, cb7[7].zzzw
  sample_indexable(texture2d)(float,float,float,float) r3.z, r3.zwzz, t9.xyzw, s1
  add_sat r3.z, r3.z, cb7[8].z
  mov r3.w, l(4)
else
  ge r3.y, r3.y, l(0.500000)
  if_nz r3.y
    mad r4.xy, v3.zwzz, cb7[4].xyxx, cb7[4].zwzz
    sample_indexable(texture2d)(float,float,float,float) r3.y, r4.xyxx, t7.xzyw, s1
    add_sat r3.z, r3.y, cb7[5].z
    mov r3.w, l(2)
  else
    mad r4.xy, v3.zwzz, cb7[1].xyxx, cb7[1].zwzz
    sample_indexable(texture2d)(float,float,float,float) r3.y, r4.xyxx, t5.xzyw, s1
    add_sat r3.z, r3.y, cb7[2].z
    mov r3.w, l(0)
  endif
endif
ge r3.x, r3.x, l(0.500000)
iadd r3.y, r3.w, l(1)
movc r3.x, r3.x, r3.y, r3.w
imul null, r3.x, r3.x, l(9)
mov_sat r3.yw, cb7[r3.x + 11].yyyw
mov_sat r4.xy, cb7[r3.x + 12].yzyy
mov_sat r4.z, cb7[r3.x + 17].w
sample_indexable(texture2d)(float,float,float,float) r5.xyz, v3.xyxx, t0.xyzw, s2
sample_indexable(texture2d)(float,float,float,float) r6.xy, v3.xyxx, t1.xyzw, s3
mad r6.xy, r6.xyxx, cb0[6].xxxx, cb0[6].yyyy
sample_indexable(texture2d)(float,float,float,float) r7.yzw, v3.xyxx, t2.xzyw, s4
ge r4.w, r7.w, l(0.156862751)
and r4.w, r4.w, l(0x3f800000)
add r5.w, r7.w, l(-0.188235298)
mul_sat r5.w, r5.w, l(1.231884)
mad_sat r5.w, cb7[r3.x + 15].y, r5.w, cb7[r3.x + 15].x
mad_sat r5.w, cb7[r3.x + 15].w, r5.w, cb7[r3.x + 15].z
mul_sat r7.xy, r7.wyww, l(7.968750, 7.968750, 0.000000, 0.000000)
mad_sat r6.z, cb7[r3.x + 13].y, r7.z, cb7[r3.x + 13].x
mad_sat r6.z, cb7[r3.x + 13].w, r6.z, cb7[r3.x + 13].z
mul_sat r8.xyz, r5.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r9.xyz, r5.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad_sat r10.xyz, cb7[r3.x + 9].xyzx, r8.xyzx, r9.xyzx
add r3.z, r3.z, l(-1.000000)
mul r3.y, r3.z, r3.y
mad_sat r8.xyz, cb7[r3.x + 14].xyzx, r8.xyzx, r9.xyzx
add r9.xyz, -r8.xyzx, r10.xyzx
mad r8.xyz, r5.wwww, r9.xyzx, r8.xyzx
add r3.z, -r7.z, r6.z
mad r8.w, r5.w, r3.z, r7.z
add r3.z, r3.w, -r4.z
mad r9.z, r5.w, r3.z, r4.z
mad r3.y, r5.w, r3.y, l(1.000000)
add r10.xyzw, -cb0[4].xyzw, cb0[5].xyzw
mad r10.xyzw, r7.yyyy, r10.xyzw, cb0[4].xyzw
mul_sat r11.xyzw, r10.xyzw, l(4.000000, 4.000000, 4.000000, 4.000000)
add_sat r10.xyzw, r10.xyzw, l(-0.250000, -0.250000, -0.250000, -0.250000)
mad r8.xyzw, r8.xyzw, r11.xyzw, r10.xyzw
min r3.y, r3.y, r8.w
lt r3.z, l(0.000100), r4.x
mul r3.w, r4.x, l(-2.000000)
mad r4.x, r4.x, l(-2.000000), l(-0.200000)
mul r4.x, r3.y, r4.x
mad r3.w, r4.x, l(-5.002501), r3.w
min r3.w, r3.w, r3.y
movc r9.xyw, r3.zzzz, r3.wwww, r3.yyyy
add r3.yzw, -r5.xxyz, r8.xxyz
mad r3.yzw, r4.wwww, r3.yyzw, r5.xxyz
mad r4.xz, r5.wwww, r6.xxyx, -r6.xxyx
mad r6.xy, r4.wwww, r4.xzxx, r6.xyxx
add r8.xyzw, -r7.zzxz, r9.xyzw
mad r8.xyzw, r4.wwww, r8.wxyz, r7.zzzx
mul r4.x, r4.y, r4.w
dp2 r4.y, r6.xyxx, r6.xyxx
add r4.y, -r4.y, l(1.000000)
max r4.y, r4.y, l(0.000000)
sqrt r6.z, r4.y
dp3 r4.y, r6.xyzx, r6.xyzx
rsq r4.y, r4.y
mul r6.xyz, r4.yyyy, r6.xyzx
mul r7.xzw, r6.yyyy, v2.xxyz
mad r6.xyw, v1.xyxz, r6.xxxx, r7.xzxw
mad r6.xyz, v0.xyzx, r6.zzzz, r6.xywx
dp3 r4.y, r6.xyzx, r6.xyzx
rsq r4.y, r4.y
mul r9.xyz, r4.yyyy, r6.xyzx
dp3 r4.z, r2.xyzx, r9.xyzx
mul r5.w, r4.z, r4.z
mad_sat r5.w, r5.w, cb0[8].x, cb0[8].y
mul r5.w, r5.w, r5.w
mad r5.w, cb0[9].y, r5.w, cb0[9].x
add_sat r5.w, r7.y, r5.w
mul_sat r7.xyz, r3.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r3.yzw, r3.yyzw, l(0.000000, -0.250000, -0.250000, -0.250000)
mad r3.xyz, cb7[r3.x + 9].xyzx, r7.xyzx, r3.yzwy
add r3.xyz, -r5.xyzx, r3.xyzx
mad r3.xyz, r4.wwww, r3.xyzx, r5.xyzx
add r5.xy, -r8.wxww, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r7.xyz, r3.xyzx, r5.xxxx
mul r3.xyz, r8.wwww, r3.xyzx
mad r3.xyz, r5.xxxx, l(0.040000, 0.040000, 0.040000, 0.000000), r3.xyzx
max r3.w, r2.w, l(0.000100)
log r3.w, r3.w
mul r3.w, r3.w, cb0[35].x
exp r3.w, r3.w
mul r3.w, r3.w, r3.w
mul r2.w, r2.w, r2.w
add r10.xyz, v4.xyzx, -cb3[0].xyzx
div r10.xyz, |r10.xyzx|, cb3[6].xyzx
add r11.xyz, l(-2.000000, -2.000000, -2.000000, 0.000000), cb3[3].xyzx
div r10.xyz, r10.xyzx, r11.xyzx
max r4.w, r10.y, r10.x
max r4.w, r10.z, r4.w
max r4.w, r4.w, l(0.510000)
log r4.w, r4.w
round_ni r4.w, r4.w
add r10.z, r4.w, l(1.000000)
lt r4.w, r10.z, cb3[8].x
exp r5.x, r10.z
mul r11.xyz, r5.xxxx, cb3[6].xyzx
div r12.xyz, cb3[0].xyzx, r11.xyzx
round_ni r12.xyz, r12.xyzx
mad r11.xyz, -r12.xyzx, r11.xyzx, v4.xyzx
div r11.xyz, r11.xyzx, cb3[6].xyzx
div r11.xyz, r11.xyzx, cb3[3].xyzx
div r11.xyz, r11.xyzx, r5.xxxx
mov r10.xy, l(0.500000,0.500000,0,0)
mad r10.xyz, r11.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r10.xyzx
add r5.x, r10.z, l(0.500000)
mul r10.xy, r10.xyxx, cb3[2].xyxx
mad r10.w, r5.x, cb3[2].z, cb3[9].x
add r10.xyz, r10.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
div r10.xyz, r10.xyzx, cb3[4].xyzx
mov r11.xy, cb8[4].zwzz
mov r11.z, l(0)
movc r10.xyz, r4.wwww, r10.xyzx, r11.xyzx
sample_l_indexable(texture3d)(float,float,float,float) r12.xyzw, r10.xyzx, t16.xyzw, s9, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r13.xyzw, r10.xyzx, t17.xyzw, s9, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r14.xyzw, r10.xyzx, t18.xyzw, s9, l(0.000000)
mul r1.w, r1.w, cb3[15].x
mad_sat r1.w, r1.w, l(1.500000), cb3[15].y
lt r4.w, r1.w, l(1.000000)
if_nz r4.w
  sample_l_indexable(texture3d)(float,float,float,float) r15.xyzw, r11.xyzx, t16.xyzw, s9, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r16.xyzw, r11.xyzx, t17.xyzw, s9, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r11.xyzw, r11.xyzx, t18.xyzw, s9, l(0.000000)
  add r17.xyzw, r12.xyzw, -r15.xyzw
  mad r12.xyzw, r1.wwww, r17.xyzw, r15.xyzw
  add r15.xyzw, r13.xyzw, -r16.xyzw
  mad r13.xyzw, r1.wwww, r15.xyzw, r16.xyzw
  add r15.xyzw, -r11.xyzw, r14.xyzw
  mad r14.xyzw, r1.wwww, r15.xyzw, r11.xyzw
endif
mov r9.w, l(1.000000)
dp4 r11.x, r12.xyzw, r9.xyzw
dp4 r11.y, r13.xyzw, r9.xyzw
dp4 r11.z, r14.xyzw, r9.xyzw
max r11.xyz, r11.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
dp3 r4.w, r12.xyzx, r12.xyzx
rsq r4.w, r4.w
mul r15.xyz, r4.wwww, r12.xyzx
dp3 r4.w, r13.xyzx, r13.xyzx
rsq r4.w, r4.w
mul r16.xyz, r4.wwww, r13.xyzx
dp3 r4.w, r14.xyzx, r14.xyzx
rsq r4.w, r4.w
mul r17.xyz, r4.wwww, r14.xyzx
mul r16.xyz, r16.xyzx, l(0.590000, 0.590000, 0.590000, 0.000000)
mad r15.xyz, r15.xyzx, l(0.300000, 0.300000, 0.300000, 0.000000), r16.xyzx
mad r15.xyz, r17.xyzx, l(0.110000, 0.110000, 0.110000, 0.000000), r15.xyzx
dp3 r4.w, r15.xyzx, r15.xyzx
rsq r4.w, r4.w
mul r15.xyz, r4.wwww, r15.xyzx
mov r15.w, l(1.000000)
dp4 r16.x, r12.xyzw, r15.xyzw
dp4 r16.y, r13.xyzw, r15.xyzw
dp4 r16.z, r14.xyzw, r15.xyzw
max r16.xyz, r16.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
dp3_sat r4.w, r15.xyzx, -r2.xyzx
mul r17.xyzw, r9.xyzw, l(-1.000000, -1.000000, -1.000000, 1.000000)
dp4 r18.x, r12.xyzw, r17.xyzw
dp4 r18.y, r13.xyzw, r17.xyzw
dp4 r18.z, r14.xyzw, r17.xyzw
max r17.xyz, r18.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r17.xyz, r17.xyzx, cb13[4].xxxx
log r4.w, r4.w
mul r4.w, r4.w, cb13[4].y
exp r4.w, r4.w
mad r16.xyz, r4.wwww, r16.xyzx, r17.xyzx
mad r11.xyz, r16.xyzx, r4.xxxx, r11.xyzx
sample_l_indexable(texture3d)(float,float,float,float) r4.w, r10.xyzx, t19.yzwx, s8, l(0.000000)
add r4.w, r4.w, l(-1.000000)
mad r1.w, r1.w, r4.w, l(1.000000)
dp3_sat r4.w, cb0[13].xyzx, r9.xyzx
min r5.x, r4.x, l(0.200000)
add r4.w, r4.w, r5.x
min r4.w, r4.w, l(1.000000)
dp3_sat r5.x, cb0[13].xyzx, -r9.xyzx
dp3_sat r5.z, cb0[13].xyzx, -r2.xyzx
log r5.z, r5.z
mul r5.z, r5.z, cb13[4].y
exp r5.z, r5.z
mad_sat r5.x, r5.x, cb13[4].x, r5.z
mul r4.x, r4.x, r5.x
mul r10.xyz, r3.wwww, cb0[12].xyzx
mul r10.xyz, r1.wwww, r10.xyzx
mul r10.xyz, r10.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
mul r16.xyz, r4.wwww, r10.xyzx
mad r10.xyz, r10.xyzx, r4.xxxx, r16.xyzx
add r10.xyz, r10.xyzx, r11.xyzx
add r1.w, r4.z, r4.z
mad r2.xyz, r9.xyzx, r1.wwww, -r2.xyzx
mul r11.xy, r8.yxyy, l(1.500000, -0.500000, 0.000000, 0.000000)
mov_sat r11.xy, r11.xyxx
mad r2.xyz, -r6.xyzx, r4.yyyy, r2.xyzx
mad r2.xyz, r11.xxxx, r2.xyzx, r9.xyzx
dp3 r1.w, r2.xyzx, r2.xyzx
rsq r1.w, r1.w
mul r6.xyz, r1.wwww, r2.xyzx
mul r16.xyz, r15.xyzx, l(0.666666746, 0.666666746, 0.666666746, 0.000000)
mov r16.w, l(0.333333373)
dp4 r12.x, r12.xyzw, r16.xyzw
dp4 r12.y, r13.xyzw, r16.xyzw
dp4 r12.z, r14.xyzw, r16.xyzw
dp4 r2.x, r16.xyzw, r16.xyzw
div r4.xyw, r12.xyxz, r2.xxxx
max r4.xyw, r4.xyxw, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r11.xzw, r1.xxyz, r0.wwww, r15.xxyz
dp3 r0.w, r11.xzwx, r11.xzwx
rsq r0.w, r0.w
mul r11.xzw, r0.wwww, r11.xxzw
dp3_sat r0.w, r11.xzwx, r9.xyzx
dp3_sat r2.x, r9.xyzx, r15.xyzx
dp3_sat r2.y, r15.xyzx, r11.xzwx
mad_sat r3.w, -r8.z, l(0.900000), l(1.000000)
mul r3.w, r3.w, r3.w
mul r3.w, r3.w, r3.w
add r2.y, -r2.y, l(1.000000)
mad r5.x, r8.w, l(0.840000), l(0.040000)
mul r5.z, r2.y, r2.y
mul r5.z, r5.z, r5.z
mul r7.w, r2.y, r5.z
mad r2.y, -r2.y, r5.z, l(1.000000)
div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
mad r2.y, r5.x, r7.w, r2.y
mad r5.x, r0.w, r3.w, -r0.w
mad r0.w, r5.x, r0.w, l(1.000000)
mul r0.w, r0.w, r0.w
div r0.w, r3.w, r0.w
mul r0.w, r0.w, r2.y
mul r0.w, r0.w, l(0.0397887304)
mul r4.xyw, r0.wwww, r4.xyxw
mul r4.xyw, r2.xxxx, r4.xyxw
sqrt r0.w, r5.y
mul r2.x, r0.w, l(8.000000)
mov_sat r8.x, r8.x
max r2.y, r2.w, l(0.000100)
log r2.y, r2.y
mul r2.w, r2.y, cb0[26].x
exp r2.w, r2.w
add r3.w, r2.w, r4.z
log r3.w, r3.w
mul r3.w, r3.w, r8.x
exp r3.w, r3.w
add r3.w, r2.w, r3.w
add_sat r3.w, r3.w, l(-1.000000)
mad_sat r3.w, cb0[25].x, r3.w, cb0[25].y
add r3.w, -r2.w, r3.w
mad r2.w, r8.x, r3.w, r2.w
lt r3.w, l(-0.500000), cb0[31].x
add r5.xyz, -v4.xyzx, cb12[7].xyzx
dp3 r5.x, r5.xyzx, r5.xyzx
sqrt r5.x, r5.x
mad_sat r5.x, r5.x, cb0[28].x, cb0[28].y
add r5.y, -cb0[30].x, cb0[31].x
mad r5.x, r5.x, r5.y, cb0[30].x
movc r3.w, r3.w, r5.x, cb0[30].x
mad r6.w, r2.z, r1.w, l(1.000000)
dp3 r1.w, r6.xywx, r6.xywx
rsq r1.w, r1.w
mul r5.xy, r1.wwww, r6.xyxx
mad r5.xy, r5.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r5.xyz, r5.xyxx, t26.xyzw, s10, r2.x
mul r2.xzw, r2.wwww, r5.xxyz
mul r5.xyz, r3.wwww, r2.xzwx
mul r1.w, r0.w, cb8[25].w
sample_l_indexable(texturecube)(float,float,float,float) r9.xyzw, r6.xyzx, t25.xyzw, s11, r1.w
lt r1.w, cb8[29].w, l(0.500000)
mul r8.yzw, r9.xxyz, r9.xxyz
movc r8.yzw, r1.wwww, r8.yyzw, r9.xxyz
mul r9.xyz, v4.yyyy, cb8[33].xyzx
mad r9.xyz, cb8[32].xyzx, v4.xxxx, r9.xyzx
mad r9.xyz, cb8[34].xyzx, v4.zzzz, r9.xyzx
add r9.xyz, r9.xyzx, cb8[35].xyzx
mul r1.w, r2.y, cb0[23].x
exp r1.w, r1.w
add r2.y, r1.w, r4.z
log r2.y, r2.y
mul r2.y, r2.y, r8.x
exp r2.y, r2.y
add r2.y, r1.w, r2.y
add_sat r2.y, r2.y, l(-1.000000)
mad_sat r2.y, cb0[22].x, r2.y, cb0[22].y
add r2.y, -r1.w, r2.y
mad r1.w, r8.x, r2.y, r1.w
mul r2.y, r1.w, cb8[24].w
add r11.xzw, cb8[30].xxyz, cb8[31].xxyz
mul r11.xzw, r2.yyyy, r11.xxzw
mul r8.yzw, r8.yyzw, r11.xxzw
mov_sat r11.xzw, -r9.xxyz
mad_sat r11.xzw, r11.xxzw, cb8[22].xxyz, -cb8[24].xxyz
add r11.xzw, -r11.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
mov_sat r12.xyz, r9.xyzx
mad_sat r12.xyz, r12.xyzx, cb8[23].xyzx, -cb8[25].xyzx
add r12.xyz, -r12.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r2.y, r12.y, r12.x
mul r2.y, r12.z, r2.y
mul r2.y, r11.x, r2.y
mul r2.y, r11.z, r2.y
mul r2.y, r11.w, r2.y
lt r6.w, l(0.000000), cb8[27].w
log r9.xyz, |r9.xyzx|
mul r9.xyz, r9.xyzx, cb8[27].wwww
exp r9.xyz, r9.xyzx
dp3 r7.w, r9.xyzx, cb8[27].xyzx
log r7.w, r7.w
mul r7.w, r7.w, cb8[28].x
exp r7.w, r7.w
mad_sat r7.w, cb8[28].y, r7.w, cb8[28].z
add r7.w, -r7.w, l(1.000000)
mul r7.w, r2.y, r7.w
movc r2.y, r6.w, r7.w, r2.y
mul r2.y, r2.y, r9.w
lt r6.w, l(0.000000), cb8[29].y
mul r9.xyz, r8.yzwy, cb0[32].xxxx
mul r8.yzw, r8.yyzw, cb0[29].xxxx
movc r8.yzw, r6.wwww, r9.xxyz, r8.yyzw
mul r2.y, r2.y, cb8[28].w
mad r2.xzw, -r2.xxzw, r3.wwww, r8.yyzw
mad r2.xyz, r2.yyyy, r2.xzwx, r5.xyzx
mul r0.w, r0.w, cb8[11].w
sample_l_indexable(texturecube)(float,float,float,float) r6.xyzw, r6.xyzx, t24.xyzw, s11, r0.w
lt r0.w, cb8[15].w, l(0.500000)
mul r5.xyz, r6.xyzx, r6.xyzx
movc r5.xyz, r0.wwww, r5.xyzx, r6.xyzx
mul r6.xyz, v4.yyyy, cb8[19].xyzx
mad r6.xyz, cb8[18].xyzx, v4.xxxx, r6.xyzx
mad r6.xyz, cb8[20].xyzx, v4.zzzz, r6.xyzx
add r6.xyz, r6.xyzx, cb8[21].xyzx
mul r0.w, r1.w, cb8[10].w
add r8.yzw, cb8[16].xxyz, cb8[17].xxyz
mul r8.yzw, r0.wwww, r8.yyzw
mul r5.xyz, r5.xyzx, r8.yzwy
mov_sat r8.yzw, -r6.xxyz
mad_sat r8.yzw, r8.yyzw, cb8[8].xxyz, -cb8[10].xxyz
add r8.yzw, -r8.yyzw, l(0.000000, 1.000000, 1.000000, 1.000000)
mov_sat r9.xyz, r6.xyzx
mad_sat r9.xyz, r9.xyzx, cb8[9].xyzx, -cb8[11].xyzx
add r9.xyz, -r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r0.w, r9.y, r9.x
mul r0.w, r9.z, r0.w
mul r0.w, r8.y, r0.w
mul r0.w, r8.z, r0.w
mul r0.w, r8.w, r0.w
lt r1.w, l(0.000000), cb8[13].w
log r6.xyz, |r6.xyzx|
mul r6.xyz, r6.xyzx, cb8[13].wwww
exp r6.xyz, r6.xyzx
dp3 r2.w, r6.xyzx, cb8[13].xyzx
log r2.w, r2.w
mul r2.w, r2.w, cb8[14].x
exp r2.w, r2.w
mad_sat r2.w, cb8[14].y, r2.w, cb8[14].z
add r2.w, -r2.w, l(1.000000)
mul r2.w, r0.w, r2.w
movc r0.w, r1.w, r2.w, r0.w
mul r0.w, r0.w, r6.w
lt r1.w, l(0.000000), cb8[15].y
mul r6.xyz, r5.xyzx, cb0[32].xxxx
mul r5.xyz, r5.xyzx, cb0[29].xxxx
movc r5.xyz, r1.wwww, r6.xyzx, r5.xyzx
mul r0.w, r0.w, cb8[14].w
add r5.xyz, -r2.xyzx, r5.xyzx
mad r2.xyz, r0.wwww, r5.xyzx, r2.xyzx
add r0.w, -r8.x, l(1.000000)
add_sat r1.w, -r4.z, l(1.000000)
mul r2.w, r1.w, r1.w
mul r2.w, r2.w, r2.w
mul r1.w, r1.w, r2.w
add r0.w, -r11.y, r0.w
add_sat r0.w, r0.w, r0.w
add r0.w, -r0.w, l(1.000000)
mul r2.w, r0.w, r1.w
mad r3.w, r8.x, l(0.600000), l(0.400000)
mad r0.w, -r1.w, r0.w, l(1.000000)
mul r0.w, r0.w, r3.w
mad r5.xyz, r3.xyzx, r0.wwww, r2.wwww
max r0.w, r5.w, l(0.001000)
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
mul r5.xyz, r0.wwww, r5.xyzx
mul r4.xyz, r0.wwww, r4.xywx
mul r2.xyz, r2.xyzx, r5.xyzx
mad r2.xyz, r3.xyzx, r4.xyzx, r2.xyzx
mad r2.xyz, r7.xyzx, r10.xyzx, r2.xyzx
mul r2.xyz, r2.xyzx, cb13[1].xxxx
dp3 r0.w, -r1.xyzx, -r1.xyzx
sqrt r0.w, r0.w
mul r1.x, r0.w, l(0.015625)
min r1.x, r1.x, l(1.000000)
sqrt r0.z, r1.x
sample_l_indexable(texture3d)(float,float,float,float) r0.z, r0.xyzx, t21.yzxw, s7, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyxx, t20.xyzw, s7, l(0.000000)
add r1.xyzw, r1.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
mad r1.xyzw, r0.zzzz, r1.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
mad_sat r0.z, r0.w, cb0[10].x, cb0[10].y
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.xyxx, t11.xyzw, s6
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.xyxx, t13.xyzw, s6
add r3.xyzw, r3.xyzw, -r4.xyzw
mad r0.xyzw, r0.zzzz, r3.xyzw, r4.xyzw
mul r0.xyz, r0.xyzx, cb8[5].xyzx
mad r0.xyz, r0.wwww, cb8[6].xyzx, r0.xyzx
mul r2.xyz, r2.xyzx, cb8[7].xyzx
mad r1.xyz, r2.xyzx, r1.wwww, r1.xyzx
mad r0.xyz, r0.xyzx, cb13[1].xxxx, r1.xyzx
mul o0.xyz, r5.wwww, r0.xyzx
mov o0.w, r5.w
ret
// Approximately 0 instruction slots used
