//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:57 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyzw        4     NONE   float   x zw
// TEXCOORD                 5   xy          5     NONE   float   xy
// SV_POSITION              0   xyzw        6      POS   float   xy
// SV_isFrontFace           0   x           7    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[134], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[13], immediateIndexed
dcl_constantbuffer cb2[1], immediateIndexed
dcl_constantbuffer cb8[8], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xzw
dcl_input_ps linear v5.xy
dcl_input_ps_siv linear noperspective v6.xy, position
dcl_output o0.xyzw
dcl_temps 4
mad r0.xy, v0.xyxx, cb0[8].xyxx, cb0[8].zwzz
sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t0.xyzw, s3
log r0.x, r0.x
mul r0.x, r0.x, l(2.200000)
exp r0.x, r0.x
mul r0.z, v4.z, l(0.500000)
mov r1.zw, l(0,0,0,0)
mul r2.xy, v6.xyxx, cb12[12].zwzz
mul r3.xy, r2.xyxx, cb12[12].xyxx
ftoi r1.xy, r3.xyxx
ld_indexable(texture2d)(float,float,float,float) r0.w, r1.xyzw, t10.yzwx
mad r0.w, r0.w, cb2[0].y, cb2[0].x
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
add r0.w, r0.w, -v0.w
div_sat r0.z, r0.w, r0.z
add r0.z, -r0.z, l(1.000000)
add r0.y, r0.z, v4.x
add r0.z, -r0.z, l(1.000000)
sample_indexable(texture2d)(float,float,float,float) r0.xyw, r0.xyxx, t1.xywz, s4
add r0.xyw, r0.xyxw, l(-2.511886521E-007, -2.511886521E-007, 0.000000, -2.511886521E-007)
mul r0.xyw, r0.xyxw, l(1.00000024, 1.00000024, 0.000000, 1.00000024)
max r0.xyw, r0.xyxw, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r0.xyw, r0.xyxw, v3.xyxz
mul r0.xyw, r0.xyxw, v5.yyyy
mul r0.xyw, r0.xyxw, cb13[1].wwww
mul r0.xyw, r0.xyxw, cb13[1].xxxx
mul r0.xyw, r0.xyxw, cb8[7].xyxz
dp3 r1.x, -v2.xyzx, -v2.xyzx
sqrt r1.x, r1.x
mul r1.y, r1.x, l(0.015625)
mad_sat r1.x, r1.x, cb0[113].x, cb0[113].y
min r1.y, r1.y, l(1.000000)
sqrt r2.z, r1.y
sample_l_indexable(texture3d)(float,float,float,float) r1.y, r2.xyzx, t21.yxzw, s2, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.xyxx, t20.xyzw, s2, l(0.000000)
add r3.xyzw, r3.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
mad r3.xyzw, r1.yyyy, r3.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
mad r0.xyw, r0.xyxw, r3.wwww, r3.xyxz
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.xyxx, t11.xyzw, s1
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyxx, t13.xyzw, s1
add r3.xyzw, -r2.xyzw, r3.xyzw
mad r1.xyzw, r1.xxxx, r3.xyzw, r2.xyzw
mul r1.xyz, r1.xyzx, cb8[5].xyzx
mad r1.xyz, r1.wwww, cb8[6].xyzx, r1.xyzx
mad r0.xyw, r1.xyxz, cb13[1].xxxx, r0.xyxw
mad r1.xy, v0.xyxx, cb0[10].xyxx, cb0[10].zwzz
sample_indexable(texture2d)(float,float,float,float) r1.x, r1.xyxx, t0.xyzw, s3
log r1.x, r1.x
mul r1.x, r1.x, l(2.200000)
exp r1.x, r1.x
mad r1.yz, v0.xxyx, cb0[9].xxyx, cb0[9].zzwz
sample_indexable(texture2d)(float,float,float,float) r1.y, r1.yzyy, t2.yxzw, s3
mul r1.x, r1.y, r1.x
log r1.x, r1.x
div r1.y, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[133].x
mul r1.x, r1.x, r1.y
exp r1.x, r1.x
mad r1.x, r1.x, v5.x, v4.w
add r1.y, v3.w, l(-0.500000)
mul_sat r1.y, r1.y, l(0.500000)
mul_sat r1.x, r1.y, r1.x
mul_sat r1.x, r1.x, v0.z
mul r0.z, r0.z, r1.x
mul o0.xyz, r0.zzzz, r0.xywx
mov o0.w, r0.z
ret
// Approximately 0 instruction slots used
