//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:57 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyz
// TEXCOORD                 1   xyzw        1     NONE   float   xyz
// TEXCOORD                 2   xyzw        2     NONE   float   xyzw
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// SV_POSITION              0   xyzw        5      POS   float   xy
// SV_isFrontFace           0   x           6    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[14], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[15], immediateIndexed
dcl_constantbuffer cb8[8], immediateIndexed
dcl_constantbuffer cb7[63], dynamicIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texture2d (float,float,float,float) t26
dcl_resource_texture2d (float,float,float,float) t27
dcl_input_ps linear v0.xyz
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyz
dcl_input_ps_siv linear noperspective v5.xy, position
dcl_output o0.xyzw
dcl_temps 12
mul r0.xy, v5.xyxx, cb12[12].zwzz
add r1.xyz, -v4.xyzx, cb12[14].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r1.xyzx
ftou r0.w, v2.w
uge r1.w, r0.w, l(4)
if_nz r1.w
  mad r3.xy, v3.zwzz, cb7[6].xyxx, cb7[6].zwzz
  mad r3.zw, v3.zzzw, cb7[7].xxxy, cb7[7].zzzw
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r3.xyxx, t8.xyzw, s1
  sample_indexable(texture2d)(float,float,float,float) r3.xy, r3.zwzz, t9.xyzw, s1
  mad r3.xy, r3.xyxx, cb7[8].xxxx, cb7[8].yyyy
else
  uge r1.w, r0.w, l(2)
  if_nz r1.w
    mad r3.zw, v3.zzzw, cb7[3].xxxy, cb7[3].zzzw
    mad r5.xy, v3.zwzz, cb7[4].xyxx, cb7[4].zwzz
    sample_indexable(texture2d)(float,float,float,float) r4.xyz, r3.zwzz, t6.xyzw, s1
    sample_indexable(texture2d)(float,float,float,float) r3.zw, r5.xyxx, t7.zwxy, s1
    mad r3.xy, r3.zwzz, cb7[5].xxxx, cb7[5].yyyy
  else
    mad r3.zw, v3.zzzw, cb7[0].xxxy, cb7[0].zzzw
    mad r5.xy, v3.zwzz, cb7[1].xyxx, cb7[1].zwzz
    sample_indexable(texture2d)(float,float,float,float) r4.xyz, r3.zwzz, t4.xyzw, s1
    sample_indexable(texture2d)(float,float,float,float) r3.zw, r5.xyxx, t5.zwxy, s1
    mad r3.xy, r3.zwzz, cb7[2].xxxx, cb7[2].yyyy
  endif
endif
imad r5.xyzw, l(9, 9, 9, 9), r0.wwww, l(9, 11, 14, 15)
imad r0.w, l(9), r0.w, l(17)
mov_sat r3.zw, cb7[r5.y + 0].xxxy
mov_sat r6.xy, cb7[r0.w + 0].xyxx
sample_indexable(texture2d)(float,float,float,float) r7.xyz, v3.xyxx, t0.xyzw, s3
sample_indexable(texture2d)(float,float,float,float) r6.zw, v3.xyxx, t1.zwxy, s4
mad r6.zw, r6.zzzw, cb0[4].xxxx, cb0[4].yyyy
sample_indexable(texture2d)(float,float,float,float) r8.zw, v3.xyxx, t2.xzwy, s5
ge r0.w, r8.z, l(0.156862751)
and r0.w, r0.w, l(0x3f800000)
add r1.w, r8.z, l(-0.188235298)
mul_sat r1.w, r1.w, l(1.231884)
mad_sat r1.w, cb7[r5.w + 0].y, r1.w, cb7[r5.w + 0].x
mad_sat r1.w, cb7[r5.w + 0].w, r1.w, cb7[r5.w + 0].z
mul_sat r9.xyz, r4.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r4.xyz, r4.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad_sat r10.xyz, cb7[r5.x + 0].xyzx, r9.xyzx, r4.xyzx
add r10.xyz, r10.xyzx, -cb7[r5.x + 0].xyzx
mad r5.xyw, r3.zzzz, r10.xyxz, cb7[r5.x + 0].xyxz
mul_sat r10.xyz, r7.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r11.xyz, r7.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad_sat r5.xyw, r5.xyxw, r10.xyxz, r11.xyxz
mad r3.zw, r3.xxxy, r3.wwww, r6.zzzw
mad_sat r4.xyz, cb7[r5.z + 0].xyzx, r9.xyzx, r4.xyzx
add r4.xyz, r4.xyzx, -cb7[r5.z + 0].xyzx
mad r4.xyz, r6.xxxx, r4.xyzx, cb7[r5.z + 0].xyzx
mad_sat r4.xyz, r4.xyzx, r10.xyzx, r11.xyzx
mad r3.xy, r3.xyxx, r6.yyyy, r6.zwzz
mov r4.w, l(1.000000)
add r5.xyz, -r4.xyzx, r5.xywx
mov r5.w, l(0)
mad r4.xyzw, r1.wwww, r5.xyzw, r4.xyzw
add r3.zw, -r3.xxxy, r3.zzzw
mad r3.xy, r1.wwww, r3.zwzz, r3.xyxx
mov r8.xyz, r7.xyzx
add r4.xyzw, r4.xyzw, -r8.xyzw
mad r4.xyzw, r0.wwww, r4.xyzw, r8.xyzw
add r3.xy, -r6.zwzz, r3.xyxx
mad r3.xy, r0.wwww, r3.xyxx, r6.zwzz
dp2 r0.w, r3.xyxx, r3.xyxx
add r0.w, -r0.w, l(1.000000)
max r0.w, r0.w, l(0.000000)
sqrt r3.z, r0.w
dp3 r0.w, r3.xyzx, r3.xyzx
rsq r0.w, r0.w
mul r3.xyz, r0.wwww, r3.xyzx
mul r5.xyz, r3.yyyy, v2.xyzx
mad r3.xyw, v1.xyxz, r3.xxxx, r5.xyxz
mad r3.xyz, v0.xyzx, r3.zzzz, r3.xywx
dp3 r0.w, r3.xyzx, r3.xyzx
rsq r0.w, r0.w
mul r3.xyz, r0.wwww, r3.xyzx
mad r5.xy, v3.xyxx, cb0[7].xyxx, cb0[7].zwzz
mad r5.zw, v3.xxxy, cb0[8].xxxy, cb0[8].zzzw
sample_indexable(texture2d)(float,float,float,float) r5.zw, r5.zwzz, t26.zwxy, s2
mad r5.xy, r5.zwzz, cb0[9].xyxx, r5.xyxx
add r5.xy, r5.xyxx, cb0[9].zwzz
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyxx, t27.xyzw, s2
mul_sat r6.xyzw, r5.xyzw, l(4.000000, 4.000000, 4.000000, 4.000000)
add_sat r5.xyzw, r5.xyzw, l(-0.250000, -0.250000, -0.250000, -0.250000)
mad r5.xyzw, cb0[6].xyzw, r6.xyzw, r5.xyzw
mul_sat r6.xyzw, r4.xyzw, l(4.000000, 4.000000, 4.000000, 4.000000)
add_sat r4.xyzw, r4.xyzw, l(-0.250000, -0.250000, -0.250000, -0.250000)
mad r4.xyzw, r5.xyzw, r6.xyzw, r4.xyzw
mul r4.xyzw, r4.xyzw, cb0[10].xxxx
dp3 r0.w, r2.xyzx, r3.xyzx
add r0.w, -r0.w, l(1.000000)
mad r0.w, -r0.w, r0.w, l(1.000000)
mad_sat r0.w, r0.w, cb0[12].x, cb0[12].y
mad r2.xyzw, cb0[13].xyzw, r0.wwww, cb0[11].xyzw
mul r2.xyzw, r2.xyzw, r4.xyzw
mul r2.xyz, r2.xyzx, cb13[1].wwww
mul r2.xyz, r2.xyzx, cb13[1].xxxx
dp3 r0.w, -r1.xyzx, -r1.xyzx
sqrt r0.w, r0.w
mul r0.w, r0.w, l(0.015625)
min r0.w, r0.w, l(1.000000)
sqrt r0.z, r0.w
sample_l_indexable(texture3d)(float,float,float,float) r0.z, r0.xyzx, t21.yzxw, s6, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t20.wxyz, s6, l(0.000000)
add r0.x, r0.x, l(-1.000000)
mad r0.x, r0.z, r0.x, l(1.000000)
mul r0.yzw, r2.xxyz, cb8[7].xxyz
mul r0.x, r0.x, r2.w
mul o0.xyz, r0.xxxx, r0.yzwy
mov o0.w, l(0)
ret
// Approximately 0 instruction slots used
