//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:02 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float
// TEXCOORD                 1   xyzw        1     NONE   float
// TEXCOORD                 2   xyzw        2     NONE   float
// TEXCOORD                 3   xyzw        3     NONE   float   xy
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// TEXCOORD                 8   xyzw        5     NONE   float    y
// SV_POSITION              0   xyzw        6      POS   float   xy
// SV_isFrontFace           0   x           7    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[42], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[15], immediateIndexed
dcl_constantbuffer cb8[8], immediateIndexed
dcl_constantbuffer cb7[55], dynamicIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texture2d (float,float,float,float) t26
dcl_resource_texture2d (float,float,float,float) t27
dcl_resource_texture2d (float,float,float,float) t28
dcl_resource_texture2d (float,float,float,float) t29
dcl_resource_texture2d (float,float,float,float) t30
dcl_resource_texture2d (float,float,float,float) t31
dcl_input_ps linear v3.xy
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.y
dcl_input_ps_siv linear noperspective v6.xy, position
dcl_output o0.xyzw
dcl_temps 8
mul r0.xy, v6.xyxx, cb12[12].zwzz
add r1.xyz, -v4.xyzx, cb12[14].xyzx
sample_indexable(texture2d)(float,float,float,float) r2.xyz, v3.xyxx, t3.xyzw, s4
add r0.w, -r2.z, r2.y
lt r0.w, r0.w, l(0.00470588217)
movc r0.w, r0.w, r2.y, r2.z
deriv_rtx_coarse r3.xy, r2.xyxx
deriv_rtx_coarse r3.z, r0.w
deriv_rty_coarse r4.xy, r2.xyxx
deriv_rty_coarse r4.z, r0.w
mul r2.zw, r3.yyyz, r3.xxxx
mul r3.xy, r4.yzyy, r4.xxxx
lt r3.zw, |r3.xxxy|, |r2.zzzw|
movc r2.zw, r3.zzzw, r2.zzzw, r3.xxxy
add r1.w, r2.x, l(-0.500000)
lt r1.w, |r1.w|, l(0.00470588217)
add r3.x, r2.y, r2.x
add r3.x, r3.x, l(-1.000000)
lt r3.x, |r3.x|, l(0.00588235306)
lt r2.zw, r2.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
and r2.z, r2.z, r3.x
add r3.x, -r2.y, l(1.000000)
movc r2.z, r2.z, r3.x, r2.x
add r3.x, r0.w, r2.z
add r3.x, r3.x, l(-1.000000)
lt r3.x, |r3.x|, l(0.00588235306)
and r2.w, r2.w, r3.x
add r3.x, -r0.w, l(1.000000)
movc r2.z, r2.w, r3.x, r2.z
movc r1.w, r1.w, r2.z, r2.x
ge r0.w, r0.w, l(0.500000)
if_nz r0.w
  mov r0.w, l(4)
else
  ge r2.x, r2.y, l(0.500000)
  if_nz r2.x
    mov r0.w, l(2)
  else
    mov r0.w, l(0)
  endif
endif
ge r1.w, r1.w, l(0.500000)
iadd r2.x, r0.w, l(1)
movc r0.w, r1.w, r2.x, r0.w
imul null, r0.w, r0.w, l(9)
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, v3.xyxx, t0.xyzw, s2
sample_indexable(texture2d)(float,float,float,float) r1.w, v3.xyxx, t2.xyzw, s3
ge r1.w, r1.w, l(0.156862751)
and r1.w, r1.w, l(0x3f800000)
mul r3.x, v5.y, cb0[7].x
max r3.x, r3.x, l(0.000000)
log r3.x, r3.x
mul r3.x, r3.x, cb0[8].x
exp r3.x, r3.x
add r3.x, r3.x, cb0[9].x
mov r3.y, l(0)
sample_indexable(texture2d)(float,float,float,float) r3.x, r3.xyxx, t26.xyzw, s5
mad_sat r3.x, r3.x, cb0[10].x, cb0[10].y
mad r3.xyzw, cb0[12].xyzw, r3.xxxx, cb0[11].xyzw
mad r4.xy, v3.xyxx, cb0[13].xyxx, cb0[13].zwzz
sample_indexable(texture2d)(float,float,float,float) r4.xy, r4.xyxx, t27.xyzw, s1
add r4.xy, r4.xyxx, -cb0[15].xyxx
mad r4.xy, r4.xyxx, cb0[14].xxxx, v3.xyxx
mad r4.xy, r4.xyxx, cb0[16].xyxx, cb0[16].zwzz
sample_indexable(texture2d)(float,float,float,float) r4.xyz, r4.xyxx, t28.xyzw, s1
mad r5.xy, v3.xyxx, cb0[17].xyxx, cb0[17].zwzz
sample_indexable(texture2d)(float,float,float,float) r5.xyz, r5.xyxx, t29.xyzw, s1
mov r5.w, l(1.000000)
mad r6.xy, v3.yxyy, cb0[19].yxyy, cb0[19].wzww
round_ne r6.zw, r6.xxxy
add r6.xy, -r6.zwzz, r6.xyxx
mad r6.zw, |r6.xxxy|, l(0.000000, 0.000000, -16.000000, -16.000000), l(0.000000, 0.000000, 8.000000, 8.000000)
mul r6.xy, r6.zwzz, r6.xyxx
mad r6.zw, |r6.xxxy|, l(0.000000, 0.000000, 0.225000, 0.225000), l(0.000000, 0.000000, 0.775000, 0.775000)
mul r6.xy, r6.zwzz, r6.xyxx
mad r6.xy, cb0[20].yxyy, r6.xyxx, v3.xyxx
mad r6.zw, r6.yyyx, cb0[21].yyyx, cb0[21].wwwz
round_ne r7.xy, r6.zwzz
add r6.zw, r6.zzzw, -r7.xxxy
mad r7.xy, |r6.zwzz|, l(-16.000000, -16.000000, 0.000000, 0.000000), l(8.000000, 8.000000, 0.000000, 0.000000)
mul r6.zw, r6.zzzw, r7.xxxy
mad r7.xy, |r6.zwzz|, l(0.225000, 0.225000, 0.000000, 0.000000), l(0.775000, 0.775000, 0.000000, 0.000000)
mul r6.zw, r6.zzzw, r7.xxxy
mad r6.xy, cb0[22].yxyy, r6.zwzz, r6.xyxx
mad r6.z, r6.y, cb0[23].y, cb0[23].w
mad r7.xy, r6.xyxx, cb0[24].xyxx, cb0[24].zwzz
sample_indexable(texture2d)(float,float,float,float) r6.w, r7.xyxx, t30.xzwy, s1
add r6.w, r6.w, -cb0[26].y
mad r6.z, r6.w, cb0[25].x, r6.z
frc r6.z, r6.z
add r6.w, r6.z, cb0[27].z
mad_sat r6.w, cb0[27].y, |r6.w|, cb0[27].x
add r6.z, r6.z, cb0[28].z
mad_sat r6.z, cb0[28].y, |r6.z|, cb0[28].x
add r6.z, r6.z, r6.w
min r6.z, r6.z, l(1.000000)
mad r7.xy, r6.xyxx, cb0[29].xyxx, cb0[29].zwzz
mul r6.w, cb0[7].x, cb0[30].x
sample_indexable(texture2d)(float,float,float,float) r6.xy, r6.xyxx, t30.xyzw, s1
add r6.xy, r6.xyxx, -cb0[31].xyxx
mad r6.xy, r6.xyxx, r6.wwww, r7.xyxx
sample_indexable(texture2d)(float,float,float,float) r6.x, r6.xyxx, t31.xyzw, s1
add r6.y, -r6.x, l(1.000000)
max r6.y, r6.y, l(0.000000)
log r6.y, r6.y
mul r6.y, r6.y, cb0[32].x
exp r6.y, r6.y
mad r6.y, r6.y, cb0[33].x, cb0[7].x
log r6.z, r6.z
mul r6.y, r6.z, r6.y
exp r6.y, r6.y
add_sat r6.y, r6.y, cb0[34].x
add r6.x, r6.x, cb0[35].x
mad r6.xyz, r6.yyyy, r6.xxxx, cb0[34].xxxx
mov r6.w, l(1.000000)
mul r6.xyzw, r6.xyzw, cb0[36].xyzw
mad r5.xyzw, r5.xyzw, cb0[18].xyzw, r6.xyzw
mov r4.w, l(1.000000)
add r4.xyzw, r5.xyzw, r4.xyzw
mul r3.xyzw, r3.xyzw, r4.xyzw
mad_sat r3.xyzw, r3.xyzw, cb0[37].xxxx, cb0[37].yyyy
mul r3.xyzw, r3.xyzw, cb0[6].xyzw
mov_sat r4.x, v5.y
mad r4.xyzw, cb0[39].xyzw, r4.xxxx, cb0[38].xyzw
mul r3.xyzw, r3.xyzw, r4.xyzw
mul r3.xyzw, r2.xyzw, r3.xyzw
add r2.w, -v5.y, l(1.000000)
mul r2.w, r2.w, r2.w
add r4.x, cb0[40].x, cb0[41].x
mul r2.w, r2.w, r4.x
mul r4.xyzw, r2.wwww, r3.xyzw
mul_sat r5.xyz, r2.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r2.xyz, r2.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad r2.xyz, cb7[r0.w + 9].xyzx, r5.xyzx, r2.xyzx
mad r2.xyz, -r3.xyzx, r2.wwww, r2.xyzx
mad r2.xyz, r1.wwww, r2.xyzx, r4.xyzx
mad r0.w, -r3.w, r2.w, l(1.000000)
mad r0.w, r1.w, r0.w, r4.w
mul r2.xyz, r2.xyzx, cb13[1].wwww
mul r2.xyz, r2.xyzx, cb13[1].xxxx
dp3 r1.x, -r1.xyzx, -r1.xyzx
sqrt r1.x, r1.x
mul r1.x, r1.x, l(0.015625)
min r1.x, r1.x, l(1.000000)
sqrt r0.z, r1.x
sample_l_indexable(texture3d)(float,float,float,float) r0.z, r0.xyzx, t21.yzxw, s6, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t20.wxyz, s6, l(0.000000)
add r0.x, r0.x, l(-1.000000)
mad r0.x, r0.z, r0.x, l(1.000000)
mul r1.xyz, r2.xyzx, cb8[7].xyzx
mul r0.x, r0.x, r0.w
mul o0.xyz, r0.xxxx, r1.xyzx
mov o0.w, l(0)
ret
// Approximately 0 instruction slots used
