//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:58 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float
// TEXCOORD                 1   xyzw        1     NONE   float
// TEXCOORD                 2   xyz         2     NONE   float
// TEXCOORD                 3   xyzw        3     NONE   float
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// SV_POSITION              0   xyzw        5      POS   float   xy
// SV_isFrontFace           0   x           6    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[11], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[13], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_input_ps linear v4.xyz
dcl_input_ps_siv linear noperspective v5.xy, position
dcl_output o0.xyzw
dcl_temps 5
mul r0.x, l(0.750000), cb0[6].x
max r0.x, r0.x, l(0.000000)
add r0.yzw, v4.xxyz, -cb12[7].xxyz
dp3 r1.x, r0.yzwy, r0.yzwy
sqrt r1.y, r1.x
rsq r1.x, r1.x
add r0.x, -r0.x, r1.y
mul_sat r0.x, r0.x, l(0.000020)
sqrt r2.x, r0.x
div r0.x, r0.w, r1.y
mul r1.y, r1.y, l(0.015625)
min r1.y, r1.y, l(1.000000)
sqrt r3.z, r1.y
mad r2.y, r0.x, l(0.500000), l(0.500000)
sample_l_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyxx, t15.xyzw, s3, l(0.000000)
add r0.x, cb0[7].x, cb0[8].x
mul r4.xyzw, r0.xxxx, cb0[9].xyzw
mul r1.yzw, r4.xxyz, cb0[10].xxxx
mul r1.yzw, r2.xxyz, r1.yyzw
mul r2.xy, v5.xyxx, cb12[12].zwzz
mul r3.xy, r2.xyxx, l(4.000000, 4.000000, 0.000000, 0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r0.x, r3.xyzx, t21.xyzw, s1, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r3.xyzw, r3.xyxx, t20.xyzw, s1, l(0.000000)
add r3.xyzw, r3.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
mad r3.xyzw, r0.xxxx, r3.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
mad r1.yzw, r1.yyzw, r3.wwww, r3.xxyz
mad r3.w, r0.w, r1.x, l(1.000000)
mul r3.xy, r0.yzyy, r1.xxxx
dp3 r0.x, r3.xywx, r3.xywx
rsq r0.x, r0.x
mul r0.xy, r0.xxxx, r3.xyxx
mad r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyxx, t4.xyzw, s2
mul r0.w, cb0[4].x, cb13[1].x
mad r0.w, -r0.w, r2.w, r0.w
mad r0.xyz, r0.xyzx, r0.wwww, r1.yzwy
mul o0.xyz, r4.wwww, r0.xyzx
mov o0.w, r4.w
ret
// Approximately 0 instruction slots used
