//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:55 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xy          3     NONE   float    y
// SV_POSITION              0   xyzw        4      POS   float   xy
// SV_isFrontFace           0   x           5    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[103], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[13], immediateIndexed
dcl_constantbuffer cb2[1], immediateIndexed
dcl_constantbuffer cb8[8], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.y
dcl_input_ps_siv linear noperspective v4.xy, position
dcl_output o0.xyzw
dcl_temps 3
add r0.xy, v0.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
add r0.z, -|r0.y|, |r0.x|
add r0.w, |r0.y|, |r0.x|
div r0.z, r0.z, r0.w
add r0.z, r0.z, l(-1.000000)
lt r1.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r0.xyxx
lt r1.zw, r0.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r1.xy, -r1.xyxx, r1.zwzz
itof r1.xy, r1.xyxx
mad r0.z, r0.z, r1.y, l(2.000000)
mul r0.z, r0.z, r1.x
mul r0.z, r0.z, l(0.125000)
frc r1.x, r0.z
dp2 r0.z, |r0.xyxx|, |r0.xyxx|
dp2 r0.x, r0.xyxx, r0.xyxx
sqrt r0.x, r0.x
mad r0.xy, r0.xxxx, l(-2.500000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
max r0.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
log r0.z, r0.z
mul r0.z, r0.z, cb0[102].x
exp r1.y, r0.z
mad r0.zw, r1.xxxy, cb0[8].xxxy, cb0[8].zzzw
sample_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t0.yzxw, s1
mad r0.y, r0.y, r0.y, r0.z
mad r0.y, r0.y, l(2.000000), l(-0.500000)
mul_sat r0.x, r0.y, r0.x
add r0.x, r0.x, l(-2.511886521E-007)
mul r0.x, r0.x, l(1.00000024)
max r0.x, r0.x, l(0.000000)
mul r0.x, r0.x, cb13[1].w
mul r0.x, r0.x, cb13[1].x
mul r0.xyz, r0.xxxx, cb8[7].xyzx
dp3 r0.w, -v2.xyzx, -v2.xyzx
sqrt r0.w, r0.w
mul r0.xyzw, r0.xyzw, l(3.14617014, 5.18128967, 5.22521973, 0.015625)
min r0.w, r0.w, l(1.000000)
sqrt r1.z, r0.w
mul r1.xy, v4.xyxx, cb12[12].zwzz
sample_l_indexable(texture3d)(float,float,float,float) r0.w, r1.xyzx, t21.yzwx, s2, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.z, r1.xyxx, t20.xywz, s2, l(0.000000)
mul r1.xy, r1.xyxx, cb12[12].xyxx
ftoi r2.xy, r1.xyxx
add r1.x, r1.z, l(-1.000000)
mad r0.w, r0.w, r1.x, l(1.000000)
mov_sat r1.x, v3.y
mul_sat r1.x, r1.x, v0.z
mul r0.w, r0.w, r1.x
mov r2.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r1.x, r2.xyzw, t10.xyzw
mad r1.x, r1.x, cb2[0].y, cb2[0].x
div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
add_sat r1.x, r1.x, -v0.w
add r1.x, -r1.x, l(1.000000)
add r1.x, -r1.x, l(1.000000)
mul r0.w, r0.w, r1.x
mul o0.xyz, r0.wwww, r0.xyzx
mov o0.w, l(0)
ret
// Approximately 0 instruction slots used
