//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:57 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyz
// TEXCOORD                 1   xyzw        1     NONE   float
// TEXCOORD                 2   xyz         2     NONE   float
// TEXCOORD                 3   xyzw        3     NONE   float   xy
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// SV_POSITION              0   xyzw        5      POS   float   xy
// SV_isFrontFace           0   x           6    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[71], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[15], immediateIndexed
dcl_constantbuffer cb3[16], immediateIndexed
dcl_constantbuffer cb8[36], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texturecube (float,float,float,float) t24
dcl_resource_texturecube (float,float,float,float) t25
dcl_input_ps linear v0.xyz
dcl_input_ps linear v3.xy
dcl_input_ps linear v4.xyz
dcl_input_ps_siv linear noperspective v5.xy, position
dcl_output o0.xyzw
dcl_temps 16
mul r0.xy, v5.xyxx, cb12[12].zwzz
add r1.xyz, -v4.xyzx, cb12[14].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r1.xyzx
add r3.xyz, v4.xyzx, -cb12[14].xyzx
dp3 r1.w, -cb12[6].xyzx, r3.xyzx
dp3 r2.w, v0.xyzx, v0.xyzx
rsq r2.w, r2.w
mul r4.xyz, r2.wwww, v0.xyzx
dp3 r3.w, r2.xyzx, v0.xyzx
mul r3.w, r3.w, r3.w
mad r3.w, r3.w, cb0[12].x, cb0[12].y
mad r3.w, r3.w, cb0[13].x, cb0[13].y
lt r5.x, r3.w, cb0[20].x
lt r5.y, r3.w, cb0[21].x
ge r5.z, r3.w, cb0[20].x
and r5.y, r5.z, r5.y
lt r5.z, r3.w, cb0[22].x
ge r5.w, r3.w, cb0[21].x
and r5.z, r5.w, r5.z
ge r5.w, r3.w, cb0[22].x
add r6.x, r3.w, -cb0[24].x
mul_sat r6.x, r6.x, cb0[24].y
add r6.yzw, -cb0[14].xxyz, cb0[15].xxyz
mad r6.xyz, r6.xxxx, r6.yzwy, cb0[14].xyzx
add r6.w, r3.w, -cb0[25].x
mul_sat r6.w, r6.w, cb0[25].y
add r7.xyz, -cb0[15].xyzx, cb0[16].xyzx
mad r7.xyz, r6.wwww, r7.xyzx, cb0[15].xyzx
add r6.w, r3.w, -cb0[26].x
mul_sat r6.w, r6.w, cb0[26].y
add r8.xyz, -cb0[16].xyzx, cb0[17].xyzx
mad r8.xyz, r6.wwww, r8.xyzx, cb0[16].xyzx
add r3.w, r3.w, -cb0[27].x
mul_sat r3.w, r3.w, cb0[27].y
add r9.xyz, -cb0[17].xyzx, cb0[18].xyzx
mad r9.xyz, r3.wwww, r9.xyzx, cb0[17].xyzx
and r6.xyz, r5.xxxx, r6.xyzx
movc r6.xyz, r5.yyyy, r7.xyzx, r6.xyzx
movc r5.xyz, r5.zzzz, r8.xyzx, r6.xyzx
movc r5.xyz, r5.wwww, r9.xyzx, r5.xyzx
mul r5.xyz, r5.xyzx, cb0[28].xyzx
add r6.xy, v3.xyxx, -cb0[29].xyxx
dp2 r3.w, r6.xyxx, r6.xyxx
sqrt r3.w, r3.w
mad_sat r3.w, r3.w, cb0[31].x, cb0[31].y
mad r6.xyz, cb0[33].xyzx, r3.wwww, cb0[32].xyzx
mad r5.xyz, r5.xyzx, cb0[34].xxxx, r6.xyzx
add r6.xy, v3.xyxx, -cb0[35].xyxx
dp2 r3.w, r6.xyxx, r6.xyxx
sqrt r3.w, r3.w
mad_sat r3.w, r3.w, cb0[37].x, cb0[37].y
add r3.w, r3.w, cb0[38].x
add r6.xy, v3.xyxx, -cb0[39].xyxx
dp2 r5.w, r6.xyxx, r6.xyxx
sqrt r5.w, r5.w
mad_sat r5.w, r5.w, cb0[41].x, cb0[41].y
mad_sat r5.w, r5.w, cb0[42].x, cb0[42].y
mul r3.w, r3.w, r5.w
mul_sat r3.w, r3.w, cb0[43].x
mov_sat r5.w, cb0[11].x
add r6.x, l(128.500000), cb0[8].x
mul r6.x, r6.x, l(0.00390625000)
ge r6.y, cb0[9].x, cb0[10].x
movc r6.x, r6.y, r6.x, l(-1.000000)
mul r5.xyz, r5.xyzx, cb0[70].xxxx
dp3 r6.y, r4.xyzx, r2.xyzx
mad r6.z, r6.x, l(255.000000), l(-127.500000)
mul_sat r7.y, r6.z, l(0.00781250000)
mul r6.z, r6.y, r6.y
min r7.x, r6.z, l(1.000000)
sample_l_indexable(texture2d)(float,float,float,float) r7.xyzw, r7.xyxx, t5.xyzw, s8, l(0.000000)
mul r7.xyzw, r7.xyzw, r7.xyzw
add r6.z, l(1.000000), -cb0[10].x
mul r6.w, r6.z, l(0.040000)
lt r6.x, l(0.500000), r6.x
mul r8.xyz, r5.xyzx, r7.wwww
movc r5.xyz, r6.xxxx, r8.xyzx, r5.xyzx
movc r7.xyz, r6.xxxx, r7.xyzx, r6.wwww
mul r6.xzw, r6.zzzz, r5.xxyz
mad r5.xyz, r5.xyzx, cb0[10].xxxx, r7.xyzx
max r7.x, l(0.000100), cb8[6].w
log r7.x, r7.x
mul r7.x, r7.x, cb0[68].x
exp r7.x, r7.x
mul r7.x, r7.x, r7.x
mul r7.y, cb8[6].w, cb8[6].w
add r8.xyz, v4.xyzx, -cb3[0].xyzx
div r8.xyz, |r8.xyzx|, cb3[6].xyzx
add r9.xyz, l(-2.000000, -2.000000, -2.000000, 0.000000), cb3[3].xyzx
div r8.xyz, r8.xyzx, r9.xyzx
max r7.z, r8.y, r8.x
max r7.z, r8.z, r7.z
max r7.z, r7.z, l(0.510000)
log r7.z, r7.z
round_ni r7.z, r7.z
add r8.z, r7.z, l(1.000000)
lt r7.z, r8.z, cb3[8].x
exp r7.w, r8.z
mul r9.xyz, r7.wwww, cb3[6].xyzx
div r10.xyz, cb3[0].xyzx, r9.xyzx
round_ni r10.xyz, r10.xyzx
mad r9.xyz, -r10.xyzx, r9.xyzx, v4.xyzx
div r9.xyz, r9.xyzx, cb3[6].xyzx
div r9.xyz, r9.xyzx, cb3[3].xyzx
div r9.xyz, r9.xyzx, r7.wwww
mov r8.xy, l(0.500000,0.500000,0,0)
mad r8.xyz, r9.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r8.xyzx
add r7.w, r8.z, l(0.500000)
mul r8.xy, r8.xyxx, cb3[2].xyxx
mad r8.w, r7.w, cb3[2].z, cb3[9].x
add r8.xyz, r8.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
div r8.xyz, r8.xyzx, cb3[4].xyzx
mov r9.xy, cb8[4].zwzz
mov r9.z, l(0)
movc r8.xyz, r7.zzzz, r8.xyzx, r9.xyzx
sample_l_indexable(texture3d)(float,float,float,float) r10.xyzw, r8.xyzx, t16.xyzw, s5, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r11.xyzw, r8.xyzx, t17.xyzw, s5, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r12.xyzw, r8.xyzx, t18.xyzw, s5, l(0.000000)
mul r1.w, r1.w, cb3[15].x
mad_sat r1.w, r1.w, l(1.500000), cb3[15].y
lt r7.z, r1.w, l(1.000000)
if_nz r7.z
  sample_l_indexable(texture3d)(float,float,float,float) r13.xyzw, r9.xyzx, t16.xyzw, s5, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r14.xyzw, r9.xyzx, t17.xyzw, s5, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r9.xyzw, r9.xyzx, t18.xyzw, s5, l(0.000000)
  add r15.xyzw, r10.xyzw, -r13.xyzw
  mad r10.xyzw, r1.wwww, r15.xyzw, r13.xyzw
  add r13.xyzw, r11.xyzw, -r14.xyzw
  mad r11.xyzw, r1.wwww, r13.xyzw, r14.xyzw
  add r13.xyzw, -r9.xyzw, r12.xyzw
  mad r12.xyzw, r1.wwww, r13.xyzw, r9.xyzw
endif
mov r4.w, l(1.000000)
dp4 r9.x, r10.xyzw, r4.xyzw
dp4 r9.y, r11.xyzw, r4.xyzw
dp4 r9.z, r12.xyzw, r4.xyzw
max r9.xyz, r9.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r4.w, r8.xyzx, t19.yzwx, s4, l(0.000000)
add r4.w, r4.w, l(-1.000000)
mad r1.w, r1.w, r4.w, l(1.000000)
dp3_sat r4.w, cb0[46].xyzx, r4.xyzx
mul r7.xzw, r7.xxxx, cb0[45].xxyz
mul r7.xzw, r1.wwww, r7.xxzw
mul r7.xzw, r4.wwww, r7.xxzw
mad r7.xzw, r7.xxzw, l(0.318309873, 0.000000, 0.318309873, 0.318309873), r9.xxyz
add r1.w, r6.y, r6.y
mad r2.xyz, r4.xyzx, r1.wwww, -r2.xyzx
mul r1.w, r5.w, l(1.500000)
min r1.w, r1.w, l(1.000000)
mad r2.xyz, -v0.xyzx, r2.wwww, r2.xyzx
mad r2.xyz, r1.wwww, r2.xyzx, r4.xyzx
dp3 r1.w, r2.xyzx, r2.xyzx
rsq r1.w, r1.w
mul r8.xyz, r1.wwww, r2.xyzx
dp3 r2.x, r10.xyzx, r10.xyzx
rsq r2.x, r2.x
mul r2.xyw, r2.xxxx, r10.xyxz
dp3 r4.w, r11.xyzx, r11.xyzx
rsq r4.w, r4.w
mul r9.xyz, r4.wwww, r11.xyzx
dp3 r4.w, r12.xyzx, r12.xyzx
rsq r4.w, r4.w
mul r13.xyz, r4.wwww, r12.xyzx
mul r9.xyz, r9.xyzx, l(0.590000, 0.590000, 0.590000, 0.000000)
mad r2.xyw, r2.xyxw, l(0.300000, 0.300000, 0.000000, 0.300000), r9.xyxz
mad r2.xyw, r13.xyxz, l(0.110000, 0.110000, 0.000000, 0.110000), r2.xyxw
dp3 r4.w, r2.xywx, r2.xywx
rsq r4.w, r4.w
mul r2.xyw, r2.xyxw, r4.wwww
mul r9.xyz, r2.xywx, l(0.666666746, 0.666666746, 0.666666746, 0.000000)
mov r9.w, l(0.333333373)
dp4 r10.x, r10.xyzw, r9.xyzw
dp4 r10.y, r11.xyzw, r9.xyzw
dp4 r10.z, r12.xyzw, r9.xyzw
dp4 r4.w, r9.xyzw, r9.xyzw
div r9.xyz, r10.xyzx, r4.wwww
max r9.xyz, r9.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r1.xyz, r1.xyzx, r0.wwww, r2.xywx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx
dp3_sat r0.w, r1.xyzx, r4.xyzx
dp3_sat r4.x, r4.xyzx, r2.xywx
dp3_sat r1.x, r2.xywx, r1.xyzx
mad r1.y, -r5.w, l(0.900000), l(1.000000)
mul r1.y, r1.y, r1.y
mul r1.y, r1.y, r1.y
add r1.x, -r1.x, l(1.000000)
mad r1.z, cb0[10].x, l(0.840000), l(0.040000)
mul r2.x, r1.x, r1.x
mul r2.x, r2.x, r2.x
mul r2.y, r1.x, r2.x
mad r1.x, -r1.x, r2.x, l(1.000000)
div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
mad r1.x, r1.z, r2.y, r1.x
mad r1.z, r0.w, r1.y, -r0.w
mad r0.w, r1.z, r0.w, l(1.000000)
mul r0.w, r0.w, r0.w
div r0.w, r1.y, r0.w
mul r0.w, r0.w, r1.x
mul r0.w, r0.w, l(0.0397887304)
mul r1.xyz, r0.wwww, r9.xyzx
mul r1.xyz, r4.xxxx, r1.xyzx
add r0.w, -r5.w, l(1.000000)
sqrt r2.x, r0.w
mul r2.y, r2.x, l(8.000000)
max r2.w, r7.y, l(0.000100)
log r2.w, r2.w
mul r4.x, r2.w, cb0[59].x
exp r4.x, r4.x
add r4.y, r4.x, r6.y
log r4.y, r4.y
mul r4.y, r4.y, r5.w
exp r4.y, r4.y
add r4.y, r4.x, r4.y
add_sat r4.y, r4.y, l(-1.000000)
mad_sat r4.y, cb0[58].x, r4.y, cb0[58].y
add r4.y, -r4.x, r4.y
mad r4.x, r5.w, r4.y, r4.x
lt r4.y, l(-0.500000), cb0[64].x
add r9.xyz, -v4.xyzx, cb12[7].xyzx
dp3 r4.z, r9.xyzx, r9.xyzx
sqrt r4.z, r4.z
mad_sat r4.z, r4.z, cb0[61].x, cb0[61].y
add r4.w, -cb0[63].x, cb0[64].x
mad r4.z, r4.z, r4.w, cb0[63].x
movc r4.y, r4.y, r4.z, cb0[63].x
mad r8.w, r2.z, r1.w, l(1.000000)
dp3 r1.w, r8.xywx, r8.xywx
rsq r1.w, r1.w
mul r4.zw, r1.wwww, r8.xxxy
mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
sample_l_indexable(texture2d)(float,float,float,float) r9.xyz, r4.zwzz, t4.xyzw, s6, r2.y
mul r4.xzw, r4.xxxx, r9.xxyz
mul r9.xyz, r4.yyyy, r4.xzwx
mul r1.w, r2.x, cb8[25].w
sample_l_indexable(texturecube)(float,float,float,float) r10.xyzw, r8.xyzx, t25.xyzw, s7, r1.w
lt r1.w, cb8[29].w, l(0.500000)
mul r11.xyz, r10.xyzx, r10.xyzx
movc r10.xyz, r1.wwww, r11.xyzx, r10.xyzx
mul r11.xyz, v4.yyyy, cb8[33].xyzx
mad r11.xyz, cb8[32].xyzx, v4.xxxx, r11.xyzx
mad r11.xyz, cb8[34].xyzx, v4.zzzz, r11.xyzx
add r11.xyz, r11.xyzx, cb8[35].xyzx
mul r1.w, r2.w, cb0[56].x
exp r1.w, r1.w
add r2.y, r1.w, r6.y
log r2.y, r2.y
mul r2.y, r2.y, r5.w
exp r2.y, r2.y
add r2.y, r1.w, r2.y
add_sat r2.y, r2.y, l(-1.000000)
mad_sat r2.y, cb0[55].x, r2.y, cb0[55].y
add r2.y, -r1.w, r2.y
mad r1.w, r5.w, r2.y, r1.w
mul r2.y, r1.w, cb8[24].w
add r12.xyz, cb8[30].xyzx, cb8[31].xyzx
mul r2.yzw, r2.yyyy, r12.xxyz
mul r2.yzw, r2.yyzw, r10.xxyz
mov_sat r10.xyz, -r11.xyzx
mad_sat r10.xyz, r10.xyzx, cb8[22].xyzx, -cb8[24].xyzx
add r10.xyz, -r10.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mov_sat r12.xyz, r11.xyzx
mad_sat r12.xyz, r12.xyzx, cb8[23].xyzx, -cb8[25].xyzx
add r12.xyz, -r12.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r7.y, r12.y, r12.x
mul r7.y, r12.z, r7.y
mul r7.y, r10.x, r7.y
mul r7.y, r10.y, r7.y
mul r7.y, r10.z, r7.y
lt r8.w, l(0.000000), cb8[27].w
log r10.xyz, |r11.xyzx|
mul r10.xyz, r10.xyzx, cb8[27].wwww
exp r10.xyz, r10.xyzx
dp3 r9.w, r10.xyzx, cb8[27].xyzx
log r9.w, r9.w
mul r9.w, r9.w, cb8[28].x
exp r9.w, r9.w
mad_sat r9.w, cb8[28].y, r9.w, cb8[28].z
add r9.w, -r9.w, l(1.000000)
mul r9.w, r7.y, r9.w
movc r7.y, r8.w, r9.w, r7.y
mul r7.y, r7.y, r10.w
lt r8.w, l(0.000000), cb8[29].y
mul r10.xyz, r2.yzwy, cb0[65].xxxx
mul r2.yzw, r2.yyzw, cb0[62].xxxx
movc r2.yzw, r8.wwww, r10.xxyz, r2.yyzw
mul r7.y, r7.y, cb8[28].w
mad r2.yzw, -r4.xxzw, r4.yyyy, r2.yyzw
mad r2.yzw, r7.yyyy, r2.yyzw, r9.xxyz
mul r2.x, r2.x, cb8[11].w
sample_l_indexable(texturecube)(float,float,float,float) r4.xyzw, r8.xyzx, t24.xyzw, s7, r2.x
lt r2.x, cb8[15].w, l(0.500000)
mul r8.xyz, r4.xyzx, r4.xyzx
movc r4.xyz, r2.xxxx, r8.xyzx, r4.xyzx
mul r8.xyz, v4.yyyy, cb8[19].xyzx
mad r8.xyz, cb8[18].xyzx, v4.xxxx, r8.xyzx
mad r8.xyz, cb8[20].xyzx, v4.zzzz, r8.xyzx
add r8.xyz, r8.xyzx, cb8[21].xyzx
mul r1.w, r1.w, cb8[10].w
add r9.xyz, cb8[16].xyzx, cb8[17].xyzx
mul r9.xyz, r1.wwww, r9.xyzx
mul r4.xyz, r4.xyzx, r9.xyzx
mov_sat r9.xyz, -r8.xyzx
mad_sat r9.xyz, r9.xyzx, cb8[8].xyzx, -cb8[10].xyzx
add r9.xyz, -r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mov_sat r10.xyz, r8.xyzx
mad_sat r10.xyz, r10.xyzx, cb8[9].xyzx, -cb8[11].xyzx
add r10.xyz, -r10.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r1.w, r10.y, r10.x
mul r1.w, r10.z, r1.w
mul r1.w, r9.x, r1.w
mul r1.w, r9.y, r1.w
mul r1.w, r9.z, r1.w
lt r2.x, l(0.000000), cb8[13].w
log r8.xyz, |r8.xyzx|
mul r8.xyz, r8.xyzx, cb8[13].wwww
exp r8.xyz, r8.xyzx
dp3 r7.y, r8.xyzx, cb8[13].xyzx
log r7.y, r7.y
mul r7.y, r7.y, cb8[14].x
exp r7.y, r7.y
mad_sat r7.y, cb8[14].y, r7.y, cb8[14].z
add r7.y, -r7.y, l(1.000000)
mul r7.y, r1.w, r7.y
movc r1.w, r2.x, r7.y, r1.w
mul r1.w, r1.w, r4.w
lt r2.x, l(0.000000), cb8[15].y
mul r8.xyz, r4.xyzx, cb0[65].xxxx
mul r4.xyz, r4.xyzx, cb0[62].xxxx
movc r4.xyz, r2.xxxx, r8.xyzx, r4.xyzx
mul r1.w, r1.w, cb8[14].w
add r4.xyz, -r2.yzwy, r4.xyzx
mad r2.xyz, r1.wwww, r4.xyzx, r2.yzwy
add_sat r1.w, -r6.y, l(1.000000)
mul r2.w, r1.w, r1.w
mul r2.w, r2.w, r2.w
mul r1.w, r1.w, r2.w
add r0.w, r0.w, r0.w
min r0.w, r0.w, l(1.000000)
add r0.w, -r0.w, l(1.000000)
mul r2.w, r0.w, r1.w
mad r4.x, r5.w, l(0.600000), l(0.400000)
mad r0.w, -r1.w, r0.w, l(1.000000)
mul r0.w, r0.w, r4.x
mad r4.xyz, r5.xyzx, r0.wwww, r2.wwww
max r0.w, r3.w, l(0.001000)
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
mul r4.xyz, r0.wwww, r4.xyzx
mul r1.xyz, r0.wwww, r1.xyzx
mul r2.xyz, r2.xyzx, r4.xyzx
mad r1.xyz, r5.xyzx, r1.xyzx, r2.xyzx
mad r1.xyz, r6.xzwx, r7.xzwx, r1.xyzx
mul r1.xyz, r1.xyzx, cb13[1].xxxx
mul r0.w, l(0.750000), cb0[7].x
max r0.w, r0.w, l(0.000000)
dp3 r1.w, r3.xyzx, r3.xyzx
sqrt r1.w, r1.w
mad_sat r2.x, r1.w, cb0[3].x, cb0[3].y
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.xyxx, t11.xyzw, s2
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.xyxx, t13.xyzw, s2
add r4.xyzw, r4.xyzw, -r5.xyzw
mad r2.xyzw, r2.xxxx, r4.xyzw, r5.xyzw
div r3.x, r3.z, r1.w
add r0.w, -r0.w, r1.w
mul_sat r0.w, r0.w, l(0.000020)
sqrt r4.x, r0.w
mad r4.y, r3.x, l(0.500000), l(0.500000)
sample_l_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t15.xyzw, s3, l(0.000000)
mul r0.w, cb0[5].x, cb13[1].x
mad r3.x, r4.w, cb0[6].x, -r4.w
mad r2.w, r2.w, r3.x, r2.w
mul r2.w, r0.w, r2.w
mad r0.w, -r0.w, r4.w, r0.w
mul r2.xyz, r0.wwww, r2.xyzx
mad r2.xyz, cb0[4].xyzx, r2.wwww, r2.xyzx
mul r0.w, r1.w, l(0.015625)
min r0.w, r0.w, l(1.000000)
sqrt r0.z, r0.w
sample_l_indexable(texture3d)(float,float,float,float) r0.z, r0.xyzx, t21.yzxw, s1, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.xyxx, t20.xyzw, s1, l(0.000000)
add r5.xyzw, r5.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
mad r0.xyzw, r0.zzzz, r5.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
mul r1.xyz, r1.xyzx, r4.xyzx
mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
add r0.xyz, r2.xyzx, r0.xyzx
mul o0.xyz, r3.wwww, r0.xyzx
mov o0.w, r3.w
ret
// Approximately 0 instruction slots used
