//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:53:57 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float
// TEXCOORD                 4      w        1     NONE   float      w
// TEXCOORD                 2   xyz         2     NONE   float
// TEXCOORD                 3   xyzw        3     NONE   float   x zw
// SV_POSITION              0   xyzw        4      POS   float   xy
// SV_isFrontFace           0   x           5    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb12[13], immediateIndexed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.w
dcl_input_ps linear v3.xzw
dcl_input_ps_siv linear noperspective v4.xy, position
dcl_output o0.xyzw
dcl_temps 2
sample_indexable(texture2d)(float,float,float,float) r0.x, v0.xyxx, t1.xyzw, s1
log r0.y, r0.x
mul r0.y, r0.y, l(2.200000)
exp r0.y, r0.y
mul r0.x, r0.x, r0.y
mul r0.x, r0.x, v3.w
add r0.y, v3.x, l(-0.500000)
mul_sat r0.y, r0.y, l(0.500000)
mul_sat r0.x, r0.y, r0.x
mul_sat r0.x, r0.x, v0.z
mul r0.yz, v4.xxyx, cb12[12].zzwz
mul r0.yz, r0.yyzy, cb12[12].xxyx
ftoi r1.xy, r0.yzyy
mov r1.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.y, r1.xyzw, t0.xyzw
add r0.y, r0.y, -v0.w
mul r0.z, v3.z, l(0.500000)
div_sat r0.y, r0.y, r0.z
add r0.y, -r0.y, l(1.000000)
add r0.y, -r0.y, l(1.000000)
mul r0.x, r0.y, r0.x
mad r1.xyzw, v1.wwww, l(2.000000, 0.065002, 2.000000, 0.065002), l(-1.000000, -1.000000, -1.000000, -1.000000)
mul r1.xyzw, r1.xyzw, l(0.020000, 0.020000, 0.020000, 0.020000)
mul r0.xyzw, r0.xxxx, r1.xyzw
mul_sat o0.xyzw, r0.xyzw, l(1.000000, 1.000000, -1.000000, -1.000000)
ret
// Approximately 0 instruction slots used
