//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:08 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyzw        1     NONE   float   xyz
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xy
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// SV_POSITION              0   xyzw        5      POS   float
// SV_isFrontFace           0   x           6    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[25], immediateIndexed
dcl_constantbuffer cb12[8], immediateIndexed
dcl_constantbuffer cb7[63], dynamicIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_input_ps linear v4.xyz
dcl_input_ps_sgv v6.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_temps 14
add r0.xyz, -v4.xyzx, cb12[7].xyzx
dp3 r0.x, r0.xyzx, r0.xyzx
sqrt r0.x, r0.x
mad r0.yz, v3.xxyx, cb0[23].xxyx, cb0[23].zzwz
sample_indexable(texture2d)(float,float,float,float) r1.xyz, v3.xyxx, t3.xyzw, s5
add r0.w, -r1.z, r1.y
lt r0.w, r0.w, l(0.00470588217)
movc r0.w, r0.w, r1.y, r1.z
deriv_rtx_coarse r2.xy, r1.xyxx
deriv_rtx_coarse r2.z, r0.w
deriv_rty_coarse r3.xy, r1.xyxx
deriv_rty_coarse r3.z, r0.w
mul r1.zw, r2.yyyz, r2.xxxx
mul r2.xy, r3.yzyy, r3.xxxx
lt r2.zw, |r2.xxxy|, |r1.zzzw|
movc r1.zw, r2.zzzw, r1.zzzw, r2.xxxy
add r2.x, r1.x, l(-0.500000)
add r2.y, r1.y, r1.x
add r2.y, r2.y, l(-1.000000)
lt r2.xy, |r2.xyxx|, l(0.00470588217, 0.00588235306, 0.000000, 0.000000)
lt r1.zw, r1.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
and r1.z, r1.z, r2.y
add r2.y, -r1.y, l(1.000000)
movc r1.z, r1.z, r2.y, r1.x
add r2.y, r0.w, r1.z
add r2.y, r2.y, l(-1.000000)
lt r2.y, |r2.y|, l(0.00588235306)
and r1.w, r1.w, r2.y
add r2.y, -r0.w, l(1.000000)
movc r1.z, r1.w, r2.y, r1.z
movc r1.x, r2.x, r1.z, r1.x
ge r0.w, r0.w, l(0.500000)
if_nz r0.w
  mad r1.zw, r0.yyyz, cb7[6].xxxy, cb7[6].zzzw
  mad r2.xy, r0.yzyy, cb7[7].xyxx, cb7[7].zwzz
  sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.zwzz, t8.wxyz, s1
  sample_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t9.xyzw, s1
  mad r1.zw, r2.xxxy, cb7[8].xxxx, cb7[8].yyyy
  add_sat r0.w, r2.z, cb7[8].z
  mov r2.x, l(4)
else
  ge r1.y, r1.y, l(0.500000)
  if_nz r1.y
    mad r2.yz, r0.yyzy, cb7[3].xxyx, cb7[3].zzwz
    mad r4.xy, r0.yzyy, cb7[4].xyxx, cb7[4].zwzz
    sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.yzyy, t6.wxyz, s1
    sample_indexable(texture2d)(float,float,float,float) r2.yzw, r4.xyxx, t7.wxyz, s1
    mad r1.zw, r2.yyyz, cb7[5].xxxx, cb7[5].yyyy
    add_sat r0.w, r2.w, cb7[5].z
    mov r2.x, l(2)
  else
    mad r2.yz, r0.yyzy, cb7[0].xxyx, cb7[0].zzwz
    mad r0.yz, r0.yyzy, cb7[1].xxyx, cb7[1].zzwz
    sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.yzyy, t4.wxyz, s1
    sample_indexable(texture2d)(float,float,float,float) r2.yzw, r0.yzyy, t5.wxyz, s1
    mad r1.zw, r2.yyyz, cb7[2].xxxx, cb7[2].yyyy
    add_sat r0.w, r2.w, cb7[2].z
    mov r2.x, l(0)
  endif
endif
ge r0.y, r1.x, l(0.500000)
iadd r0.z, r2.x, l(1)
movc r0.y, r0.y, r0.z, r2.x
imul null, r0.y, r0.y, l(9)
mov_sat r2.xyzw, cb7[r0.y + 11].xyzw
mov_sat r1.xy, cb7[r0.y + 12].yzyy
mov_sat r4.xyzw, cb7[r0.y + 17].xyzw
sample_indexable(texture2d)(float,float,float,float) r5.xyz, v3.xyxx, t0.xyzw, s2
sample_indexable(texture2d)(float,float,float,float) r6.xy, v3.xyxx, t1.xyzw, s3
mad r6.xy, r6.xyxx, cb0[24].xxxx, cb0[24].yyyy
sample_indexable(texture2d)(float,float,float,float) r7.xyzw, v3.xyxx, t2.xyzw, s4
ge r0.z, r7.w, l(0.156862751)
and r6.z, r0.z, l(0x3f800000)
add r8.xyz, r7.ywzy, l(-0.250000, -0.188235298, -0.156862751, 0.000000)
mul_sat r8.yz, r8.yyzy, l(0.000000, 1.231884, 1.18604648, 0.000000)
mul_sat r9.xyz, r7.zwyz, l(7.968750, 7.968750, 4.000000, 0.000000)
movc r6.w, v6.x, l(1.000000), l(-1.000000)
mad_sat r7.z, cb7[r0.y + 15].y, r8.y, cb7[r0.y + 15].x
mad_sat r7.z, cb7[r0.y + 15].w, r7.z, cb7[r0.y + 15].z
mad_sat r7.w, r7.y, cb0[2].x, cb0[2].y
mul_sat r7.w, r7.w, cb0[3].x
add r8.y, -r7.w, l(1.000000)
mad r8.w, r9.y, cb0[4].x, cb0[4].y
mul r10.y, r8.w, r8.y
add r8.y, l(128.500000), cb0[5].x
mul r8.y, r8.y, l(0.00390625000)
ge r8.w, l(0.050000), r10.y
movc r8.y, r8.w, r8.y, l(-1.000000)
mad_sat r7.w, r7.w, cb0[22].x, cb0[22].y
add r11.xyzw, -cb0[20].xyzw, cb0[21].xyzw
mad_sat r11.xyzw, r7.wwww, r11.xyzw, cb0[20].xyzw
mul r12.xyzw, r11.xyzw, l(4.000000, 4.000000, 4.000000, 4.000000)
min r12.xyzw, r12.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mov r5.w, r7.y
add r11.xyzw, r11.xyzw, l(-0.250000, -0.250000, -0.250000, -0.250000)
max r11.xyzw, r11.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r11.xyzw, r5.xyzw, r12.xyzw, r11.xyzw
mul_sat r12.xyz, r3.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r3.yzw, r3.yyzw, l(0.000000, -0.250000, -0.250000, -0.250000)
mad_sat r13.xyz, cb7[r0.y + 9].xyzx, r12.xyzx, r3.yzwy
add r13.xyz, r13.xyzx, -cb7[r0.y + 9].xyzx
mad r13.xyz, r2.xxxx, r13.xyzx, cb7[r0.y + 9].xyzx
mad_sat r2.x, cb7[r0.y + 13].y, r7.y, cb7[r0.y + 13].x
mad_sat r2.x, cb7[r0.y + 13].w, r2.x, cb7[r0.y + 13].z
mov_sat r8.x, r8.x
mad_sat r3.x, r3.x, r9.z, r8.x
mad_sat r5.w, cb7[r0.y + 13].y, r3.x, cb7[r0.y + 13].x
mad_sat r5.w, cb7[r0.y + 13].w, r5.w, cb7[r0.y + 13].z
add r5.w, -r2.x, r5.w
mad r2.x, r2.z, r5.w, r2.x
mul_sat r9.yzw, r5.xxyz, l(0.000000, 4.000000, 4.000000, 4.000000)
add_sat r5.xyz, r5.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad_sat r13.xyz, r13.xyzx, r9.yzwy, r5.xyzx
mad r8.xw, r1.zzzw, r2.yyyy, r6.xxxy
add r0.w, r0.w, l(-1.000000)
mad r2.y, r2.y, r0.w, l(1.000000)
mad_sat r3.yzw, cb7[r0.y + 14].xxyz, r12.xxyz, r3.yyzw
add r3.yzw, r3.yyzw, -cb7[r0.y + 14].xxyz
mad r3.yzw, r4.xxxx, r3.yyzw, cb7[r0.y + 14].xxyz
mad_sat r3.yzw, r3.yyzw, r9.yyzw, r5.xxyz
mad_sat r2.z, cb7[r0.y + 16].y, r7.y, cb7[r0.y + 16].x
mad_sat r2.z, cb7[r0.y + 16].w, r2.z, cb7[r0.y + 16].z
mad_sat r3.x, cb7[r0.y + 16].y, r3.x, cb7[r0.y + 16].x
mad_sat r3.x, cb7[r0.y + 16].w, r3.x, cb7[r0.y + 16].z
add r3.x, -r2.z, r3.x
mad r2.z, r4.z, r3.x, r2.z
mad r1.zw, r1.zzzw, r4.yyyy, r6.xxxy
mad r0.w, r4.y, r0.w, l(1.000000)
add r4.xyz, -r3.yzwy, r13.xyzx
mad r3.xyz, r7.zzzz, r4.xyzx, r3.yzwy
add r4.xy, -r1.zwzz, r8.xwxx
mad r1.zw, r7.zzzz, r4.xxxy, r1.zzzw
add r2.x, -r2.z, r2.x
mad r2.x, r7.z, r2.x, r2.z
add r2.z, r2.w, -r4.w
mad r4.y, r7.z, r2.z, r4.w
add r2.y, -r0.w, r2.y
mad r0.w, r7.z, r2.y, r0.w
add r2.y, l(128.500000), cb7[r0.y + 12].x
mul r2.y, r2.y, l(0.00390625000)
ge r2.z, l(0.050000), r2.w
movc r2.y, r2.z, r2.y, l(-1.000000)
min r0.w, r0.w, r2.x
lt r2.x, l(0.000100), r1.x
mul r2.z, r1.x, l(-2.000000)
mad r1.x, r1.x, l(-2.000000), l(-0.200000)
mul r1.x, r0.w, r1.x
mad r1.x, r1.x, l(-5.002501), r2.z
min r1.x, r0.w, r1.x
movc r4.x, r2.x, r1.x, r0.w
add r2.xzw, -r11.xxyz, r3.xxyz
mad r2.xzw, r6.zzzz, r2.xxzw, r11.xxyz
add r1.xz, -r6.xxyx, r1.zzwz
mad r3.xy, r6.zzzz, r1.xzxx, r6.xyxx
mov r10.x, r11.w
add r1.xz, -r10.xxyx, r4.xxyx
mad r1.xz, r6.zzzz, r1.xxzx, r10.xxyx
mul r0.w, r1.y, r6.z
movc o0.w, r0.z, r2.y, r8.y
ne r0.z, l(0.000000, 0.000000, 0.000000, 0.000000), cb7[r0.y + 10].w
and r4.xyz, r0.zzzz, cb7[r0.y + 10].xyzx
mul r0.y, r8.z, cb0[19].x
mul r4.xyz, r4.xyzx, r0.yyyy
mul r4.xyz, r6.zzzz, r4.xyzx
mul r5.xyz, r7.zzzz, r4.xyzx
mad r4.xyz, r4.xyzx, r7.zzzz, r2.xzwx
max r0.y, r4.y, r4.x
max r0.y, r4.z, r0.y
add_sat r0.y, r0.y, l(-1.000000)
add r0.y, -r0.y, l(1.000000)
mad r2.xyz, r2.xzwx, r0.yyyy, r5.xyzx
max r0.y, r2.y, r2.x
max r0.y, r2.z, r0.y
max r0.y, r0.y, l(1.000000)
div r2.xyz, r2.xyzx, r0.yyyy
max r0.y, r5.y, r5.x
max r0.y, r5.z, r0.y
dp2 r0.z, r3.xyxx, r3.xyxx
add r0.z, -r0.z, l(1.000000)
max r0.z, r0.z, l(0.000000)
sqrt r3.z, r0.z
dp3 r0.z, r3.xyzx, r3.xyzx
rsq r0.z, r0.z
mul r3.xyz, r0.zzzz, r3.xyzx
mul r4.xyz, r6.wwww, v0.xyzx
mul r5.xyz, r3.yyyy, v2.xyzx
mad r3.xyw, v1.xyxz, r3.xxxx, r5.xyxz
mad r3.xyz, r4.xyzx, r3.zzzz, r3.xywx
dp3 r0.z, r3.xyzx, r3.xyzx
rsq r0.z, r0.z
mul r3.xyz, r0.zzzz, r3.xyzx
ne r0.z, l(0.000000), cb0[7].x
if_nz r0.z
  deriv_rtx_coarse r1.yw, v3.xxxy
  dp2 r0.z, r1.ywyy, r1.ywyy
  sqrt r0.z, r0.z
  deriv_rty_coarse r1.yw, v3.xxxy
  dp2 r1.y, r1.ywyy, r1.ywyy
  sqrt r1.y, r1.y
  max r0.z, r0.z, r1.y
  div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
  log r0.z, r0.z
  round_ni r1.y, r0.z
  exp r1.y, r1.y
  round_pi r1.w, r0.z
  exp r1.w, r1.w
  mul r5.xy, r1.yyyy, v3.xyxx
  round_ni r5.xy, r5.xyxx
  dp2 r1.y, r5.xyxx, l(17.000000, 0.100000, 0.000000, 0.000000)
  sincos r1.y, null, r1.y
  mul r1.y, r1.y, l(10000.000000)
  mad r2.w, r5.y, l(13.000000), r5.x
  sincos r2.w, null, r2.w
  add r2.w, |r2.w|, l(0.100000)
  mul r1.y, r1.y, r2.w
  mul r5.xy, r1.wwww, v3.xyxx
  round_ni r5.xy, r5.xyxx
  dp2 r1.w, r5.xyxx, l(17.000000, 0.100000, 0.000000, 0.000000)
  sincos r1.w, null, r1.w
  mul r1.w, r1.w, l(10000.000000)
  mad r2.w, r5.y, l(13.000000), r5.x
  sincos r2.w, null, r2.w
  add r2.w, |r2.w|, l(0.100000)
  mul r1.w, r1.w, r2.w
  frc r1.yw, r1.yyyw
  frc r0.z, r0.z
  add r1.w, -r1.y, r1.w
  mad r1.y, r0.z, r1.w, r1.y
  add r1.w, -r0.z, l(1.000000)
  min r0.z, r0.z, r1.w
  mul r1.w, r1.y, r1.y
  add r2.w, r0.z, r0.z
  add r3.w, -r0.z, l(1.000000)
  mul r2.w, r2.w, r3.w
  div r1.w, r1.w, r2.w
  mad r4.w, -r0.z, l(0.500000), r1.y
  div r4.w, r4.w, r3.w
  add r5.x, -r1.y, l(1.000000)
  mul r5.x, r5.x, r5.x
  div r2.w, r5.x, r2.w
  add r2.w, -r2.w, l(1.000000)
  lt r3.w, r1.y, r3.w
  lt r0.z, r1.y, r0.z
  movc r0.z, r0.z, r1.w, r4.w
  movc r0.z, r3.w, r0.z, r2.w
  ge r1.y, l(0.500000), cb0[6].x
  add r1.w, cb0[6].x, cb0[6].x
  mad r1.w, r0.z, -r1.w, r1.w
  mad r2.w, cb0[6].x, l(2.000000), l(-2.000000)
  mad r0.z, r0.z, r2.w, l(1.000000)
  movc r0.z, r1.y, r1.w, r0.z
else
  mov r0.z, cb0[6].x
endif
add r0.z, -r0.z, r9.x
lt r0.z, r0.z, l(0.000000)
discard_nz r0.z
mov_sat r0.z, cb0[17].x
dp3 r1.y, r4.xyzx, r4.xyzx
rsq r1.y, r1.y
mul r4.xyz, r1.yyyy, r4.xyzx
dp3 r1.y, cb0[10].xyzx, r4.xyzx
add r1.w, -cb0[8].x, cb0[9].x
mad_sat r1.y, r1.y, r1.w, cb0[8].x
add r1.w, v4.z, -cb0[11].z
mul r1.w, r1.w, cb0[12].x
max r1.w, r1.w, l(0.000000)
log r1.w, r1.w
mul r1.w, r1.w, cb0[13].x
exp r1.w, r1.w
mul_sat r1.w, r1.w, cb0[14].x
mul r1.y, r1.w, r1.y
mad_sat r0.x, r0.x, cb0[15].x, cb0[15].y
mul r0.x, r0.x, r1.y
dp3 r1.y, r2.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
max r1.y, r1.y, l(0.000100)
log r1.y, r1.y
mul r1.y, r1.y, -cb0[16].x
exp r1.y, r1.y
mul r0.x, r0.x, r1.y
add o2.w, r0.z, v0.w
mad r0.x, r0.x, cb0[18].x, r0.y
mad r0.y, r1.x, l(0.125000), l(0.375000)
mad_sat o1.xyz, r3.xyzx, r0.yyyy, l(0.500000, 0.500000, 0.500000, 0.000000)
add r0.x, r0.x, l(0.00781250000)
log r0.x, r0.x
mad_sat r0.x, r0.x, l(0.0769230798), l(0.538461566)
mov_sat r7.x, r7.x
add r0.x, r0.x, r7.x
mul o2.yz, r0.xxwx, l(0.000000, 0.500000, 0.800000, 0.000000)
mov o0.xyz, r2.xyzx
mov o1.w, l(0)
mov o2.x, r1.z
ret
// Approximately 0 instruction slots used
