//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:02 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyz
// TEXCOORD                 1   xyzw        1     NONE   float
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xy
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// TEXCOORD                 8   xyzw        5     NONE   float   x
// SV_POSITION              0   xyzw        6      POS   float   xy
// SV_isFrontFace           0   x           7    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[55], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[15], immediateIndexed
dcl_constantbuffer cb3[16], immediateIndexed
dcl_constantbuffer cb8[36], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texturecube (float,float,float,float) t24
dcl_resource_texturecube (float,float,float,float) t25
dcl_input_ps linear v0.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.x
dcl_input_ps_siv linear noperspective v6.xy, position
dcl_output o0.xyzw
dcl_temps 15
mul r0.xy, v6.xyxx, cb12[12].zwzz
add r1.xyz, -v4.xyzx, cb12[14].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r1.xyzx
add r3.xyz, v4.xyzx, -cb12[14].xyzx
dp3 r1.w, -cb12[6].xyzx, r3.xyzx
dp3 r2.w, v0.xyzx, v0.xyzx
rsq r2.w, r2.w
mul r4.xyz, r2.wwww, v0.xyzx
mad r5.xy, v3.xyxx, cb0[13].xyxx, cb0[13].zwzz
sample_indexable(texture2d)(float,float,float,float) r3.w, r5.xyxx, t5.yzwx, s4
mov_sat r3.w, r3.w
mad r5.xyzw, cb0[15].xyzw, r3.wwww, cb0[14].xyzw
mad r5.xyzw, r5.xyzw, cb0[16].xxxx, cb0[16].yyyy
dp2 r3.w, cb0[10].xyxx, v3.xyxx
add r6.x, r3.w, cb0[10].z
dp2 r3.w, cb0[11].xyxx, v3.xyxx
add r6.y, r3.w, cb0[11].z
sample_indexable(texture2d)(float,float,float,float) r3.w, r6.xyxx, t4.yzwx, s4
mad_sat r3.w, r3.w, cb0[12].x, cb0[12].y
add r6.xyzw, -cb0[17].xyzw, cb0[18].xyzw
mad_sat r6.xyzw, r3.wwww, r6.xyzw, cb0[17].xyzw
add r7.w, r6.w, -v5.x
mov r6.w, r5.w
mov r7.xyz, l(0,0,0,0)
add r6.xyzw, r7.xyzw, r6.xyzw
mov r5.w, l(1.000000)
add_sat r5.xyzw, r6.xyzw, r5.xyzw
add r6.x, -cb0[8].x, cb0[9].x
mad_sat r3.w, r3.w, r6.x, cb0[8].x
mad r6.xyz, r1.xyzx, r0.wwww, cb0[19].xyzx
dp3 r6.w, r6.xyzx, r6.xyzx
rsq r6.w, r6.w
mul r6.xyz, r6.wwww, r6.xyzx
mad r7.xyz, cb0[23].xxxx, v0.xyzx, v2.xyzx
dp3 r6.w, r7.xyzx, r7.xyzx
rsq r6.w, r6.w
mul r7.xyz, r6.wwww, r7.xyzx
mad r8.xyz, cb0[27].xxxx, v0.xyzx, v2.xyzx
dp3 r6.w, r8.xyzx, r8.xyzx
rsq r6.w, r6.w
mul r8.xyz, r6.wwww, r8.xyzx
dp3 r6.w, r7.xyzx, r6.xyzx
mad r6.w, -r6.w, r6.w, l(1.000000)
sqrt r6.w, r6.w
log r6.w, r6.w
mul r6.w, r6.w, cb0[21].x
exp r6.w, r6.w
dp3 r6.x, r8.xyzx, r6.xyzx
mad r6.x, -r6.x, r6.x, l(1.000000)
sqrt r6.x, r6.x
log r6.x, r6.x
mul r6.x, r6.x, cb0[25].x
exp r6.x, r6.x
mul r6.y, r6.w, cb0[22].x
mul r6.x, r6.x, cb0[26].x
mul_sat r6.yzw, r6.yyyy, cb0[20].xxyz
mul_sat r7.xyz, r6.xxxx, cb0[24].xyzx
add r6.xyz, r6.yzwy, r7.xyzx
mad r5.xyz, r5.xyzx, cb0[54].xxxx, r6.xyzx
max r6.x, l(0.000100), cb8[6].w
log r6.x, r6.x
mul r6.x, r6.x, cb0[52].x
exp r6.x, r6.x
mul r6.x, r6.x, r6.x
mul r6.y, cb8[6].w, cb8[6].w
add r7.xyz, v4.xyzx, -cb3[0].xyzx
div r7.xyz, |r7.xyzx|, cb3[6].xyzx
add r8.xyz, l(-2.000000, -2.000000, -2.000000, 0.000000), cb3[3].xyzx
div r7.xyz, r7.xyzx, r8.xyzx
max r6.z, r7.y, r7.x
max r6.z, r7.z, r6.z
max r6.z, r6.z, l(0.510000)
log r6.z, r6.z
round_ni r6.z, r6.z
add r7.z, r6.z, l(1.000000)
lt r6.z, r7.z, cb3[8].x
exp r6.w, r7.z
mul r8.xyz, r6.wwww, cb3[6].xyzx
div r9.xyz, cb3[0].xyzx, r8.xyzx
round_ni r9.xyz, r9.xyzx
mad r8.xyz, -r9.xyzx, r8.xyzx, v4.xyzx
div r8.xyz, r8.xyzx, cb3[6].xyzx
div r8.xyz, r8.xyzx, cb3[3].xyzx
div r8.xyz, r8.xyzx, r6.wwww
mov r7.xy, l(0.500000,0.500000,0,0)
mad r7.xyz, r8.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r7.xyzx
add r6.w, r7.z, l(0.500000)
mul r7.xy, r7.xyxx, cb3[2].xyxx
mad r7.w, r6.w, cb3[2].z, cb3[9].x
add r7.xyz, r7.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
div r7.xyz, r7.xyzx, cb3[4].xyzx
mov r8.xy, cb8[4].zwzz
mov r8.z, l(0)
movc r7.xyz, r6.zzzz, r7.xyzx, r8.xyzx
sample_l_indexable(texture3d)(float,float,float,float) r9.xyzw, r7.xyzx, t16.xyzw, s6, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r10.xyzw, r7.xyzx, t17.xyzw, s6, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r11.xyzw, r7.xyzx, t18.xyzw, s6, l(0.000000)
mul r1.w, r1.w, cb3[15].x
mad_sat r1.w, r1.w, l(1.500000), cb3[15].y
lt r6.z, r1.w, l(1.000000)
if_nz r6.z
  sample_l_indexable(texture3d)(float,float,float,float) r12.xyzw, r8.xyzx, t16.xyzw, s6, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r13.xyzw, r8.xyzx, t17.xyzw, s6, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r8.xyzw, r8.xyzx, t18.xyzw, s6, l(0.000000)
  add r14.xyzw, r9.xyzw, -r12.xyzw
  mad r9.xyzw, r1.wwww, r14.xyzw, r12.xyzw
  add r12.xyzw, r10.xyzw, -r13.xyzw
  mad r10.xyzw, r1.wwww, r12.xyzw, r13.xyzw
  add r12.xyzw, -r8.xyzw, r11.xyzw
  mad r11.xyzw, r1.wwww, r12.xyzw, r8.xyzw
endif
mov r4.w, l(1.000000)
dp4 r8.x, r9.xyzw, r4.xyzw
dp4 r8.y, r10.xyzw, r4.xyzw
dp4 r8.z, r11.xyzw, r4.xyzw
max r8.xyz, r8.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r4.w, r7.xyzx, t19.yzwx, s5, l(0.000000)
add r4.w, r4.w, l(-1.000000)
mad r1.w, r1.w, r4.w, l(1.000000)
dp3_sat r4.w, cb0[30].xyzx, r4.xyzx
mul r6.xzw, r6.xxxx, cb0[29].xxyz
mul r6.xzw, r1.wwww, r6.xxzw
mul r6.xzw, r4.wwww, r6.xxzw
mad r6.xzw, r6.xxzw, l(0.318309873, 0.000000, 0.318309873, 0.318309873), r8.xxyz
dp3 r1.w, r4.xyzx, r2.xyzx
add r4.w, r1.w, r1.w
mad r2.xyz, r4.xyzx, r4.wwww, -r2.xyzx
mul r4.w, r3.w, l(1.500000)
min r4.w, r4.w, l(1.000000)
mad r2.xyz, -v0.xyzx, r2.wwww, r2.xyzx
mad r2.xyz, r4.wwww, r2.xyzx, r4.xyzx
dp3 r2.w, r2.xyzx, r2.xyzx
rsq r2.w, r2.w
mul r7.xyz, r2.wwww, r2.xyzx
dp3 r2.x, r9.xyzx, r9.xyzx
rsq r2.x, r2.x
mul r8.xyz, r2.xxxx, r9.xyzx
dp3 r2.x, r10.xyzx, r10.xyzx
rsq r2.x, r2.x
mul r12.xyz, r2.xxxx, r10.xyzx
dp3 r2.x, r11.xyzx, r11.xyzx
rsq r2.x, r2.x
mul r13.xyz, r2.xxxx, r11.xyzx
mul r12.xyz, r12.xyzx, l(0.590000, 0.590000, 0.590000, 0.000000)
mad r8.xyz, r8.xyzx, l(0.300000, 0.300000, 0.300000, 0.000000), r12.xyzx
mad r8.xyz, r13.xyzx, l(0.110000, 0.110000, 0.110000, 0.000000), r8.xyzx
dp3 r2.x, r8.xyzx, r8.xyzx
rsq r2.x, r2.x
mul r8.xyz, r2.xxxx, r8.xyzx
mul r12.xyz, r8.xyzx, l(0.666666746, 0.666666746, 0.666666746, 0.000000)
mov r12.w, l(0.333333373)
dp4 r9.x, r9.xyzw, r12.xyzw
dp4 r9.y, r10.xyzw, r12.xyzw
dp4 r9.z, r11.xyzw, r12.xyzw
dp4 r2.x, r12.xyzw, r12.xyzw
div r9.xyz, r9.xyzx, r2.xxxx
max r9.xyz, r9.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r1.xyz, r1.xyzx, r0.wwww, r8.xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx
dp3_sat r0.w, r1.xyzx, r4.xyzx
dp3_sat r2.x, r4.xyzx, r8.xyzx
dp3_sat r1.x, r8.xyzx, r1.xyzx
mad r1.y, -r3.w, l(0.900000), l(1.000000)
mul r1.y, r1.y, r1.y
add r1.x, -r1.x, l(1.000000)
mul r1.yz, r1.yyxy, r1.yyxy
mul r1.z, r1.z, r1.z
mul r2.y, r1.z, r1.x
mad r1.x, -r1.x, r1.z, l(1.000000)
mad r1.x, r2.y, l(25.000000), r1.x
mad r1.z, r0.w, r1.y, -r0.w
mad r0.w, r1.z, r0.w, l(1.000000)
mul r0.w, r0.w, r0.w
div r0.w, r1.y, r0.w
mul r0.w, r0.w, r1.x
mul r0.w, r0.w, l(0.0397887304)
mul r1.xyz, r0.wwww, r9.xyzx
mul r1.xyz, r2.xxxx, r1.xyzx
add r0.w, -r3.w, l(1.000000)
sqrt r2.x, r0.w
mul r2.y, r2.x, l(8.000000)
max r4.x, r6.y, l(0.000100)
log r4.x, r4.x
mul r4.y, r4.x, cb0[43].x
exp r4.y, r4.y
add r4.z, r1.w, r4.y
log r4.z, r4.z
mul r4.z, r3.w, r4.z
exp r4.z, r4.z
add r4.z, r4.y, r4.z
add_sat r4.z, r4.z, l(-1.000000)
mad_sat r4.z, cb0[42].x, r4.z, cb0[42].y
add r4.z, -r4.y, r4.z
mad r4.y, r3.w, r4.z, r4.y
lt r4.z, l(-0.500000), cb0[48].x
add r8.xyz, -v4.xyzx, cb12[7].xyzx
dp3 r4.w, r8.xyzx, r8.xyzx
sqrt r4.w, r4.w
mad_sat r4.w, r4.w, cb0[45].x, cb0[45].y
add r6.y, -cb0[47].x, cb0[48].x
mad r4.w, r4.w, r6.y, cb0[47].x
movc r4.z, r4.z, r4.w, cb0[47].x
mad r7.w, r2.z, r2.w, l(1.000000)
dp3 r2.z, r7.xywx, r7.xywx
rsq r2.z, r2.z
mul r2.zw, r2.zzzz, r7.xxxy
mad r2.zw, r2.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
sample_l_indexable(texture2d)(float,float,float,float) r2.yzw, r2.zwzz, t6.wxyz, s7, r2.y
mul r2.yzw, r4.yyyy, r2.yyzw
mul r8.xyz, r4.zzzz, r2.yzwy
mul r4.y, r2.x, cb8[25].w
sample_l_indexable(texturecube)(float,float,float,float) r9.xyzw, r7.xyzx, t25.xyzw, s8, r4.y
lt r4.y, cb8[29].w, l(0.500000)
mul r10.xyz, r9.xyzx, r9.xyzx
movc r9.xyz, r4.yyyy, r10.xyzx, r9.xyzx
mul r10.xyz, v4.yyyy, cb8[33].xyzx
mad r10.xyz, cb8[32].xyzx, v4.xxxx, r10.xyzx
mad r10.xyz, cb8[34].xyzx, v4.zzzz, r10.xyzx
add r10.xyz, r10.xyzx, cb8[35].xyzx
mul r4.x, r4.x, cb0[40].x
exp r4.x, r4.x
add r4.y, r1.w, r4.x
log r4.y, r4.y
mul r4.y, r3.w, r4.y
exp r4.y, r4.y
add r4.y, r4.x, r4.y
add_sat r4.y, r4.y, l(-1.000000)
mad_sat r4.y, cb0[39].x, r4.y, cb0[39].y
add r4.y, -r4.x, r4.y
mad r4.x, r3.w, r4.y, r4.x
mul r4.y, r4.x, cb8[24].w
add r11.xyz, cb8[30].xyzx, cb8[31].xyzx
mul r11.xyz, r4.yyyy, r11.xyzx
mul r9.xyz, r9.xyzx, r11.xyzx
mov_sat r11.xyz, -r10.xyzx
mad_sat r11.xyz, r11.xyzx, cb8[22].xyzx, -cb8[24].xyzx
add r11.xyz, -r11.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mov_sat r12.xyz, r10.xyzx
mad_sat r12.xyz, r12.xyzx, cb8[23].xyzx, -cb8[25].xyzx
add r12.xyz, -r12.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r4.y, r12.y, r12.x
mul r4.y, r12.z, r4.y
mul r4.y, r11.x, r4.y
mul r4.y, r11.y, r4.y
mul r4.y, r11.z, r4.y
lt r4.w, l(0.000000), cb8[27].w
log r10.xyz, |r10.xyzx|
mul r10.xyz, r10.xyzx, cb8[27].wwww
exp r10.xyz, r10.xyzx
dp3 r6.y, r10.xyzx, cb8[27].xyzx
log r6.y, r6.y
mul r6.y, r6.y, cb8[28].x
exp r6.y, r6.y
mad_sat r6.y, cb8[28].y, r6.y, cb8[28].z
add r6.y, -r6.y, l(1.000000)
mul r6.y, r4.y, r6.y
movc r4.y, r4.w, r6.y, r4.y
mul r4.y, r4.y, r9.w
lt r4.w, l(0.000000), cb8[29].y
mul r10.xyz, r9.xyzx, cb0[49].xxxx
mul r9.xyz, r9.xyzx, cb0[46].xxxx
movc r9.xyz, r4.wwww, r10.xyzx, r9.xyzx
mul r4.y, r4.y, cb8[28].w
mad r2.yzw, -r2.yyzw, r4.zzzz, r9.xxyz
mad r2.yzw, r4.yyyy, r2.yyzw, r8.xxyz
mul r2.x, r2.x, cb8[11].w
sample_l_indexable(texturecube)(float,float,float,float) r7.xyzw, r7.xyzx, t24.xyzw, s8, r2.x
lt r2.x, cb8[15].w, l(0.500000)
mul r4.yzw, r7.xxyz, r7.xxyz
movc r4.yzw, r2.xxxx, r4.yyzw, r7.xxyz
mul r7.xyz, v4.yyyy, cb8[19].xyzx
mad r7.xyz, cb8[18].xyzx, v4.xxxx, r7.xyzx
mad r7.xyz, cb8[20].xyzx, v4.zzzz, r7.xyzx
add r7.xyz, r7.xyzx, cb8[21].xyzx
mul r2.x, r4.x, cb8[10].w
add r8.xyz, cb8[16].xyzx, cb8[17].xyzx
mul r8.xyz, r2.xxxx, r8.xyzx
mul r4.xyz, r4.yzwy, r8.xyzx
mov_sat r8.xyz, -r7.xyzx
mad_sat r8.xyz, r8.xyzx, cb8[8].xyzx, -cb8[10].xyzx
add r8.xyz, -r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mov_sat r9.xyz, r7.xyzx
mad_sat r9.xyz, r9.xyzx, cb8[9].xyzx, -cb8[11].xyzx
add r9.xyz, -r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r2.x, r9.y, r9.x
mul r2.x, r9.z, r2.x
mul r2.x, r8.x, r2.x
mul r2.x, r8.y, r2.x
mul r2.x, r8.z, r2.x
lt r4.w, l(0.000000), cb8[13].w
log r7.xyz, |r7.xyzx|
mul r7.xyz, r7.xyzx, cb8[13].wwww
exp r7.xyz, r7.xyzx
dp3 r6.y, r7.xyzx, cb8[13].xyzx
log r6.y, r6.y
mul r6.y, r6.y, cb8[14].x
exp r6.y, r6.y
mad_sat r6.y, cb8[14].y, r6.y, cb8[14].z
add r6.y, -r6.y, l(1.000000)
mul r6.y, r2.x, r6.y
movc r2.x, r4.w, r6.y, r2.x
mul r2.x, r2.x, r7.w
lt r4.w, l(0.000000), cb8[15].y
mul r7.xyz, r4.xyzx, cb0[49].xxxx
mul r4.xyz, r4.xyzx, cb0[46].xxxx
movc r4.xyz, r4.wwww, r7.xyzx, r4.xyzx
mul r2.x, r2.x, cb8[14].w
add r4.xyz, -r2.yzwy, r4.xyzx
mad r2.xyz, r2.xxxx, r4.xyzx, r2.yzwy
add_sat r1.w, -r1.w, l(1.000000)
mul r2.w, r1.w, r1.w
mul r2.w, r2.w, r2.w
mul r1.w, r1.w, r2.w
add r0.w, r0.w, r0.w
min r0.w, r0.w, l(1.000000)
add r0.w, -r0.w, l(1.000000)
mul r2.w, r0.w, r1.w
mad r3.w, r3.w, l(0.600000), l(0.400000)
mad r0.w, -r1.w, r0.w, l(1.000000)
mul r0.w, r0.w, r3.w
mad r0.w, r0.w, l(0.040000), r2.w
max r1.w, r5.w, l(0.001000)
div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), r1.w
mul r0.w, r0.w, r1.w
mul r1.xyz, r1.wwww, r1.xyzx
mul r2.xyz, r2.xyzx, r0.wwww
mad r1.xyz, r1.xyzx, l(0.040000, 0.040000, 0.040000, 0.000000), r2.xyzx
mad r1.xyz, r5.xyzx, r6.xzwx, r1.xyzx
mul r1.xyz, r1.xyzx, cb13[1].xxxx
mul r0.w, l(0.750000), cb0[7].x
max r0.w, r0.w, l(0.000000)
dp3 r1.w, r3.xyzx, r3.xyzx
sqrt r1.w, r1.w
mad_sat r2.x, r1.w, cb0[3].x, cb0[3].y
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.xyxx, t11.xyzw, s2
sample_indexable(texture2d)(float,float,float,float) r6.xyzw, r0.xyxx, t13.xyzw, s2
add r4.xyzw, r4.xyzw, -r6.xyzw
mad r2.xyzw, r2.xxxx, r4.xyzw, r6.xyzw
div r3.x, r3.z, r1.w
add r0.w, -r0.w, r1.w
mul_sat r0.w, r0.w, l(0.000020)
sqrt r4.x, r0.w
mad r4.y, r3.x, l(0.500000), l(0.500000)
sample_l_indexable(texture2d)(float,float,float,float) r3.xyzw, r4.xyxx, t15.xyzw, s3, l(0.000000)
mul r0.w, cb0[5].x, cb13[1].x
mad r4.x, r3.w, cb0[6].x, -r3.w
mad r2.w, r2.w, r4.x, r2.w
mul r2.w, r0.w, r2.w
mad r0.w, -r0.w, r3.w, r0.w
mul r2.xyz, r0.wwww, r2.xyzx
mad r2.xyz, cb0[4].xyzx, r2.wwww, r2.xyzx
mul r0.w, r1.w, l(0.015625)
min r0.w, r0.w, l(1.000000)
sqrt r0.z, r0.w
sample_l_indexable(texture3d)(float,float,float,float) r0.z, r0.xyzx, t21.yzxw, s1, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.xyxx, t20.xyzw, s1, l(0.000000)
add r4.xyzw, r4.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
mad r0.xyzw, r0.zzzz, r4.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
mul r1.xyz, r1.xyzx, r3.xyzx
mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
add r0.xyz, r2.xyzx, r0.xyzx
mul o0.xyz, r5.wwww, r0.xyzx
mov o0.w, r5.w
ret
// Approximately 0 instruction slots used
