//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Thu Jun 29 22:54:12 2023
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float
// TEXCOORD                 1   xyzw        1     NONE   float
// TEXCOORD                 2   xyzw        2     NONE   float      w
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// TEXCOORD                 8   xyzw        5     NONE   float    y
// SV_POSITION              0   xyzw        6      POS   float   xy
// SV_isFrontFace           0   x           7    FFACE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[42], immediateIndexed
dcl_constantbuffer cb13[2], immediateIndexed
dcl_constantbuffer cb12[15], immediateIndexed
dcl_constantbuffer cb8[8], immediateIndexed
dcl_constantbuffer cb7[63], dynamicIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texture2d (float,float,float,float) t26
dcl_resource_texture2d (float,float,float,float) t27
dcl_resource_texture2d (float,float,float,float) t28
dcl_resource_texture2d (float,float,float,float) t29
dcl_resource_texture2d (float,float,float,float) t30
dcl_resource_texture2d (float,float,float,float) t31
dcl_input_ps linear v2.w
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.y
dcl_input_ps_siv linear noperspective v6.xy, position
dcl_output o0.xyzw
dcl_temps 9
mul r0.xy, v6.xyxx, cb12[12].zwzz
add r1.xyz, -v4.xyzx, cb12[14].xyzx
ftou r0.w, v2.w
uge r1.w, r0.w, l(4)
if_nz r1.w
  mad r2.xy, v3.zwzz, cb7[6].xyxx, cb7[6].zwzz
  sample_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t8.xyzw, s1
else
  uge r1.w, r0.w, l(2)
  if_nz r1.w
    mad r3.xy, v3.zwzz, cb7[3].xyxx, cb7[3].zwzz
    sample_indexable(texture2d)(float,float,float,float) r2.xyz, r3.xyxx, t6.xyzw, s1
  else
    mad r3.xy, v3.zwzz, cb7[0].xyxx, cb7[0].zwzz
    sample_indexable(texture2d)(float,float,float,float) r2.xyz, r3.xyxx, t4.xyzw, s1
  endif
endif
imad r3.xyzw, l(9, 9, 9, 9), r0.wwww, l(9, 11, 14, 15)
imad r0.w, l(9), r0.w, l(17)
mov_sat r1.w, cb7[r3.y + 0].x
mov_sat r0.w, cb7[r0.w + 0].x
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, v3.xyxx, t0.xyzw, s3
sample_indexable(texture2d)(float,float,float,float) r2.w, v3.xyxx, t2.xyzw, s4
ge r3.y, r2.w, l(0.156862751)
and r3.y, r3.y, l(0x3f800000)
add r2.w, r2.w, l(-0.188235298)
mul_sat r2.w, r2.w, l(1.231884)
mad_sat r2.w, cb7[r3.w + 0].y, r2.w, cb7[r3.w + 0].x
mad_sat r2.w, cb7[r3.w + 0].w, r2.w, cb7[r3.w + 0].z
mul_sat r5.xyz, r2.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r2.xyz, r2.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad_sat r6.xyz, cb7[r3.x + 0].xyzx, r5.xyzx, r2.xyzx
add r6.xyz, r6.xyzx, -cb7[r3.x + 0].xyzx
mad r6.xyz, r1.wwww, r6.xyzx, cb7[r3.x + 0].xyzx
mul_sat r7.xyz, r4.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r8.xyz, r4.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad_sat r6.xyz, r6.xyzx, r7.xyzx, r8.xyzx
mad_sat r2.xyz, cb7[r3.z + 0].xyzx, r5.xyzx, r2.xyzx
add r2.xyz, r2.xyzx, -cb7[r3.z + 0].xyzx
mad r2.xyz, r0.wwww, r2.xyzx, cb7[r3.z + 0].xyzx
mad_sat r2.xyz, r2.xyzx, r7.xyzx, r8.xyzx
add r5.xyz, -r2.xyzx, r6.xyzx
mad r2.xyz, r2.wwww, r5.xyzx, r2.xyzx
add r2.xyz, -r4.xyzx, r2.xyzx
mad r2.xyz, r3.yyyy, r2.xyzx, r4.xyzx
mul r0.w, v5.y, cb0[7].x
max r0.w, r0.w, l(0.000000)
log r0.w, r0.w
mul r0.w, r0.w, cb0[8].x
exp r0.w, r0.w
add r5.x, r0.w, cb0[9].x
mov r5.y, l(0)
sample_indexable(texture2d)(float,float,float,float) r0.w, r5.xyxx, t26.yzwx, s5
mad_sat r0.w, r0.w, cb0[10].x, cb0[10].y
mad r5.xyzw, cb0[12].xyzw, r0.wwww, cb0[11].xyzw
mad r3.zw, v3.xxxy, cb0[13].xxxy, cb0[13].zzzw
sample_indexable(texture2d)(float,float,float,float) r3.zw, r3.zwzz, t27.zwxy, s2
add r3.zw, r3.zzzw, -cb0[15].xxxy
mad r3.zw, r3.zzzw, cb0[14].xxxx, v3.xxxy
mad r3.zw, r3.zzzw, cb0[16].xxxy, cb0[16].zzzw
sample_indexable(texture2d)(float,float,float,float) r6.xyz, r3.zwzz, t28.xyzw, s2
mad r3.zw, v3.xxxy, cb0[17].xxxy, cb0[17].zzzw
sample_indexable(texture2d)(float,float,float,float) r7.xyz, r3.zwzz, t29.xyzw, s2
mov r7.w, l(1.000000)
mad r3.zw, v3.yyyx, cb0[19].yyyx, cb0[19].wwwz
round_ne r8.xy, r3.zwzz
add r3.zw, r3.zzzw, -r8.xxxy
mad r8.xy, |r3.zwzz|, l(-16.000000, -16.000000, 0.000000, 0.000000), l(8.000000, 8.000000, 0.000000, 0.000000)
mul r3.zw, r3.zzzw, r8.xxxy
mad r8.xy, |r3.zwzz|, l(0.225000, 0.225000, 0.000000, 0.000000), l(0.775000, 0.775000, 0.000000, 0.000000)
mul r3.zw, r3.zzzw, r8.xxxy
mad r3.zw, cb0[20].yyyx, r3.zzzw, v3.xxxy
mad r8.xy, r3.wzww, cb0[21].yxyy, cb0[21].wzww
round_ne r8.zw, r8.xxxy
add r8.xy, -r8.zwzz, r8.xyxx
mad r8.zw, |r8.xxxy|, l(0.000000, 0.000000, -16.000000, -16.000000), l(0.000000, 0.000000, 8.000000, 8.000000)
mul r8.xy, r8.zwzz, r8.xyxx
mad r8.zw, |r8.xxxy|, l(0.000000, 0.000000, 0.225000, 0.225000), l(0.000000, 0.000000, 0.775000, 0.775000)
mul r8.xy, r8.zwzz, r8.xyxx
mad r3.zw, cb0[22].yyyx, r8.xxxy, r3.zzzw
mad r0.w, r3.w, cb0[23].y, cb0[23].w
mad r8.xy, r3.zwzz, cb0[24].xyxx, cb0[24].zwzz
sample_indexable(texture2d)(float,float,float,float) r1.w, r8.xyxx, t30.xzwy, s2
add r1.w, r1.w, -cb0[26].y
mad r0.w, r1.w, cb0[25].x, r0.w
frc r0.w, r0.w
add r1.w, r0.w, cb0[27].z
mad_sat r1.w, cb0[27].y, |r1.w|, cb0[27].x
add r0.w, r0.w, cb0[28].z
mad_sat r0.w, cb0[28].y, |r0.w|, cb0[28].x
add r0.w, r0.w, r1.w
min r0.w, r0.w, l(1.000000)
mad r8.xy, r3.zwzz, cb0[29].xyxx, cb0[29].zwzz
mul r1.w, cb0[7].x, cb0[30].x
sample_indexable(texture2d)(float,float,float,float) r3.zw, r3.zwzz, t30.zwxy, s2
add r3.zw, r3.zzzw, -cb0[31].xxxy
mad r3.zw, r3.zzzw, r1.wwww, r8.xxxy
sample_indexable(texture2d)(float,float,float,float) r1.w, r3.zwzz, t31.yzwx, s2
add r2.w, -r1.w, l(1.000000)
max r2.w, r2.w, l(0.000000)
log r2.w, r2.w
mul r2.w, r2.w, cb0[32].x
exp r2.w, r2.w
mad r2.w, r2.w, cb0[33].x, cb0[7].x
log r0.w, r0.w
mul r0.w, r0.w, r2.w
exp r0.w, r0.w
add_sat r0.w, r0.w, cb0[34].x
add r1.w, r1.w, cb0[35].x
mad r8.xyz, r0.wwww, r1.wwww, cb0[34].xxxx
mov r8.w, l(1.000000)
mul r8.xyzw, r8.xyzw, cb0[36].xyzw
mad r7.xyzw, r7.xyzw, cb0[18].xyzw, r8.xyzw
mov r6.w, l(1.000000)
add r6.xyzw, r7.xyzw, r6.xyzw
mul r5.xyzw, r5.xyzw, r6.xyzw
mad_sat r5.xyzw, r5.xyzw, cb0[37].xxxx, cb0[37].yyyy
mul r5.xyzw, r5.xyzw, cb0[6].xyzw
mov_sat r0.w, v5.y
mad r6.xyzw, cb0[39].xyzw, r0.wwww, cb0[38].xyzw
mul r5.xyzw, r5.xyzw, r6.xyzw
mul r4.xyzw, r4.xyzw, r5.xyzw
add r0.w, -v5.y, l(1.000000)
mul r0.w, r0.w, r0.w
add r1.w, cb0[40].x, cb0[41].x
mul r0.w, r0.w, r1.w
mul r5.xyzw, r0.wwww, r4.xyzw
mul_sat r6.xyz, r2.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
add_sat r2.xyz, r2.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mad r2.xyz, cb7[r3.x + 0].xyzx, r6.xyzx, r2.xyzx
mad r2.xyz, -r4.xyzx, r0.wwww, r2.xyzx
mad r2.xyz, r3.yyyy, r2.xyzx, r5.xyzx
mad r0.w, -r4.w, r0.w, l(1.000000)
mad r0.w, r3.y, r0.w, r5.w
mul r2.xyz, r2.xyzx, cb13[1].wwww
mul r2.xyz, r2.xyzx, cb13[1].xxxx
dp3 r1.x, -r1.xyzx, -r1.xyzx
sqrt r1.x, r1.x
mul r1.x, r1.x, l(0.015625)
min r1.x, r1.x, l(1.000000)
sqrt r0.z, r1.x
sample_l_indexable(texture3d)(float,float,float,float) r0.z, r0.xyzx, t21.yzxw, s6, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t20.wxyz, s6, l(0.000000)
add r0.x, r0.x, l(-1.000000)
mad r0.x, r0.z, r0.x, l(1.000000)
mul r1.xyz, r2.xyzx, cb8[7].xyzx
mul r0.x, r0.x, r0.w
mul o0.xyz, r0.xxxx, r1.xyzx
mov o0.w, l(0)
ret
// Approximately 0 instruction slots used
